/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahmed Kassem
 */
public class acc_lest extends javax.swing.JFrame {

    int mousex;
    int mousey;

    /**
     * Creates new form acc_lest
     */
    public acc_lest() {
        initComponents();
        x1.setEnabled(false);
        x1.setVisible(false);
        _1.setEnabled(false);
        _1.setVisible(false);
        employee1.setEnabled(false);
        employee1.setVisible(false);
        employee2.setEnabled(false);
        employee2.setVisible(false);
        doctor1.setEnabled(false);
        doctor1.setVisible(false);
        doctor2.setEnabled(false);
        doctor2.setVisible(false);
        exit1.setEnabled(false);
        exit1.setVisible(false);

        Doc.setEnabled(false);
        Doc.setVisible(false);
        Emp.setEnabled(false);
        Emp.setVisible(false);

        detailsE.setEnabled(false);
        detailsE.setVisible(false);
        totalE.setEnabled(false);
        totalE.setVisible(false);
        detailsD.setEnabled(false);
        detailsD.setVisible(false);
        totalD.setEnabled(false);
        totalD.setVisible(false);

        days.setEnabled(false);
        days.setVisible(false);
        day.setEnabled(false);
        day.setVisible(false);
        dayst.setEnabled(false);
        dayst.setVisible(false);
        dayt.setEnabled(false);
        dayt.setVisible(false);

        daysD.setEnabled(false);
        daysD.setVisible(false);
        dayD.setEnabled(false);
        dayD.setVisible(false);
        daystD.setEnabled(false);
        daystD.setVisible(false);
        daytD.setEnabled(false);
        daytD.setVisible(false);

        dE1.setEnabled(false);
        dE1.setVisible(false);
        dE2.setEnabled(false);
        dE2.setVisible(false);
        tE1.setEnabled(false);
        tE1.setVisible(false);
        tE2.setEnabled(false);
        tE2.setVisible(false);

        dD1.setEnabled(false);
        dD1.setVisible(false);
        dD2.setEnabled(false);
        dD2.setVisible(false);
        tD1.setEnabled(false);
        tD1.setVisible(false);
        tD2.setEnabled(false);
        tD2.setVisible(false);

        serchdsE1.setEnabled(false);
        serchdsE1.setVisible(false);
        serchdsE2.setEnabled(false);
        serchdsE2.setVisible(false);
        serchdE1.setEnabled(false);
        serchdE1.setVisible(false);
        serchdE2.setEnabled(false);
        serchdE2.setVisible(false);

        serchdsEt1.setEnabled(false);
        serchdsEt1.setVisible(false);
        serchdsEt2.setEnabled(false);
        serchdsEt2.setVisible(false);
        serchdEt1.setEnabled(false);
        serchdEt1.setVisible(false);
        serchdEt2.setEnabled(false);
        serchdEt2.setVisible(false);

        serchdsD1.setEnabled(false);
        serchdsD1.setVisible(false);
        serchdsD2.setEnabled(false);
        serchdsD2.setVisible(false);
        serchdD1.setEnabled(false);
        serchdD1.setVisible(false);
        serchdD2.setEnabled(false);
        serchdD2.setVisible(false);

        serchdstD1.setEnabled(false);
        serchdstD1.setVisible(false);
        serchdtD1.setEnabled(false);
        serchdtD1.setVisible(false);
        DocName.setVisible(false);
        DocName.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btndetailsE = new javax.swing.ButtonGroup();
        btntotalE = new javax.swing.ButtonGroup();
        btndetailsD = new javax.swing.ButtonGroup();
        btntotalD = new javax.swing.ButtonGroup();
        bar = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        _ = new javax.swing.JLabel();
        _1 = new javax.swing.JLabel();
        employee = new javax.swing.JLabel();
        employee1 = new javax.swing.JLabel();
        employee2 = new javax.swing.JLabel();
        doctor = new javax.swing.JLabel();
        doctor1 = new javax.swing.JLabel();
        doctor2 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        Doc = new javax.swing.JPanel();
        dD = new javax.swing.JLabel();
        dD1 = new javax.swing.JLabel();
        dD2 = new javax.swing.JLabel();
        tD = new javax.swing.JLabel();
        tD1 = new javax.swing.JLabel();
        tD2 = new javax.swing.JLabel();
        detailsD = new javax.swing.JPanel();
        btndayD = new javax.swing.JRadioButton();
        btndaysD = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        detailsDLest = new javax.swing.JTable();
        dayD = new javax.swing.JPanel();
        serchdD = new javax.swing.JLabel();
        serchdD1 = new javax.swing.JLabel();
        serchdD2 = new javax.swing.JLabel();
        datedayD = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        daysD = new javax.swing.JPanel();
        serchdsD = new javax.swing.JLabel();
        serchdsD1 = new javax.swing.JLabel();
        serchdsD2 = new javax.swing.JLabel();
        datefromD = new com.toedter.calendar.JDateChooser();
        datetoD = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        totalD = new javax.swing.JPanel();
        btndaytD = new javax.swing.JRadioButton();
        btndaystD = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        totalDLest = new javax.swing.JTable();
        daystD = new javax.swing.JPanel();
        serchdstD = new javax.swing.JLabel();
        serchdstD1 = new javax.swing.JLabel();
        datefromtD = new com.toedter.calendar.JDateChooser();
        datetotD = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        daytD = new javax.swing.JPanel();
        serchdtD = new javax.swing.JLabel();
        serchdtD1 = new javax.swing.JLabel();
        datedaytD = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        DocName = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Emp = new javax.swing.JPanel();
        dE = new javax.swing.JLabel();
        dE1 = new javax.swing.JLabel();
        dE2 = new javax.swing.JLabel();
        tE = new javax.swing.JLabel();
        tE1 = new javax.swing.JLabel();
        tE2 = new javax.swing.JLabel();
        detailsE = new javax.swing.JPanel();
        btnday = new javax.swing.JRadioButton();
        btndays = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailsELest = new javax.swing.JTable();
        days = new javax.swing.JPanel();
        serchdsE = new javax.swing.JLabel();
        serchdsE2 = new javax.swing.JLabel();
        serchdsE1 = new javax.swing.JLabel();
        datefromE = new com.toedter.calendar.JDateChooser();
        datetoE = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        day = new javax.swing.JPanel();
        serchdE = new javax.swing.JLabel();
        serchdE2 = new javax.swing.JLabel();
        serchdE1 = new javax.swing.JLabel();
        datedayE = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        totalE = new javax.swing.JPanel();
        btndayt = new javax.swing.JRadioButton();
        btndayst = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        totalELest = new javax.swing.JTable();
        dayt = new javax.swing.JPanel();
        serchdEt = new javax.swing.JLabel();
        serchdEt2 = new javax.swing.JLabel();
        serchdEt1 = new javax.swing.JLabel();
        datedayEt = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        dayst = new javax.swing.JPanel();
        serchdsEt = new javax.swing.JLabel();
        serchdsEt2 = new javax.swing.JLabel();
        serchdsEt1 = new javax.swing.JLabel();
        datefromEt = new com.toedter.calendar.JDateChooser();
        datetoEt = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        main = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barMouseDragged(evt);
            }
        });
        bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barMousePressed(evt);
            }
        });
        getContentPane().add(bar);
        bar.setBounds(0, 0, 900, 20);

        x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });
        getContentPane().add(x);
        x.setBounds(919, 1, 22, 18);

        x1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/13.png"))); // NOI18N
        x1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(x1);
        x1.setBounds(917, -1, 24, 21);

        _.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _MouseExited(evt);
            }
        });
        getContentPane().add(_);
        _.setBounds(896, 0, 22, 20);

        _1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/15.png"))); // NOI18N
        getContentPane().add(_1);
        _1.setBounds(896, 0, 22, 20);

        employee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                employeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeeMouseExited(evt);
            }
        });
        getContentPane().add(employee);
        employee.setBounds(16, 268, 195, 33);

        employee1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestالموظفين.png"))); // NOI18N
        getContentPane().add(employee1);
        employee1.setBounds(16, 268, 195, 33);

        employee2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestالموظفين.png"))); // NOI18N
        getContentPane().add(employee2);
        employee2.setBounds(16, 268, 195, 33);

        doctor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                doctorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                doctorMouseExited(evt);
            }
        });
        getContentPane().add(doctor);
        doctor.setBounds(17, 333, 195, 33);

        doctor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestالاطباء.png"))); // NOI18N
        getContentPane().add(doctor1);
        doctor1.setBounds(17, 333, 195, 33);

        doctor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestالاطباء.png"))); // NOI18N
        getContentPane().add(doctor2);
        doctor2.setBounds(17, 333, 195, 33);

        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(16, 398, 195, 33);

        exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/خروج.png"))); // NOI18N
        getContentPane().add(exit1);
        exit1.setBounds(16, 398, 195, 33);

        Doc.setLayout(null);

        dD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dDMouseExited(evt);
            }
        });
        Doc.add(dD);
        dD.setBounds(499, 5, 202, 33);

        dD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestتفاصيل ط.png"))); // NOI18N
        Doc.add(dD1);
        dD1.setBounds(499, 5, 202, 33);

        dD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestتفاصيل ط.png"))); // NOI18N
        Doc.add(dD2);
        dD2.setBounds(499, 5, 202, 33);

        tD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tDMouseExited(evt);
            }
        });
        Doc.add(tD);
        tD.setBounds(295, 5, 202, 33);

        tD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestنهائي ط.png"))); // NOI18N
        Doc.add(tD1);
        tD1.setBounds(295, 5, 202, 33);

        tD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestنهائي ط.png"))); // NOI18N
        Doc.add(tD2);
        tD2.setBounds(295, 5, 202, 33);

        detailsD.setLayout(null);

        btndayD.setOpaque(false);
        btndayD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btndayDItemStateChanged(evt);
            }
        });
        detailsD.add(btndayD);
        btndayD.setBounds(584, 25, 21, 21);

        btndaysD.setOpaque(false);
        btndaysD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btndaysDItemStateChanged(evt);
            }
        });
        detailsD.add(btndaysD);
        btndaysD.setBounds(496, 25, 21, 21);

        jScrollPane2.setBorder(null);

        detailsDLest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        detailsDLest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "حساب رقم", "التاريخ", "اسم الطبيب", "سعر الكشف", "عدد الكشف", "السعر الاجمالي", "نسبة الموظفين", "حساب الطبيب"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        detailsDLest.setSelectionBackground(new java.awt.Color(0, 102, 215));
        jScrollPane2.setViewportView(detailsDLest);

        detailsD.add(jScrollPane2);
        jScrollPane2.setBounds(3, 61, 690, 270);

        dayD.setLayout(null);

        serchdD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serchdD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serchdDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                serchdDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                serchdDMouseExited(evt);
            }
        });
        dayD.add(serchdD);
        serchdD.setBounds(14, 6, 40, 38);

        serchdD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestبحث.png"))); // NOI18N
        dayD.add(serchdD1);
        serchdD1.setBounds(14, 6, 40, 38);

        serchdD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestبحث2.png"))); // NOI18N
        dayD.add(serchdD2);
        serchdD2.setBounds(14, 6, 40, 38);

        datedayD.setDateFormatString("yyyy-MM-dd");
        dayD.add(datedayD);
        datedayD.setBounds(71, 10, 190, 27);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestبحث باليوم.png"))); // NOI18N
        dayD.add(jLabel10);
        jLabel10.setBounds(0, 0, 360, 48);

        detailsD.add(dayD);
        dayD.setBounds(22, 10, 360, 48);

        daysD.setLayout(null);

        serchdsD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serchdsD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serchdsDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                serchdsDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                serchdsDMouseExited(evt);
            }
        });
        daysD.add(serchdsD);
        serchdsD.setBounds(14, 6, 40, 38);

        serchdsD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestبحث.png"))); // NOI18N
        daysD.add(serchdsD1);
        serchdsD1.setBounds(14, 6, 40, 38);

        serchdsD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestبحث2.png"))); // NOI18N
        daysD.add(serchdsD2);
        serchdsD2.setBounds(14, 6, 40, 38);

        datefromD.setDateFormatString("yyyy-MM-dd");
        daysD.add(datefromD);
        datefromD.setBounds(237, 11, 120, 27);

        datetoD.setDateFormatString("yyyy-MM-dd");
        daysD.add(datetoD);
        datetoD.setBounds(57, 11, 120, 27);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestبحث بالفترة.png"))); // NOI18N
        daysD.add(jLabel9);
        jLabel9.setBounds(0, 0, 420, 48);

        detailsD.add(daysD);
        daysD.setBounds(22, 10, 420, 48);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_LestE_D.png"))); // NOI18N
        detailsD.add(jLabel8);
        jLabel8.setBounds(0, 0, 698, 334);

        Doc.add(detailsD);
        detailsD.setBounds(4, 35, 698, 334);

        totalD.setLayout(null);

        btndaytD.setOpaque(false);
        btndaytD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btndaytDItemStateChanged(evt);
            }
        });
        totalD.add(btndaytD);
        btndaytD.setBounds(584, 25, 21, 21);

        btndaystD.setOpaque(false);
        btndaystD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btndaystDItemStateChanged(evt);
            }
        });
        totalD.add(btndaystD);
        btndaystD.setBounds(496, 25, 21, 21);

        jScrollPane4.setBorder(null);

        totalDLest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totalDLest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "التاريخ", "اسم الطبيب", "الحساب قبل الخصم", "الخصم", "الحساب بعد الخصم"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        totalDLest.setSelectionBackground(new java.awt.Color(0, 102, 215));
        jScrollPane4.setViewportView(totalDLest);

        totalD.add(jScrollPane4);
        jScrollPane4.setBounds(3, 61, 690, 270);

        daystD.setLayout(null);

        serchdstD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serchdstD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serchdstDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                serchdstDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                serchdstDMouseExited(evt);
            }
        });
        daystD.add(serchdstD);
        serchdstD.setBounds(14, 6, 40, 38);

        serchdstD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestبحث.png"))); // NOI18N
        daystD.add(serchdstD1);
        serchdstD1.setBounds(14, 6, 40, 38);

        datefromtD.setDateFormatString("yyyy-MM-dd");
        daystD.add(datefromtD);
        datefromtD.setBounds(237, 11, 120, 27);

        datetotD.setDateFormatString("yyyy-MM-dd");
        daystD.add(datetotD);
        datetotD.setBounds(57, 11, 120, 27);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestبحث بالفترة.png"))); // NOI18N
        daystD.add(jLabel12);
        jLabel12.setBounds(0, 0, 420, 48);

        totalD.add(daystD);
        daystD.setBounds(22, 10, 420, 48);

        daytD.setLayout(null);

        serchdtD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serchdtD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serchdtDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                serchdtDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                serchdtDMouseExited(evt);
            }
        });
        daytD.add(serchdtD);
        serchdtD.setBounds(14, 6, 40, 38);

        serchdtD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestبحث.png"))); // NOI18N
        daytD.add(serchdtD1);
        serchdtD1.setBounds(14, 6, 40, 38);

        datedaytD.setDateFormatString("yyyy-MM-dd");
        daytD.add(datedaytD);
        datedaytD.setBounds(71, 10, 190, 27);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestبحث باليوم.png"))); // NOI18N
        daytD.add(jLabel13);
        jLabel13.setBounds(0, 0, 360, 48);

        totalD.add(daytD);
        daytD.setBounds(22, 10, 360, 48);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_LestE_D.png"))); // NOI18N
        totalD.add(jLabel11);
        jLabel11.setBounds(0, 0, 698, 334);

        Doc.add(totalD);
        totalD.setBounds(4, 35, 698, 334);

        DocName.setLayout(null);

        Dname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Dname.setForeground(new java.awt.Color(56, 148, 233));
        DocName.add(Dname);
        Dname.setBounds(5, 3, 145, 24);

        Doname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Doname.setForeground(new java.awt.Color(56, 148, 233));
        DocName.add(Doname);
        Doname.setBounds(5, 3, 145, 24);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ReportAccName.png"))); // NOI18N
        DocName.add(jLabel15);
        jLabel15.setBounds(0, 0, 251, 31);

        Doc.add(DocName);
        DocName.setBounds(5, 4, 251, 31);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestالطبيب.png"))); // NOI18N
        Doc.add(jLabel14);
        jLabel14.setBounds(0, 0, 706, 376);

        getContentPane().add(Doc);
        Doc.setBounds(230, 107, 706, 376);

        Emp.setLayout(null);

        dE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dEMouseExited(evt);
            }
        });
        Emp.add(dE);
        dE.setBounds(499, 5, 202, 33);

        dE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestتفاصيل م.png"))); // NOI18N
        Emp.add(dE1);
        dE1.setBounds(499, 5, 202, 33);

        dE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestتفاصيل م.png"))); // NOI18N
        Emp.add(dE2);
        dE2.setBounds(499, 5, 202, 33);

        tE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tEMouseExited(evt);
            }
        });
        Emp.add(tE);
        tE.setBounds(295, 5, 202, 33);

        tE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestنهائي م.png"))); // NOI18N
        Emp.add(tE1);
        tE1.setBounds(295, 5, 202, 33);

        tE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestنهائي م.png"))); // NOI18N
        Emp.add(tE2);
        tE2.setBounds(295, 5, 202, 33);

        detailsE.setLayout(null);

        btnday.setOpaque(false);
        btnday.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btndayItemStateChanged(evt);
            }
        });
        detailsE.add(btnday);
        btnday.setBounds(584, 25, 21, 21);

        btndays.setOpaque(false);
        btndays.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btndaysItemStateChanged(evt);
            }
        });
        detailsE.add(btndays);
        btndays.setBounds(496, 25, 21, 21);

        jScrollPane1.setBorder(null);

        detailsELest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        detailsELest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "حساب رقم", "التاريخ", "اسم الموظف", "نسبة الموظف", "عدد الحجز", "سعر الكشف", "حساب الموظف", "اسم الطبيب"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        detailsELest.setSelectionBackground(new java.awt.Color(0, 102, 215));
        jScrollPane1.setViewportView(detailsELest);

        detailsE.add(jScrollPane1);
        jScrollPane1.setBounds(3, 61, 690, 270);

        days.setLayout(null);

        serchdsE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serchdsE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serchdsEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                serchdsEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                serchdsEMouseExited(evt);
            }
        });
        days.add(serchdsE);
        serchdsE.setBounds(14, 6, 40, 38);

        serchdsE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestبحث2.png"))); // NOI18N
        days.add(serchdsE2);
        serchdsE2.setBounds(14, 6, 40, 38);

        serchdsE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestبحث.png"))); // NOI18N
        days.add(serchdsE1);
        serchdsE1.setBounds(14, 6, 40, 38);

        datefromE.setDateFormatString("yyyy-MM-dd");
        days.add(datefromE);
        datefromE.setBounds(237, 11, 120, 27);

        datetoE.setDateFormatString("yyyy-MM-dd");
        days.add(datetoE);
        datetoE.setBounds(57, 11, 120, 27);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestبحث بالفترة.png"))); // NOI18N
        days.add(jLabel4);
        jLabel4.setBounds(0, 0, 420, 48);

        detailsE.add(days);
        days.setBounds(22, 10, 420, 48);

        day.setLayout(null);

        serchdE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serchdE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serchdEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                serchdEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                serchdEMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                serchdEMouseReleased(evt);
            }
        });
        day.add(serchdE);
        serchdE.setBounds(14, 6, 40, 38);

        serchdE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestبحث2.png"))); // NOI18N
        day.add(serchdE2);
        serchdE2.setBounds(14, 6, 40, 38);

        serchdE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestبحث.png"))); // NOI18N
        day.add(serchdE1);
        serchdE1.setBounds(14, 6, 40, 38);

        datedayE.setDateFormatString("yyyy-MM-dd");
        day.add(datedayE);
        datedayE.setBounds(71, 10, 190, 27);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestبحث باليوم.png"))); // NOI18N
        day.add(jLabel2);
        jLabel2.setBounds(0, 0, 360, 48);

        detailsE.add(day);
        day.setBounds(22, 10, 360, 48);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_LestE_D.png"))); // NOI18N
        detailsE.add(jLabel3);
        jLabel3.setBounds(0, 0, 698, 334);

        Emp.add(detailsE);
        detailsE.setBounds(4, 35, 698, 334);

        totalE.setLayout(null);

        btndayt.setOpaque(false);
        btndayt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btndaytItemStateChanged(evt);
            }
        });
        totalE.add(btndayt);
        btndayt.setBounds(584, 25, 21, 21);

        btndayst.setOpaque(false);
        btndayst.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btndaystItemStateChanged(evt);
            }
        });
        totalE.add(btndayst);
        btndayst.setBounds(496, 25, 21, 21);

        jScrollPane3.setBorder(null);

        totalELest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totalELest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "التاريخ", "اسم الموظف", "الحساب قبل الخصم", "الخصم", "الحساب بعد الخصم"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        totalELest.setSelectionBackground(new java.awt.Color(0, 102, 215));
        jScrollPane3.setViewportView(totalELest);

        totalE.add(jScrollPane3);
        jScrollPane3.setBounds(3, 61, 690, 270);

        dayt.setLayout(null);

        serchdEt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serchdEt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serchdEtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                serchdEtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                serchdEtMouseExited(evt);
            }
        });
        dayt.add(serchdEt);
        serchdEt.setBounds(14, 6, 40, 38);

        serchdEt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestبحث2.png"))); // NOI18N
        dayt.add(serchdEt2);
        serchdEt2.setBounds(14, 6, 40, 38);

        serchdEt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestبحث.png"))); // NOI18N
        dayt.add(serchdEt1);
        serchdEt1.setBounds(14, 6, 40, 38);

        datedayEt.setDateFormatString("yyyy-MM-dd");
        dayt.add(datedayEt);
        datedayEt.setBounds(71, 10, 190, 27);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestبحث باليوم.png"))); // NOI18N
        dayt.add(jLabel7);
        jLabel7.setBounds(0, 0, 360, 48);

        totalE.add(dayt);
        dayt.setBounds(22, 10, 360, 48);

        dayst.setLayout(null);

        serchdsEt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serchdsEt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serchdsEtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                serchdsEtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                serchdsEtMouseExited(evt);
            }
        });
        dayst.add(serchdsEt);
        serchdsEt.setBounds(14, 6, 40, 38);

        serchdsEt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestبحث2.png"))); // NOI18N
        dayst.add(serchdsEt2);
        serchdsEt2.setBounds(14, 6, 40, 38);

        serchdsEt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestبحث.png"))); // NOI18N
        dayst.add(serchdsEt1);
        serchdsEt1.setBounds(14, 6, 40, 38);

        datefromEt.setDateFormatString("yyyy-MM-dd");
        dayst.add(datefromEt);
        datefromEt.setBounds(237, 11, 120, 27);

        datetoEt.setDateFormatString("yyyy-MM-dd");
        dayst.add(datetoEt);
        datetoEt.setBounds(57, 11, 120, 27);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestبحث بالفترة.png"))); // NOI18N
        dayst.add(jLabel6);
        jLabel6.setBounds(0, 0, 420, 48);

        totalE.add(dayst);
        dayst.setBounds(22, 10, 420, 48);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_LestE_D.png"))); // NOI18N
        totalE.add(jLabel5);
        jLabel5.setBounds(0, 0, 698, 334);

        Emp.add(totalE);
        totalE.setBounds(4, 35, 698, 334);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lestالموظف.png"))); // NOI18N
        Emp.add(jLabel1);
        jLabel1.setBounds(0, 0, 706, 376);

        getContentPane().add(Emp);
        Emp.setBounds(230, 107, 706, 376);

        main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acc_Lest.png"))); // NOI18N
        getContentPane().add(main);
        main.setBounds(0, 0, 940, 506);

        setBounds(0, 0, 940, 506);
    }// </editor-fold>//GEN-END:initComponents
public void detailsdE() {
        try {
            DefaultTableModel table = new DefaultTableModel();
            table.addColumn("حساب رقم");
            table.addColumn("التاريخ");
            table.addColumn("اسم الموظف");
            table.addColumn("نسبة الموظف");
            table.addColumn("عدد الحجز");
            table.addColumn("سعر الكشف");
            table.addColumn("حساب الموظف");
            table.addColumn("اسم الطبيب");

            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            String dat = f.format(datedayE.getDate());
            Connection con = DB.ConectionDB.setconn();
            Statement st = con.createStatement();
            String strE = "SELECT * FROM accounte WHERE date_acc LIKE '%" + dat + "%'";
            ResultSet r = st.executeQuery(strE);
            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(6),
                    r.getString(9),
                    r.getString(7),
                    r.getString(8),
                    r.getString(3),
                    r.getString(5),});
                detailsELest.setModel(table);
            }

        } catch (Exception ex) {
            ex.getMessage();
        }
    }

    public void detailsdsE() {
        try {
            DefaultTableModel table = new DefaultTableModel();
            table.addColumn("حساب رقم");
            table.addColumn("التاريخ");
            table.addColumn("اسم الموظف");
            table.addColumn("نسبة الموظف");
            table.addColumn("عدد الحجز");
            table.addColumn("سعر الكشف");
            table.addColumn("حساب الموظف");
            table.addColumn("اسم الطبيب");

            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            String datF = f.format(datefromE.getDate());
            String datT = f.format(datetoE.getDate());
            Connection con = DB.ConectionDB.setconn();
            Statement st = con.createStatement();
            String strE = "SELECT * FROM accounte WHERE date_acc BETWEEN '" + datF + "' AND '" + datT + "'";
            ResultSet r = st.executeQuery(strE);
            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(6),
                    r.getString(9),
                    r.getString(7),
                    r.getString(8),
                    r.getString(3),
                    r.getString(5),});
                detailsELest.setModel(table);
            }

        } catch (Exception ex) {
            ex.getMessage();
        }
    }

    public void totaldE() {
        try {
            DefaultTableModel table = new DefaultTableModel();
            table.addColumn("التاريخ");
            table.addColumn("اسم الموظف");
            table.addColumn("الحساب قبل الخصم");
            table.addColumn("الخصم");
            table.addColumn("الحساب بعد الخصم");

            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            String dat = f.format(datedayEt.getDate());
            Connection con = DB.ConectionDB.setconn();
            Statement st = con.createStatement();
            String strE = "SELECT * FROM accounttotale WHERE date_acc LIKE '%" + dat + "%'";
            ResultSet r = st.executeQuery(strE);
            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(6),
                    r.getString(5),
                    r.getString(4),});
                totalELest.setModel(table);
            }

        } catch (Exception ex) {
            ex.getMessage();
        }
    }

    public void totaldsE() {
        try {
            DefaultTableModel table = new DefaultTableModel();
            table.addColumn("التاريخ");
            table.addColumn("اسم الموظف");
            table.addColumn("الحساب قبل الخصم");
            table.addColumn("الخصم");
            table.addColumn("الحساب بعد الخصم");

            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            String datF = f.format(datefromEt.getDate());
            String datT = f.format(datetoEt.getDate());
            Connection con = DB.ConectionDB.setconn();
            Statement st = con.createStatement();
            String strE = "SELECT * FROM accounttotale WHERE date_acc BETWEEN '" + datF + "' AND '" + datT + "'";
            ResultSet r = st.executeQuery(strE);
            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(6),
                    r.getString(5),
                    r.getString(4),});
                totalELest.setModel(table);
            }

        } catch (Exception ex) {
            ex.getMessage();
        }
    }

    public void detailsdD() {
        try {
            DefaultTableModel table = new DefaultTableModel();
            table.addColumn("حساب رقم");
            table.addColumn("التاريخ");
            table.addColumn("اسم الطبيب");
            table.addColumn("سعر الكشف");
            table.addColumn("عدد الكشف");
            table.addColumn("السعر الاجمالي");
            table.addColumn("نسبة الموظفين");
            table.addColumn("حساب الطبيب");

            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            String dat = f.format(datedayD.getDate());
            Connection con = DB.ConectionDB.setconn();
            Statement st = con.createStatement();
            String strE = "SELECT * FROM accountd WHERE date_acc LIKE '%" + dat + "%' AND ";
            if (Doname.isVisible()) {
                strE += " docname like '%" + Doname.getSelectedItem() + "%'";
            } else {
                strE += " docname like '%" + Dname.getText() + "%'";
            }
            ResultSet r = st.executeQuery(strE);
            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(5),
                    r.getString(9),
                    r.getString(6),
                    r.getString(7),
                    r.getString(8),
                    r.getString(3),});
                detailsDLest.setModel(table);
            }

        } catch (Exception ex) {
            ex.getMessage();
        }
    }

    public void detailsdsD() {
        try {
            DefaultTableModel table = new DefaultTableModel();
            table.addColumn("حساب رقم");
            table.addColumn("التاريخ");
            table.addColumn("اسم الطبيب");
            table.addColumn("سعر الكشف");
            table.addColumn("عدد الكشف");
            table.addColumn("السعر الاجمالي");
            table.addColumn("نسبة الموظفين");
            table.addColumn("حساب الطبيب");

            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            String datF = f.format(datefromD.getDate());
            String datT = f.format(datetoD.getDate());
            Connection con = DB.ConectionDB.setconn();
            Statement st = con.createStatement();
            String strE = "SELECT * FROM accountd WHERE date_acc BETWEEN '" + datF + "' AND '" + datT + "' AND ";
            if (Doname.isVisible()) {
                strE += " docname like '%" + Doname.getSelectedItem() + "%'";
            } else {
                strE += " docname like '%" + Dname.getText() + "%'";
            }
            ResultSet r = st.executeQuery(strE);
            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(5),
                    r.getString(9),
                    r.getString(6),
                    r.getString(7),
                    r.getString(8),
                    r.getString(3),});
                detailsDLest.setModel(table);
            }

        } catch (Exception ex) {
            ex.getMessage();
        }
    }

    public void totaldD() {
        try {
            DefaultTableModel table = new DefaultTableModel();
            table.addColumn("التاريخ");
            table.addColumn("اسم الطبيب");
            table.addColumn("الحساب قبل الخصم");
            table.addColumn("الخصم");
            table.addColumn("الحساب بعد الخصم");

            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            String dat = f.format(datedaytD.getDate());
            Connection con = DB.ConectionDB.setconn();
            Statement st = con.createStatement();
            String strE = "SELECT * FROM accounttotald WHERE date_acc LIKE '%" + dat + "%' AND ";
            if (Doname.isVisible()) {
                strE += " dname like '%" + Doname.getSelectedItem() + "%'";
            } else {
                strE += " dname like '%" + Dname.getText() + "%'";
            }
            ResultSet r = st.executeQuery(strE);
            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(6),
                    r.getString(5),
                    r.getString(4),});
                totalDLest.setModel(table);
            }

        } catch (Exception ex) {
            ex.getMessage();
        }
    }

    public void totaldsD() {
        try {
            DefaultTableModel table = new DefaultTableModel();
            table.addColumn("التاريخ");
            table.addColumn("اسم الطبيب");
            table.addColumn("الحساب قبل الخصم");
            table.addColumn("الخصم");
            table.addColumn("الحساب بعد الخصم");

            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            String datF = f.format(datefromtD.getDate());
            String datT = f.format(datetotD.getDate());
            Connection con = DB.ConectionDB.setconn();
            Statement st = con.createStatement();
            String strE = "SELECT * FROM accounttotald WHERE date_acc BETWEEN '" + datF + "' AND '" + datT + "' AND ";
            if (Doname.isVisible()) {
                strE += " dname like '%" + Doname.getSelectedItem() + "%'";
            } else {
                strE += " dname like '%" + Dname.getText() + "%'";
            }
            ResultSet r = st.executeQuery(strE);
            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(6),
                    r.getString(5),
                    r.getString(4),});
                totalDLest.setModel(table);
            }

        } catch (Exception ex) {
            ex.getMessage();
        }
    }
    private void barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mousex, y - mousey);
    }//GEN-LAST:event_barMouseDragged

    private void barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMousePressed
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_barMousePressed

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.dispose();
        }
    }//GEN-LAST:event_xMouseClicked

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
        x1.setEnabled(true);
        x1.setVisible(true);
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
        x1.setEnabled(false);
        x1.setVisible(false);
    }//GEN-LAST:event_xMouseExited

    private void _MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.setState(MainFormE.ICONIFIED);
        }
    }//GEN-LAST:event__MouseClicked

    private void _MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseEntered
        _1.setEnabled(true);
        _1.setVisible(true);
    }//GEN-LAST:event__MouseEntered

    private void _MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseExited
        _1.setEnabled(false);
        _1.setVisible(false);
    }//GEN-LAST:event__MouseExited

    private void employeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            employee2.setEnabled(true);
            employee2.setVisible(true);
            doctor2.setEnabled(false);
            doctor2.setVisible(false);
            Emp.setEnabled(true);
            Emp.setVisible(true);
            Doc.setEnabled(false);
            Doc.setVisible(false);
            DocName.setVisible(false);
            DocName.setEnabled(false);
        }
    }//GEN-LAST:event_employeeMouseClicked

    private void employeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeMouseEntered
        employee1.setEnabled(true);
        employee1.setVisible(true);
    }//GEN-LAST:event_employeeMouseEntered

    private void employeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeMouseExited
        employee1.setEnabled(false);
        employee1.setVisible(false);
    }//GEN-LAST:event_employeeMouseExited

    private void doctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            employee2.setEnabled(false);
            employee2.setVisible(false);
            doctor2.setEnabled(true);
            doctor2.setVisible(true);
            Emp.setEnabled(false);
            Emp.setVisible(false);
            Doc.setEnabled(true);
            Doc.setVisible(true);
            DocName.setVisible(true);
            DocName.setEnabled(true);
        }
    }//GEN-LAST:event_doctorMouseClicked

    private void doctorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorMouseEntered
        doctor1.setEnabled(true);
        doctor1.setVisible(true);
    }//GEN-LAST:event_doctorMouseEntered

    private void doctorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorMouseExited
        doctor1.setEnabled(false);
        doctor1.setVisible(false);
    }//GEN-LAST:event_doctorMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.dispose();
        }
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit1.setEnabled(true);
        exit1.setVisible(true);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit1.setEnabled(false);
        exit1.setVisible(false);
    }//GEN-LAST:event_exitMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DB.GO.icon(this);
        btndetailsE.add(btnday);
        btndetailsE.add(btndays);

        btntotalE.add(btndayt);
        btntotalE.add(btndayst);

        btndetailsD.add(btndayD);
        btndetailsD.add(btndaysD);

        btntotalD.add(btndaytD);
        btntotalD.add(btndaystD);

    }//GEN-LAST:event_formWindowOpened

    private void dEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dEMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            dE2.setEnabled(true);
            dE2.setVisible(true);
            tE2.setEnabled(false);
            tE2.setVisible(false);
            detailsE.setEnabled(true);
            detailsE.setVisible(true);
            totalE.setEnabled(false);
            totalE.setVisible(false);

        }
    }//GEN-LAST:event_dEMouseClicked

    private void dEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dEMouseEntered
        dE1.setEnabled(true);
        dE1.setVisible(true);
    }//GEN-LAST:event_dEMouseEntered

    private void dEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dEMouseExited
        dE1.setEnabled(false);
        dE1.setVisible(false);
    }//GEN-LAST:event_dEMouseExited

    private void tEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tEMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            dE2.setEnabled(false);
            dE2.setVisible(false);
            tE2.setEnabled(true);
            tE2.setVisible(true);
            detailsE.setEnabled(false);
            detailsE.setVisible(false);
            totalE.setEnabled(true);
            totalE.setVisible(true);

        }
    }//GEN-LAST:event_tEMouseClicked

    private void tEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tEMouseEntered
        tE1.setEnabled(true);
        tE1.setVisible(true);
    }//GEN-LAST:event_tEMouseEntered

    private void tEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tEMouseExited
        tE1.setEnabled(false);
        tE1.setVisible(false);
    }//GEN-LAST:event_tEMouseExited

    private void dDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dDMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            dD2.setEnabled(true);
            dD2.setVisible(true);
            tD2.setEnabled(false);
            tD2.setVisible(false);
            detailsD.setEnabled(true);
            detailsD.setVisible(true);
            totalD.setEnabled(false);
            totalD.setVisible(false);

        }
    }//GEN-LAST:event_dDMouseClicked

    private void dDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dDMouseEntered
        dD1.setEnabled(true);
        dD1.setVisible(true);
    }//GEN-LAST:event_dDMouseEntered

    private void dDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dDMouseExited
        dD1.setEnabled(false);
        dD1.setVisible(false);
    }//GEN-LAST:event_dDMouseExited

    private void tDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            dD2.setEnabled(false);
            dD2.setVisible(false);
            tD2.setEnabled(true);
            tD2.setVisible(true);
            detailsD.setEnabled(false);
            detailsD.setVisible(false);
            totalD.setEnabled(true);
            totalD.setVisible(true);

        }
    }//GEN-LAST:event_tDMouseClicked

    private void tDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDMouseEntered
        tD1.setEnabled(true);
        tD1.setVisible(true);
    }//GEN-LAST:event_tDMouseEntered

    private void tDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDMouseExited
        tD1.setEnabled(false);
        tD1.setVisible(false);
    }//GEN-LAST:event_tDMouseExited

    private void btndayItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btndayItemStateChanged
        if (btnday.isSelected()) {
            day.setVisible(true);
            day.setEnabled(true);
            days.setVisible(false);
            days.setEnabled(false);
            datefromE.setCalendar(null);
            datetoE.setCalendar(null);
            DefaultTableModel mod = (DefaultTableModel) detailsELest.getModel();
            mod.setNumRows(0);
        }
    }//GEN-LAST:event_btndayItemStateChanged

    private void btndaysItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btndaysItemStateChanged
        if (btndays.isSelected()) {
            day.setVisible(false);
            day.setEnabled(false);
            days.setVisible(true);
            days.setEnabled(true);
            datedayE.setCalendar(null);
            DefaultTableModel mod = (DefaultTableModel) detailsELest.getModel();
            mod.setNumRows(0);

        }
    }//GEN-LAST:event_btndaysItemStateChanged

    private void btndaytItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btndaytItemStateChanged
        if (btndayt.isSelected()) {
            dayt.setVisible(true);
            dayt.setEnabled(true);
            dayst.setVisible(false);
            dayst.setEnabled(false);
            datefromEt.setCalendar(null);
            datetoEt.setCalendar(null);
            DefaultTableModel mod = (DefaultTableModel) totalELest.getModel();
            mod.setNumRows(0);
        }
    }//GEN-LAST:event_btndaytItemStateChanged

    private void btndaystItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btndaystItemStateChanged
        if (btndayst.isSelected()) {
            dayt.setVisible(false);
            dayt.setEnabled(false);
            dayst.setVisible(true);
            dayst.setEnabled(true);
            datedayEt.setCalendar(null);
            DefaultTableModel mod = (DefaultTableModel) totalELest.getModel();
            mod.setNumRows(0);
        }
    }//GEN-LAST:event_btndaystItemStateChanged

    private void btndayDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btndayDItemStateChanged
        if (btndayD.isSelected()) {
            dayD.setVisible(true);
            dayD.setEnabled(true);
            daysD.setVisible(false);
            daysD.setEnabled(false);
            datefromD.setCalendar(null);
            datetoD.setCalendar(null);
            DefaultTableModel mod = (DefaultTableModel) detailsDLest.getModel();
            mod.setNumRows(0);
        }
    }//GEN-LAST:event_btndayDItemStateChanged

    private void btndaysDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btndaysDItemStateChanged
        if (btndaysD.isSelected()) {
            dayD.setVisible(false);
            dayD.setEnabled(false);
            daysD.setVisible(true);
            daysD.setEnabled(true);
            datedayD.setCalendar(null);
            DefaultTableModel mod = (DefaultTableModel) detailsDLest.getModel();
            mod.setNumRows(0);
        }
    }//GEN-LAST:event_btndaysDItemStateChanged

    private void btndaytDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btndaytDItemStateChanged
        if (btndaytD.isSelected()) {
            daytD.setVisible(true);
            daytD.setEnabled(true);
            daystD.setVisible(false);
            daystD.setEnabled(false);
            datefromtD.setCalendar(null);
            datetotD.setCalendar(null);
            DefaultTableModel mod = (DefaultTableModel) totalDLest.getModel();
            mod.setNumRows(0);
        }
    }//GEN-LAST:event_btndaytDItemStateChanged

    private void btndaystDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btndaystDItemStateChanged
        if (btndaystD.isSelected()) {
            daytD.setVisible(false);
            daytD.setEnabled(false);
            daystD.setVisible(true);
            daystD.setEnabled(true);
            datedaytD.setCalendar(null);
            DefaultTableModel mod = (DefaultTableModel) totalDLest.getModel();
            mod.setNumRows(0);
        }
    }//GEN-LAST:event_btndaystDItemStateChanged

    private void serchdEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdEMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            serchdE2.setVisible(true);
            serchdE2.setEnabled(true);
            detailsdE();
            serchdE2.setVisible(false);
            serchdE2.setEnabled(false);
        }


    }//GEN-LAST:event_serchdEMouseClicked

    private void serchdEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdEMouseEntered
        serchdE1.setVisible(true);
        serchdE1.setEnabled(true);
    }//GEN-LAST:event_serchdEMouseEntered

    private void serchdEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdEMouseExited
        serchdE1.setVisible(false);
        serchdE1.setEnabled(false);
    }//GEN-LAST:event_serchdEMouseExited

    private void serchdsEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdsEMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            serchdsE2.setVisible(true);
            serchdsE2.setEnabled(true);
            detailsdsE();
            serchdsE2.setVisible(false);
            serchdsE2.setEnabled(false);
        }
    }//GEN-LAST:event_serchdsEMouseClicked

    private void serchdsEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdsEMouseEntered
        serchdsE1.setVisible(true);
        serchdsE1.setEnabled(true);
    }//GEN-LAST:event_serchdsEMouseEntered

    private void serchdsEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdsEMouseExited
        serchdsE1.setVisible(false);
        serchdsE1.setEnabled(false);
    }//GEN-LAST:event_serchdsEMouseExited

    private void serchdEtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdEtMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            serchdEt2.setVisible(true);
            serchdEt2.setEnabled(true);
            totaldE();
            serchdEt2.setVisible(false);
            serchdEt2.setEnabled(false);
        }
    }//GEN-LAST:event_serchdEtMouseClicked

    private void serchdEtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdEtMouseEntered
        serchdEt1.setVisible(true);
        serchdEt1.setEnabled(true);
    }//GEN-LAST:event_serchdEtMouseEntered

    private void serchdEtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdEtMouseExited
        serchdEt1.setVisible(false);
        serchdEt1.setEnabled(false);
    }//GEN-LAST:event_serchdEtMouseExited

    private void serchdsEtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdsEtMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            serchdsEt2.setVisible(true);
            serchdsEt2.setEnabled(true);
            totaldsE();
            serchdsEt2.setVisible(false);
            serchdsEt2.setEnabled(false);
        }
    }//GEN-LAST:event_serchdsEtMouseClicked

    private void serchdsEtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdsEtMouseEntered
        serchdsEt1.setVisible(true);
        serchdsEt1.setEnabled(true);
    }//GEN-LAST:event_serchdsEtMouseEntered

    private void serchdsEtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdsEtMouseExited
        serchdsEt1.setVisible(false);
        serchdsEt1.setEnabled(false);
    }//GEN-LAST:event_serchdsEtMouseExited

    private void serchdEMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdEMouseReleased

    }//GEN-LAST:event_serchdEMouseReleased

    private void serchdstDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdstDMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            totaldsD();
        }
    }//GEN-LAST:event_serchdstDMouseClicked

    private void serchdstDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdstDMouseEntered
        serchdstD1.setVisible(true);
        serchdstD1.setEnabled(true);
    }//GEN-LAST:event_serchdstDMouseEntered

    private void serchdstDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdstDMouseExited
        serchdstD1.setVisible(false);
        serchdstD1.setEnabled(false);
    }//GEN-LAST:event_serchdstDMouseExited

    private void serchdtDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdtDMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {            
            totaldD();            
        }
    }//GEN-LAST:event_serchdtDMouseClicked

    private void serchdtDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdtDMouseEntered
        serchdtD1.setVisible(true);
        serchdtD1.setEnabled(true);
    }//GEN-LAST:event_serchdtDMouseEntered

    private void serchdtDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdtDMouseExited
        serchdtD1.setVisible(false);
        serchdtD1.setEnabled(false);
    }//GEN-LAST:event_serchdtDMouseExited

    private void serchdDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdDMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            serchdD2.setVisible(true);
            serchdD2.setEnabled(true);
            detailsdD();
            serchdD2.setVisible(false);
            serchdD2.setEnabled(false);
        }
    }//GEN-LAST:event_serchdDMouseClicked

    private void serchdDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdDMouseEntered
        serchdD2.setVisible(true);
        serchdD2.setEnabled(true);
    }//GEN-LAST:event_serchdDMouseEntered

    private void serchdDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdDMouseExited
        serchdD2.setVisible(false);
        serchdD2.setEnabled(false);
    }//GEN-LAST:event_serchdDMouseExited

    private void serchdsDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdsDMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            serchdsD2.setVisible(true);
            serchdsD2.setEnabled(true);
            detailsdsD();
            serchdsD2.setVisible(false);
            serchdsD2.setEnabled(false);
        }
    }//GEN-LAST:event_serchdsDMouseClicked

    private void serchdsDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdsDMouseEntered
        serchdsD2.setVisible(true);
        serchdsD2.setEnabled(true);
    }//GEN-LAST:event_serchdsDMouseEntered

    private void serchdsDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchdsDMouseExited
        serchdsD2.setVisible(false);
        serchdsD2.setEnabled(false);
    }//GEN-LAST:event_serchdsDMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(acc_lest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(acc_lest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(acc_lest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(acc_lest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new acc_lest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JLabel Dname = new javax.swing.JLabel();
    private javax.swing.JPanel Doc;
    private javax.swing.JPanel DocName;
    public static final javax.swing.JComboBox<String> Doname = new javax.swing.JComboBox<>();
    private javax.swing.JPanel Emp;
    private javax.swing.JLabel _;
    private javax.swing.JLabel _1;
    private javax.swing.JLabel bar;
    private javax.swing.JRadioButton btnday;
    private javax.swing.JRadioButton btndayD;
    private javax.swing.JRadioButton btndays;
    private javax.swing.JRadioButton btndaysD;
    private javax.swing.JRadioButton btndayst;
    private javax.swing.JRadioButton btndaystD;
    private javax.swing.JRadioButton btndayt;
    private javax.swing.JRadioButton btndaytD;
    private javax.swing.ButtonGroup btndetailsD;
    private javax.swing.ButtonGroup btndetailsE;
    private javax.swing.ButtonGroup btntotalD;
    private javax.swing.ButtonGroup btntotalE;
    private javax.swing.JLabel dD;
    private javax.swing.JLabel dD1;
    private javax.swing.JLabel dD2;
    private javax.swing.JLabel dE;
    private javax.swing.JLabel dE1;
    private javax.swing.JLabel dE2;
    private com.toedter.calendar.JDateChooser datedayD;
    private com.toedter.calendar.JDateChooser datedayE;
    private com.toedter.calendar.JDateChooser datedayEt;
    private com.toedter.calendar.JDateChooser datedaytD;
    private com.toedter.calendar.JDateChooser datefromD;
    private com.toedter.calendar.JDateChooser datefromE;
    private com.toedter.calendar.JDateChooser datefromEt;
    private com.toedter.calendar.JDateChooser datefromtD;
    private com.toedter.calendar.JDateChooser datetoD;
    private com.toedter.calendar.JDateChooser datetoE;
    private com.toedter.calendar.JDateChooser datetoEt;
    private com.toedter.calendar.JDateChooser datetotD;
    private javax.swing.JPanel day;
    private javax.swing.JPanel dayD;
    private javax.swing.JPanel days;
    private javax.swing.JPanel daysD;
    private javax.swing.JPanel dayst;
    private javax.swing.JPanel daystD;
    private javax.swing.JPanel dayt;
    private javax.swing.JPanel daytD;
    private javax.swing.JPanel detailsD;
    private javax.swing.JTable detailsDLest;
    private javax.swing.JPanel detailsE;
    private javax.swing.JTable detailsELest;
    private javax.swing.JLabel doctor;
    private javax.swing.JLabel doctor1;
    private javax.swing.JLabel doctor2;
    private javax.swing.JLabel employee;
    private javax.swing.JLabel employee1;
    private javax.swing.JLabel employee2;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel main;
    private javax.swing.JLabel serchdD;
    private javax.swing.JLabel serchdD1;
    private javax.swing.JLabel serchdD2;
    private javax.swing.JLabel serchdE;
    private javax.swing.JLabel serchdE1;
    private javax.swing.JLabel serchdE2;
    private javax.swing.JLabel serchdEt;
    private javax.swing.JLabel serchdEt1;
    private javax.swing.JLabel serchdEt2;
    private javax.swing.JLabel serchdsD;
    private javax.swing.JLabel serchdsD1;
    private javax.swing.JLabel serchdsD2;
    private javax.swing.JLabel serchdsE;
    private javax.swing.JLabel serchdsE1;
    private javax.swing.JLabel serchdsE2;
    private javax.swing.JLabel serchdsEt;
    private javax.swing.JLabel serchdsEt1;
    private javax.swing.JLabel serchdsEt2;
    private javax.swing.JLabel serchdstD;
    private javax.swing.JLabel serchdstD1;
    private javax.swing.JLabel serchdtD;
    private javax.swing.JLabel serchdtD1;
    private javax.swing.JLabel tD;
    private javax.swing.JLabel tD1;
    private javax.swing.JLabel tD2;
    private javax.swing.JLabel tE;
    private javax.swing.JLabel tE1;
    private javax.swing.JLabel tE2;
    private javax.swing.JPanel totalD;
    private javax.swing.JTable totalDLest;
    private javax.swing.JPanel totalE;
    private javax.swing.JTable totalELest;
    private javax.swing.JLabel x;
    private javax.swing.JLabel x1;
    // End of variables declaration//GEN-END:variables
}
