/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Color;
import java.awt.event.InputEvent;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahmed Kassem
 */
public class Doctors extends javax.swing.JFrame {

    int mousex;
    int mousey;

    /**
     * Creates new form Doctors
     */
    public Doctors() {
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        ShowD.setEnabled(false);
        ShowD.setVisible(false);
        Add1.setEnabled(false);
        Add1.setVisible(false);
        Show3.setEnabled(false);
        Show3.setVisible(false);
        Show2.setEnabled(false);
        Show2.setVisible(false);
        Home1.setEnabled(false);
        Home1.setVisible(false);
        x1.setEnabled(false);
        x1.setVisible(false);
        _1.setEnabled(false);
        _1.setVisible(false);
        Back1.setEnabled(false);
        Back1.setVisible(false);
        Update1.setEnabled(false);
        Update1.setVisible(false);
        Delete1.setEnabled(false);
        Delete1.setVisible(false);
        Times1.setEnabled(false);
        Times1.setVisible(false);
        Lest.getTableHeader().setReorderingAllowed(false);
        Lest.getTableHeader().setBackground(new Color(102, 102, 102));
        Lest.getTableHeader().setForeground(Color.BLACK);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        x = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        _ = new javax.swing.JLabel();
        _1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Home1 = new javax.swing.JLabel();
        Show1 = new javax.swing.JLabel();
        Show2 = new javax.swing.JLabel();
        Show3 = new javax.swing.JLabel();
        NewD = new javax.swing.JPanel();
        Times = new javax.swing.JLabel();
        Times1 = new javax.swing.JLabel();
        Add = new javax.swing.JLabel();
        Add1 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        FName = new javax.swing.JTextField();
        LName = new javax.swing.JTextField();
        Salary = new javax.swing.JTextField();
        Special = new javax.swing.JTextField();
        Main2 = new javax.swing.JLabel();
        ShowD = new javax.swing.JPanel();
        Back = new javax.swing.JLabel();
        Back1 = new javax.swing.JLabel();
        Update = new javax.swing.JLabel();
        Update1 = new javax.swing.JLabel();
        Delete = new javax.swing.JLabel();
        Delete1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lest = new javax.swing.JTable();
        Main1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });
        getContentPane().add(x);
        x.setBounds(921, 1, 17, 18);

        x1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/13.png"))); // NOI18N
        x1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(x1);
        x1.setBounds(917, -1, 24, 22);

        _.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _MouseExited(evt);
            }
        });
        getContentPane().add(_);
        _.setBounds(903, 1, 16, 18);

        _1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/15.png"))); // NOI18N
        getContentPane().add(_1);
        _1.setBounds(896, -1, 22, 22);

        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 20);

        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });
        getContentPane().add(Home);
        Home.setBounds(52, 409, 195, 33);

        Home1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home.png"))); // NOI18N
        getContentPane().add(Home1);
        Home1.setBounds(52, 409, 195, 33);

        Show1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Show1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Show1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Show1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Show1MouseExited(evt);
            }
        });
        getContentPane().add(Show1);
        Show1.setBounds(52, 201, 195, 33);

        Show2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Show Doc.png"))); // NOI18N
        getContentPane().add(Show2);
        Show2.setBounds(52, 201, 195, 33);

        Show3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Show Doc.png"))); // NOI18N
        getContentPane().add(Show3);
        Show3.setBounds(52, 201, 195, 33);

        NewD.setLayout(null);

        Times.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Times.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TimesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TimesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TimesMouseExited(evt);
            }
        });
        NewD.add(Times);
        Times.setBounds(650, 405, 226, 33);

        Times1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Times.png"))); // NOI18N
        NewD.add(Times1);
        Times1.setBounds(650, 405, 226, 33);

        Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddMouseExited(evt);
            }
        });
        NewD.add(Add);
        Add.setBounds(52, 132, 195, 33);

        Add1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add.png"))); // NOI18N
        NewD.add(Add1);
        Add1.setBounds(52, 132, 195, 33);

        ID.setEditable(false);
        ID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ID.setBorder(null);
        ID.setOpaque(false);
        NewD.add(ID);
        ID.setBounds(545, 121, 150, 29);

        FName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        FName.setForeground(new java.awt.Color(51, 51, 51));
        FName.setBorder(null);
        FName.setOpaque(false);
        NewD.add(FName);
        FName.setBounds(485, 181, 210, 30);

        LName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LName.setForeground(new java.awt.Color(51, 51, 51));
        LName.setBorder(null);
        LName.setOpaque(false);
        NewD.add(LName);
        LName.setBounds(485, 235, 210, 30);

        Salary.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Salary.setForeground(new java.awt.Color(51, 51, 51));
        Salary.setBorder(null);
        Salary.setOpaque(false);
        NewD.add(Salary);
        Salary.setBounds(545, 340, 150, 30);

        Special.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Special.setForeground(new java.awt.Color(51, 51, 51));
        Special.setBorder(null);
        Special.setOpaque(false);
        NewD.add(Special);
        Special.setBounds(485, 286, 210, 30);

        Main2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Doc.jpg"))); // NOI18N
        NewD.add(Main2);
        Main2.setBounds(0, 0, 940, 506);

        getContentPane().add(NewD);
        NewD.setBounds(0, 0, 940, 506);

        ShowD.setLayout(null);

        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
        });
        ShowD.add(Back);
        Back.setBounds(52, 132, 195, 33);

        Back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        ShowD.add(Back1);
        Back1.setBounds(52, 132, 195, 33);

        Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateMouseExited(evt);
            }
        });
        ShowD.add(Update);
        Update.setBounds(52, 270, 195, 33);

        Update1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Update.png"))); // NOI18N
        ShowD.add(Update1);
        Update1.setBounds(52, 270, 195, 33);

        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteMouseExited(evt);
            }
        });
        ShowD.add(Delete);
        Delete.setBounds(50, 340, 195, 33);

        Delete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete.png"))); // NOI18N
        ShowD.add(Delete1);
        Delete1.setBounds(50, 340, 195, 33);

        jScrollPane1.setBorder(null);
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jScrollPane1.setOpaque(false);

        Lest.setBackground(new java.awt.Color(184, 197, 251));
        Lest.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Lest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "رقم التسلسل", "الاسم", "التخصص", "سعر الكشف"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Lest.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Lest.setGridColor(new java.awt.Color(51, 51, 51));
        Lest.setOpaque(false);
        Lest.setRequestFocusEnabled(false);
        Lest.setSelectionBackground(new java.awt.Color(102, 102, 102));
        Lest.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(Lest);

        ShowD.add(jScrollPane1);
        jScrollPane1.setBounds(310, 120, 600, 350);

        Main1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DocShow.png"))); // NOI18N
        ShowD.add(Main1);
        Main1.setBounds(0, 0, 940, 506);

        getContentPane().add(ShowD);
        ShowD.setBounds(0, 0, 940, 506);

        setBounds(0, 0, 940, 506);
    }// </editor-fold>//GEN-END:initComponents

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        int a = JOptionPane.showConfirmDialog(this, "هل تريد الخروج ؟", "Exit", JOptionPane.WARNING_MESSAGE);

        if (a == JOptionPane.YES_OPTION) {
            this.dispose();
        } else {

        }
    }//GEN-LAST:event_xMouseClicked

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
        x1.setEnabled(true);
        x1.setVisible(true);
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
        x1.setEnabled(false);
        x1.setVisible(false);
    }//GEN-LAST:event_xMouseExited

    private void _MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseClicked
        this.setState(MainFormE.ICONIFIED);
    }//GEN-LAST:event__MouseClicked

    private void _MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseEntered
        _1.setEnabled(true);
        _1.setVisible(true);
    }//GEN-LAST:event__MouseEntered

    private void _MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseExited
        _1.setEnabled(false);
        _1.setVisible(false);
    }//GEN-LAST:event__MouseExited

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mousex, y - mousey);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked

        this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        Home1.setEnabled(true);
        Home1.setVisible(true);
    }//GEN-LAST:event_HomeMouseEntered

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        Home1.setEnabled(false);
        Home1.setVisible(false);
    }//GEN-LAST:event_HomeMouseExited
    public void Listed() {
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("رقم المسلسل");
        table.addColumn("الاسم");
        table.addColumn("التخصص");
        table.addColumn("سعر الكشف");

        try {
            Connection con = DB.ConectionDB.setconn();
            String strs = "SELECT * FROM DOCTORS";
            Statement st = con.createStatement();
            ResultSet r = st.executeQuery(strs);

            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),});
                Lest.setModel(table);
            }

        } catch (Exception ex) {

        }
    }
    private void Show1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Show1MouseClicked
        ShowD.setEnabled(true);
        ShowD.setVisible(true);
        NewD.setEnabled(false);
        NewD.setVisible(false);
        Show3.setEnabled(true);
        Show3.setVisible(true);
        Listed();
    }//GEN-LAST:event_Show1MouseClicked

    private void Show1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Show1MouseEntered
        Show2.setEnabled(true);
        Show2.setVisible(true);
    }//GEN-LAST:event_Show1MouseEntered

    private void Show1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Show1MouseExited
        Show2.setEnabled(false);
        Show2.setVisible(false);
    }//GEN-LAST:event_Show1MouseExited
    public void clearData() {
        Controls.Tools.clearText(this);
        FName.requestFocus();
        ID.setText(DB.GO.autoNumber("Doctors", "Number"));
    }
    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
        if ("".equals(ID.getText()) || "".equals(FName.getText()) || "".equals(LName.getText()) || "".equals(Special.getText()) || "".equals(Salary.getText())) {
            JOptionPane.showMessageDialog(this, "رجاء ادخال جميع البيانات ", "خطأ", JOptionPane.ERROR_MESSAGE);
        } else {
            String stra = "INSERT INTO DOCTORS VALUES (" + ID.getText() + ", 'DR: " + FName.getText() + " " + LName.getText() + "', '" + Special.getText() + "', '" + Salary.getText() + "')";
            boolean ifa = DB.GO.runNunQuery(stra);
            if (ifa) {
                JOptionPane.showMessageDialog(this, "تم تسجيل البيانات", "نجح", JOptionPane.WARNING_MESSAGE);
                clearData();
            } else {
                JOptionPane.showMessageDialog(this, "لم يتم تسجيل البيانات", "خطأ", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_AddMouseClicked

    private void AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseEntered
        Add1.setEnabled(true);
        Add1.setVisible(true);
    }//GEN-LAST:event_AddMouseEntered

    private void AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseExited
        Add1.setEnabled(false);
        Add1.setVisible(false);
    }//GEN-LAST:event_AddMouseExited

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        ShowD.setEnabled(false);
        ShowD.setVisible(false);
        NewD.setEnabled(true);
        NewD.setVisible(true);
        Show3.setEnabled(false);
        Show3.setVisible(false);
    }//GEN-LAST:event_BackMouseClicked

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
        Back1.setEnabled(true);
        Back1.setVisible(true);
    }//GEN-LAST:event_BackMouseEntered

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
        Back1.setEnabled(false);
        Back1.setVisible(false);
    }//GEN-LAST:event_BackMouseExited

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        int row = Lest.getSelectedRow();
        String id = Lest.getValueAt(row, 0).toString();
        String name = Lest.getValueAt(row, 1).toString();
        String Sp = Lest.getValueAt(row, 2).toString();
        String Salr = Lest.getValueAt(row, 3).toString();

        String stru = "UPDATE DOCTORS SET NAME='" + name + "', Specialization='" + Sp + "', SALARY='" + Salr + "'WHERE NUMBER=" + id;
        boolean ifu = DB.GO.runNunQuery(stru);
        if (ifu) {
            JOptionPane.showMessageDialog(this, "تم تعديل البيانات", "نجح", JOptionPane.WARNING_MESSAGE);
            Listed();
        } else {
            JOptionPane.showMessageDialog(this, "لم يتم تعديل البيانات", "خطأ", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_UpdateMouseClicked

    private void UpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseEntered
        Update1.setEnabled(true);
        Update1.setVisible(true);
    }//GEN-LAST:event_UpdateMouseEntered

    private void UpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseExited
        Update1.setEnabled(false);
        Update1.setVisible(false);
    }//GEN-LAST:event_UpdateMouseExited

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        int d = JOptionPane.showConfirmDialog(this, "هل تريد حذف المحدد ؟");
        if (d == JOptionPane.YES_OPTION) {
            int row = Lest.getSelectedRow();
            String id = Lest.getValueAt(row, 0).toString();
            String strd = "DELETE FROM DOCTORS WHERE NUMBER=" + id;
            boolean ifd = DB.GO.runNunQuery(strd);
            if (ifd) {
                JOptionPane.showMessageDialog(this, "تم حذف البيانات", "نجح", JOptionPane.WARNING_MESSAGE);
                Listed();
            } else {
                JOptionPane.showMessageDialog(this, "لم يتم حذف شيئ", "خطأ", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_DeleteMouseClicked

    private void DeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseEntered
        Delete1.setEnabled(true);
        Delete1.setVisible(true);
    }//GEN-LAST:event_DeleteMouseEntered

    private void DeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseExited
        Delete1.setEnabled(false);
        Delete1.setVisible(false);
    }//GEN-LAST:event_DeleteMouseExited

    private void TimesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimesMouseEntered
        Times1.setEnabled(true);
        Times1.setVisible(true);
    }//GEN-LAST:event_TimesMouseEntered

    private void TimesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimesMouseExited
        Times1.setEnabled(false);
        Times1.setVisible(false);
    }//GEN-LAST:event_TimesMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DB.GO.icon(this);
        ID.setText(DB.GO.autoNumber("Doctors", "Number"));
    }//GEN-LAST:event_formWindowOpened

    private void TimesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimesMouseClicked
        Times t = new Times();
        t.setVisible(true);
        t.setDefaultCloseOperation(2);

    }//GEN-LAST:event_TimesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add;
    private javax.swing.JLabel Add1;
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Back1;
    private javax.swing.JLabel Delete;
    private javax.swing.JLabel Delete1;
    private javax.swing.JTextField FName;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Home1;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField LName;
    private javax.swing.JTable Lest;
    private javax.swing.JLabel Main1;
    private javax.swing.JLabel Main2;
    private javax.swing.JPanel NewD;
    private javax.swing.JTextField Salary;
    private javax.swing.JLabel Show1;
    private javax.swing.JLabel Show2;
    private javax.swing.JLabel Show3;
    private javax.swing.JPanel ShowD;
    private javax.swing.JTextField Special;
    private javax.swing.JLabel Times;
    private javax.swing.JLabel Times1;
    private javax.swing.JLabel Update;
    private javax.swing.JLabel Update1;
    private javax.swing.JLabel _;
    private javax.swing.JLabel _1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel x;
    private javax.swing.JLabel x1;
    // End of variables declaration//GEN-END:variables
}
