/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahmed Kassem
 */
public class Doctors_Date extends javax.swing.JFrame {

    int mousex;
    int mousey;

    /**
     * Creates new form Doctors_Date
     */
    public Doctors_Date() {
        initComponents();
        _1.setEnabled(false);
        _1.setVisible(false);
        x1.setEnabled(false);
        x1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _ = new javax.swing.JLabel();
        _1 = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        bar = new javax.swing.JLabel();
        Times = new javax.swing.JPanel();
        doctname = new javax.swing.JComboBox<>();
        SSfrom = new javax.swing.JTextField();
        SSto = new javax.swing.JTextField();
        SSUfrom = new javax.swing.JTextField();
        SSUto = new javax.swing.JTextField();
        MMfrom = new javax.swing.JTextField();
        MMto = new javax.swing.JTextField();
        TTfrom = new javax.swing.JTextField();
        TTto = new javax.swing.JTextField();
        WWto = new javax.swing.JTextField();
        WWfrom = new javax.swing.JTextField();
        TTHfrom = new javax.swing.JTextField();
        TTHto = new javax.swing.JTextField();
        FFto = new javax.swing.JTextField();
        FFfrom = new javax.swing.JTextField();
        Sfrom = new javax.swing.JTextField();
        Sto = new javax.swing.JTextField();
        SUfrom = new javax.swing.JTextField();
        SUto = new javax.swing.JTextField();
        Mfrom = new javax.swing.JTextField();
        Mto = new javax.swing.JTextField();
        Tfrom = new javax.swing.JTextField();
        Tto = new javax.swing.JTextField();
        Wfrom = new javax.swing.JTextField();
        Wto = new javax.swing.JTextField();
        THfrom = new javax.swing.JTextField();
        THto = new javax.swing.JTextField();
        Ffrom = new javax.swing.JTextField();
        Fto = new javax.swing.JTextField();
        MMfrom1 = new javax.swing.JLabel();
        MMto1 = new javax.swing.JLabel();
        Mfrom1 = new javax.swing.JLabel();
        Mto1 = new javax.swing.JLabel();
        SSUfrom1 = new javax.swing.JLabel();
        Sfrom1 = new javax.swing.JLabel();
        SUfrom1 = new javax.swing.JLabel();
        SSfrom1 = new javax.swing.JLabel();
        SUto1 = new javax.swing.JLabel();
        SSUto1 = new javax.swing.JLabel();
        Sto1 = new javax.swing.JLabel();
        SSto1 = new javax.swing.JLabel();
        TTfrom1 = new javax.swing.JLabel();
        TTto1 = new javax.swing.JLabel();
        Tfrom1 = new javax.swing.JLabel();
        Tto1 = new javax.swing.JLabel();
        WWfrom1 = new javax.swing.JLabel();
        WWto1 = new javax.swing.JLabel();
        Wfrom1 = new javax.swing.JLabel();
        Wto1 = new javax.swing.JLabel();
        TTHfrom1 = new javax.swing.JLabel();
        TTHto1 = new javax.swing.JLabel();
        THfrom1 = new javax.swing.JLabel();
        THto1 = new javax.swing.JLabel();
        FFfrom1 = new javax.swing.JLabel();
        FFto1 = new javax.swing.JLabel();
        Ffrom1 = new javax.swing.JLabel();
        Fto1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        _.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _MouseExited(evt);
            }
        });
        getContentPane().add(_);
        _.setBounds(624, 0, 19, 20);

        _1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/15_.png"))); // NOI18N
        getContentPane().add(_1);
        _1.setBounds(624, 0, 19, 20);

        x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });
        getContentPane().add(x);
        x.setBounds(642, -2, 22, 22);

        x1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/13X.png"))); // NOI18N
        x1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(x1);
        x1.setBounds(642, -2, 22, 22);

        bar.setBackground(new java.awt.Color(0, 0, 102));
        bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DateTime.png"))); // NOI18N
        bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barMouseDragged(evt);
            }
        });
        bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barMousePressed(evt);
            }
        });
        getContentPane().add(bar);
        bar.setBounds(0, 0, 663, 20);

        Times.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doctname.setBackground(new java.awt.Color(56, 148, 233));
        doctname.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        doctname.setForeground(new java.awt.Color(16, 24, 32));
        doctname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        doctname.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        doctname.setOpaque(false);
        doctname.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                doctnameItemStateChanged(evt);
            }
        });
        Times.add(doctname, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 22, 161, 30));

        SSfrom.setEditable(false);
        SSfrom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SSfrom.setForeground(new java.awt.Color(16, 24, 32));
        SSfrom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SSfrom.setBorder(null);
        SSfrom.setOpaque(false);
        Times.add(SSfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 138, 90, 29));

        SSto.setEditable(false);
        SSto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SSto.setForeground(new java.awt.Color(16, 24, 32));
        SSto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SSto.setBorder(null);
        SSto.setOpaque(false);
        Times.add(SSto, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 138, 90, 29));

        SSUfrom.setEditable(false);
        SSUfrom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SSUfrom.setForeground(new java.awt.Color(16, 24, 32));
        SSUfrom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SSUfrom.setBorder(null);
        SSUfrom.setOpaque(false);
        Times.add(SSUfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 186, 90, 29));

        SSUto.setEditable(false);
        SSUto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SSUto.setForeground(new java.awt.Color(16, 24, 32));
        SSUto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SSUto.setBorder(null);
        SSUto.setOpaque(false);
        Times.add(SSUto, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 186, 90, 29));

        MMfrom.setEditable(false);
        MMfrom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        MMfrom.setForeground(new java.awt.Color(16, 24, 32));
        MMfrom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MMfrom.setBorder(null);
        MMfrom.setOpaque(false);
        Times.add(MMfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 235, 90, 29));

        MMto.setEditable(false);
        MMto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        MMto.setForeground(new java.awt.Color(16, 24, 32));
        MMto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MMto.setBorder(null);
        MMto.setOpaque(false);
        Times.add(MMto, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 235, 90, 29));

        TTfrom.setEditable(false);
        TTfrom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TTfrom.setForeground(new java.awt.Color(16, 24, 32));
        TTfrom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TTfrom.setBorder(null);
        TTfrom.setOpaque(false);
        Times.add(TTfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 283, 90, 29));

        TTto.setEditable(false);
        TTto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TTto.setForeground(new java.awt.Color(16, 24, 32));
        TTto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TTto.setBorder(null);
        TTto.setOpaque(false);
        Times.add(TTto, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 283, 90, 29));

        WWto.setEditable(false);
        WWto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        WWto.setForeground(new java.awt.Color(16, 24, 32));
        WWto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WWto.setBorder(null);
        WWto.setOpaque(false);
        Times.add(WWto, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 331, 90, 29));

        WWfrom.setEditable(false);
        WWfrom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        WWfrom.setForeground(new java.awt.Color(16, 24, 32));
        WWfrom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WWfrom.setBorder(null);
        WWfrom.setOpaque(false);
        Times.add(WWfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 331, 90, 29));

        TTHfrom.setEditable(false);
        TTHfrom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TTHfrom.setForeground(new java.awt.Color(16, 24, 32));
        TTHfrom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TTHfrom.setBorder(null);
        TTHfrom.setOpaque(false);
        Times.add(TTHfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 379, 90, 29));

        TTHto.setEditable(false);
        TTHto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TTHto.setForeground(new java.awt.Color(16, 24, 32));
        TTHto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TTHto.setBorder(null);
        TTHto.setOpaque(false);
        Times.add(TTHto, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 379, 90, 29));

        FFto.setEditable(false);
        FFto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        FFto.setForeground(new java.awt.Color(16, 24, 32));
        FFto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FFto.setBorder(null);
        FFto.setOpaque(false);
        Times.add(FFto, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 427, 90, 29));

        FFfrom.setEditable(false);
        FFfrom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        FFfrom.setForeground(new java.awt.Color(16, 24, 32));
        FFfrom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FFfrom.setBorder(null);
        FFfrom.setOpaque(false);
        Times.add(FFfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 427, 90, 29));

        Sfrom.setEditable(false);
        Sfrom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Sfrom.setForeground(new java.awt.Color(16, 24, 32));
        Sfrom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sfrom.setBorder(null);
        Sfrom.setOpaque(false);
        Times.add(Sfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 140, 90, 29));

        Sto.setEditable(false);
        Sto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Sto.setForeground(new java.awt.Color(16, 24, 32));
        Sto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sto.setBorder(null);
        Sto.setOpaque(false);
        Times.add(Sto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 90, 29));

        SUfrom.setEditable(false);
        SUfrom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SUfrom.setForeground(new java.awt.Color(16, 24, 32));
        SUfrom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SUfrom.setBorder(null);
        SUfrom.setOpaque(false);
        Times.add(SUfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 188, 90, 29));

        SUto.setEditable(false);
        SUto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SUto.setForeground(new java.awt.Color(16, 24, 32));
        SUto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SUto.setBorder(null);
        SUto.setOpaque(false);
        Times.add(SUto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 188, 90, 29));

        Mfrom.setEditable(false);
        Mfrom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Mfrom.setForeground(new java.awt.Color(16, 24, 32));
        Mfrom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Mfrom.setBorder(null);
        Mfrom.setOpaque(false);
        Times.add(Mfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 237, 90, 29));

        Mto.setEditable(false);
        Mto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Mto.setForeground(new java.awt.Color(16, 24, 32));
        Mto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Mto.setBorder(null);
        Mto.setOpaque(false);
        Times.add(Mto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 237, 90, 29));

        Tfrom.setEditable(false);
        Tfrom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Tfrom.setForeground(new java.awt.Color(16, 24, 32));
        Tfrom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tfrom.setBorder(null);
        Tfrom.setOpaque(false);
        Times.add(Tfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 285, 90, 29));

        Tto.setEditable(false);
        Tto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Tto.setForeground(new java.awt.Color(16, 24, 32));
        Tto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tto.setBorder(null);
        Tto.setOpaque(false);
        Times.add(Tto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 285, 90, 29));

        Wfrom.setEditable(false);
        Wfrom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Wfrom.setForeground(new java.awt.Color(16, 24, 32));
        Wfrom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Wfrom.setBorder(null);
        Wfrom.setOpaque(false);
        Times.add(Wfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 333, 90, 29));

        Wto.setEditable(false);
        Wto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Wto.setForeground(new java.awt.Color(16, 24, 32));
        Wto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Wto.setBorder(null);
        Wto.setOpaque(false);
        Times.add(Wto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 333, 90, 29));

        THfrom.setEditable(false);
        THfrom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        THfrom.setForeground(new java.awt.Color(16, 24, 32));
        THfrom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        THfrom.setBorder(null);
        THfrom.setOpaque(false);
        Times.add(THfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 381, 90, 29));

        THto.setEditable(false);
        THto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        THto.setForeground(new java.awt.Color(16, 24, 32));
        THto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        THto.setBorder(null);
        THto.setOpaque(false);
        Times.add(THto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 381, 90, 29));

        Ffrom.setEditable(false);
        Ffrom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Ffrom.setForeground(new java.awt.Color(16, 24, 32));
        Ffrom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ffrom.setBorder(null);
        Ffrom.setOpaque(false);
        Times.add(Ffrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 429, 90, 29));

        Fto.setEditable(false);
        Fto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Fto.setForeground(new java.awt.Color(16, 24, 32));
        Fto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Fto.setBorder(null);
        Fto.setOpaque(false);
        Times.add(Fto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 429, 90, 29));

        MMfrom1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        MMfrom1.setForeground(new java.awt.Color(102, 102, 102));
        MMfrom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MMfrom1.setText("لا يوجد مواعيد");
        Times.add(MMfrom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 235, 90, 29));

        MMto1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        MMto1.setForeground(new java.awt.Color(102, 102, 102));
        MMto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MMto1.setText("لا يوجد مواعيد");
        Times.add(MMto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 235, 90, 29));

        Mfrom1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Mfrom1.setForeground(new java.awt.Color(102, 102, 102));
        Mfrom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mfrom1.setText("لا يوجد مواعيد");
        Times.add(Mfrom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 237, 90, 29));

        Mto1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Mto1.setForeground(new java.awt.Color(102, 102, 102));
        Mto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mto1.setText("لا يوجد مواعيد");
        Times.add(Mto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 237, 90, 29));

        SSUfrom1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SSUfrom1.setForeground(new java.awt.Color(102, 102, 102));
        SSUfrom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SSUfrom1.setText("لا يوجد مواعيد");
        Times.add(SSUfrom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 186, 90, 29));

        Sfrom1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Sfrom1.setForeground(new java.awt.Color(102, 102, 102));
        Sfrom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sfrom1.setText("لا يوجد مواعيد");
        Times.add(Sfrom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 140, 90, 29));

        SUfrom1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SUfrom1.setForeground(new java.awt.Color(102, 102, 102));
        SUfrom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SUfrom1.setText("لا يوجد مواعيد");
        Times.add(SUfrom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 188, 90, 29));

        SSfrom1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SSfrom1.setForeground(new java.awt.Color(102, 102, 102));
        SSfrom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SSfrom1.setText("لا يوجد مواعيد");
        Times.add(SSfrom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 138, 90, 29));

        SUto1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SUto1.setForeground(new java.awt.Color(102, 102, 102));
        SUto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SUto1.setText("لا يوجد مواعيد");
        Times.add(SUto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 188, 90, 29));

        SSUto1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SSUto1.setForeground(new java.awt.Color(102, 102, 102));
        SSUto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SSUto1.setText("لا يوجد مواعيد");
        Times.add(SSUto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 186, 90, 29));

        Sto1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Sto1.setForeground(new java.awt.Color(102, 102, 102));
        Sto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sto1.setText("لا يوجد مواعيد");
        Times.add(Sto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 90, 29));

        SSto1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SSto1.setForeground(new java.awt.Color(102, 102, 102));
        SSto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SSto1.setText("لا يوجد مواعيد");
        Times.add(SSto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 138, 90, 29));

        TTfrom1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TTfrom1.setForeground(new java.awt.Color(102, 102, 102));
        TTfrom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TTfrom1.setText("لا يوجد مواعيد");
        Times.add(TTfrom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 283, 90, 29));

        TTto1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TTto1.setForeground(new java.awt.Color(102, 102, 102));
        TTto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TTto1.setText("لا يوجد مواعيد");
        Times.add(TTto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 283, 90, 29));

        Tfrom1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Tfrom1.setForeground(new java.awt.Color(102, 102, 102));
        Tfrom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tfrom1.setText("لا يوجد مواعيد");
        Times.add(Tfrom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 285, 90, 29));

        Tto1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Tto1.setForeground(new java.awt.Color(102, 102, 102));
        Tto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tto1.setText("لا يوجد مواعيد");
        Times.add(Tto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 285, 90, 29));

        WWfrom1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        WWfrom1.setForeground(new java.awt.Color(102, 102, 102));
        WWfrom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WWfrom1.setText("لا يوجد مواعيد");
        Times.add(WWfrom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 331, 90, 29));

        WWto1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        WWto1.setForeground(new java.awt.Color(102, 102, 102));
        WWto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WWto1.setText("لا يوجد مواعيد");
        Times.add(WWto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 331, 90, 29));

        Wfrom1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Wfrom1.setForeground(new java.awt.Color(102, 102, 102));
        Wfrom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Wfrom1.setText("لا يوجد مواعيد");
        Times.add(Wfrom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 333, 90, 29));

        Wto1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Wto1.setForeground(new java.awt.Color(102, 102, 102));
        Wto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Wto1.setText("لا يوجد مواعيد");
        Times.add(Wto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 333, 90, 29));

        TTHfrom1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TTHfrom1.setForeground(new java.awt.Color(102, 102, 102));
        TTHfrom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TTHfrom1.setText("لا يوجد مواعيد");
        Times.add(TTHfrom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 379, 90, 29));

        TTHto1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TTHto1.setForeground(new java.awt.Color(102, 102, 102));
        TTHto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TTHto1.setText("لا يوجد مواعيد");
        Times.add(TTHto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 379, 90, 29));

        THfrom1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        THfrom1.setForeground(new java.awt.Color(102, 102, 102));
        THfrom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        THfrom1.setText("لا يوجد مواعيد");
        Times.add(THfrom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 381, 90, 29));

        THto1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        THto1.setForeground(new java.awt.Color(102, 102, 102));
        THto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        THto1.setText("لا يوجد مواعيد");
        Times.add(THto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 381, 90, 29));

        FFfrom1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        FFfrom1.setForeground(new java.awt.Color(102, 102, 102));
        FFfrom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FFfrom1.setText("لا يوجد مواعيد");
        Times.add(FFfrom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 427, 90, 29));

        FFto1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        FFto1.setForeground(new java.awt.Color(102, 102, 102));
        FFto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FFto1.setText("لا يوجد مواعيد");
        Times.add(FFto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 427, 90, 29));

        Ffrom1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Ffrom1.setForeground(new java.awt.Color(102, 102, 102));
        Ffrom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ffrom1.setText("لا يوجد مواعيد");
        Times.add(Ffrom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 429, 90, 29));

        Fto1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Fto1.setForeground(new java.awt.Color(102, 102, 102));
        Fto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fto1.setText("لا يوجد مواعيد");
        Times.add(Fto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 429, 90, 29));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Times Doc.png"))); // NOI18N
        Times.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 663, 483));

        getContentPane().add(Times);
        Times.setBounds(0, 20, 664, 483);

        setBounds(0, 0, 663, 505);
    }// </editor-fold>//GEN-END:initComponents

    private void _MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseClicked
        this.setState(MainFormE.ICONIFIED);
    }//GEN-LAST:event__MouseClicked

    private void _MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseEntered
        _1.setEnabled(true);
        _1.setVisible(true);
    }//GEN-LAST:event__MouseEntered

    private void _MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseExited
        _1.setEnabled(false);
        _1.setVisible(false);
    }//GEN-LAST:event__MouseExited

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        this.dispose();
    }//GEN-LAST:event_xMouseClicked

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
        x1.setEnabled(true);
        x1.setVisible(true);
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
        x1.setEnabled(false);
        x1.setVisible(false);
    }//GEN-LAST:event_xMouseExited

    private void barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mousex, y - mousey);
    }//GEN-LAST:event_barMouseDragged

    private void barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMousePressed
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_barMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DB.GO.icon(this);
        DB.GO.fillCompo("doctors", "name", doctname);
        doctname.setSelectedItem(null);
    }//GEN-LAST:event_formWindowOpened

    private void doctnameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_doctnameItemStateChanged
        Controls.Tools.clearText(this);
        SSfrom1.setVisible(true);
        SSto1.setVisible(true);
        Sfrom1.setVisible(true);
        Sto1.setVisible(true);
        SSUfrom1.setVisible(true);
        SSUto1.setVisible(true);
        SUfrom1.setVisible(true);
        SUto1.setVisible(true);
        MMfrom1.setVisible(true);
        MMto1.setVisible(true);
        Mfrom1.setVisible(true);
        Mto1.setVisible(true);
        TTfrom1.setVisible(true);
        TTto1.setVisible(true);
        Tfrom1.setVisible(true);
        Tto1.setVisible(true);
        WWfrom1.setVisible(true);
        WWto1.setVisible(true);
        Wfrom1.setVisible(true);
        Wto1.setVisible(true);
        TTHfrom1.setVisible(true);
        TTHto1.setVisible(true);
        THfrom1.setVisible(true);
        THto1.setVisible(true);
        FFfrom1.setVisible(true);
        FFto1.setVisible(true);
        Ffrom1.setVisible(true);
        Fto1.setVisible(true);
        try {
            Connection con = DB.ConectionDB.setconn();
            String strs = "SELECT * FROM doc_times_data WHERE Doctors_name like '%" + doctname.getSelectedItem() + "%'";
            Statement st = con.createStatement();
            ResultSet r = st.executeQuery(strs);

            while (r.next()) {

                String num = r.getString(1);
                String nam = r.getString(2);
                String day = r.getString(3);
                String from = r.getString(4);
                String to = r.getString(5);
                String shift = r.getString(6);

                if ("السبت".equals(day) & "1".equals(shift)) {
                    SSfrom1.setVisible(false);
                    SSto1.setVisible(false);
                    SSfrom.setText(from);
                    SSto.setText(to);
                } else if ("السبت".equals(day) & "2".equals(shift)) {
                    Sfrom1.setVisible(false);
                    Sto1.setVisible(false);
                    Sfrom.setText(from);
                    Sto.setText(to);
                } else if ("الاحد".equals(day) & "1".equals(shift)) {
                    SSUfrom1.setVisible(false);
                    SSUto1.setVisible(false);
                    SSUfrom.setText(from);
                    SSUto.setText(to);
                } else if ("الاحد".equals(day) & "2".equals(shift)) {
                    SUfrom1.setVisible(false);
                    SUto1.setVisible(false);
                    SUfrom.setText(from);
                    SUto.setText(to);
                } else if ("الاثنين".equals(day) & "1".equals(shift)) {
                    MMfrom1.setVisible(false);
                    MMto1.setVisible(false);
                    MMfrom.setText(from);
                    MMto.setText(to);
                } else if ("الاثنين".equals(day) & "2".equals(shift)) {
                    Mfrom1.setVisible(false);
                    Mto1.setVisible(false);
                    Mfrom.setText(from);
                    Mto.setText(to);
                } else if ("الثلاثاء".equals(day) & "1".equals(shift)) {
                    TTfrom1.setVisible(false);
                    TTto1.setVisible(false);
                    TTfrom.setText(from);
                    TTto.setText(to);
                } else if ("الثلاثاء".equals(day) & "2".equals(shift)) {
                    Tfrom1.setVisible(false);
                    Tto1.setVisible(false);
                    Tfrom.setText(from);
                    Tto.setText(to);
                } else if ("الاربعاء".equals(day) & "1".equals(shift)) {
                    WWfrom1.setVisible(false);
                    WWto1.setVisible(false);
                    WWfrom.setText(from);
                    WWto.setText(to);
                } else if ("الاربعاء".equals(day) & "2".equals(shift)) {
                    Wfrom1.setVisible(false);
                    Wto1.setVisible(false);
                    Wfrom.setText(from);
                    Wto.setText(to);
                } else if ("الخميس".equals(day) & "1".equals(shift)) {
                    TTHfrom1.setVisible(false);
                    TTHto1.setVisible(false);
                    TTHfrom.setText(from);
                    TTHto.setText(to);
                } else if ("الخميس".equals(day) & "2".equals(shift)) {
                    THfrom1.setVisible(false);
                    THto1.setVisible(false);
                    THfrom.setText(from);
                    THto.setText(to);
                } else if ("الجمعه".equals(day) & "1".equals(shift)) {
                    FFfrom1.setVisible(false);
                    FFto1.setVisible(false);
                    FFfrom.setText(from);
                    FFto.setText(to);
                } else if ("الجمعه".equals(day) & "2".equals(shift)) {
                    Ffrom1.setVisible(false);
                    Fto1.setVisible(false);
                    Ffrom.setText(from);
                    Fto.setText(to);
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_doctnameItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctors_Date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctors_Date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctors_Date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctors_Date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctors_Date().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FFfrom;
    private javax.swing.JLabel FFfrom1;
    private javax.swing.JTextField FFto;
    private javax.swing.JLabel FFto1;
    private javax.swing.JTextField Ffrom;
    private javax.swing.JLabel Ffrom1;
    private javax.swing.JTextField Fto;
    private javax.swing.JLabel Fto1;
    private javax.swing.JTextField MMfrom;
    private javax.swing.JLabel MMfrom1;
    private javax.swing.JTextField MMto;
    private javax.swing.JLabel MMto1;
    private javax.swing.JTextField Mfrom;
    private javax.swing.JLabel Mfrom1;
    private javax.swing.JTextField Mto;
    private javax.swing.JLabel Mto1;
    private javax.swing.JTextField SSUfrom;
    private javax.swing.JLabel SSUfrom1;
    private javax.swing.JTextField SSUto;
    private javax.swing.JLabel SSUto1;
    private javax.swing.JTextField SSfrom;
    private javax.swing.JLabel SSfrom1;
    private javax.swing.JTextField SSto;
    private javax.swing.JLabel SSto1;
    private javax.swing.JTextField SUfrom;
    private javax.swing.JLabel SUfrom1;
    private javax.swing.JTextField SUto;
    private javax.swing.JLabel SUto1;
    private javax.swing.JTextField Sfrom;
    private javax.swing.JLabel Sfrom1;
    private javax.swing.JTextField Sto;
    private javax.swing.JLabel Sto1;
    private javax.swing.JTextField THfrom;
    private javax.swing.JLabel THfrom1;
    private javax.swing.JTextField THto;
    private javax.swing.JLabel THto1;
    private javax.swing.JTextField TTHfrom;
    private javax.swing.JLabel TTHfrom1;
    private javax.swing.JTextField TTHto;
    private javax.swing.JLabel TTHto1;
    private javax.swing.JTextField TTfrom;
    private javax.swing.JLabel TTfrom1;
    private javax.swing.JTextField TTto;
    private javax.swing.JLabel TTto1;
    private javax.swing.JTextField Tfrom;
    private javax.swing.JLabel Tfrom1;
    private javax.swing.JPanel Times;
    private javax.swing.JTextField Tto;
    private javax.swing.JLabel Tto1;
    private javax.swing.JTextField WWfrom;
    private javax.swing.JLabel WWfrom1;
    private javax.swing.JTextField WWto;
    private javax.swing.JLabel WWto1;
    private javax.swing.JTextField Wfrom;
    private javax.swing.JLabel Wfrom1;
    private javax.swing.JTextField Wto;
    private javax.swing.JLabel Wto1;
    private javax.swing.JLabel _;
    private javax.swing.JLabel _1;
    private javax.swing.JLabel bar;
    private javax.swing.JComboBox<String> doctname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel x;
    private javax.swing.JLabel x1;
    // End of variables declaration//GEN-END:variables

}
