/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahmed Kassem
 */
public class Employee extends javax.swing.JFrame {
int mousex;
int mousey;
    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        ShowE.setEnabled(false);
        ShowE.setVisible(false);
        Add1.setEnabled(false);
        Add1.setVisible(false);
        Show1.setEnabled(false);
        Show1.setVisible(false);
        Show2.setEnabled(false);
        Show2.setVisible(false);
        Home1.setEnabled(false);
        Home1.setVisible(false);
        x1.setEnabled(false);
        x1.setVisible(false);
        _1.setEnabled(false);
        _1.setVisible(false);
        Back1.setEnabled(false);
        Back1.setVisible(false);
        Update1.setEnabled(false);
        Update1.setVisible(false);
        Delete1.setEnabled(false);
        Delete1.setVisible(false);        
        LestEmp.getTableHeader().setReorderingAllowed(false);
        LestEmp.getTableHeader().setBackground(new Color(102, 102, 102));
        LestEmp.getTableHeader().setForeground(Color.BLACK);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        x = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        _ = new javax.swing.JLabel();
        _1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Home1 = new javax.swing.JLabel();
        Show = new javax.swing.JLabel();
        Show1 = new javax.swing.JLabel();
        Show2 = new javax.swing.JLabel();
        NewE = new javax.swing.JPanel();
        Add = new javax.swing.JLabel();
        Add1 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        Salary = new javax.swing.JTextField();
        hiring = new com.toedter.calendar.JDateChooser();
        birth = new com.toedter.calendar.JDateChooser();
        MainE = new javax.swing.JLabel();
        ShowE = new javax.swing.JPanel();
        Back = new javax.swing.JLabel();
        Back1 = new javax.swing.JLabel();
        Update = new javax.swing.JLabel();
        Update1 = new javax.swing.JLabel();
        Delete = new javax.swing.JLabel();
        Delete1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LestEmp = new javax.swing.JTable();
        MainE1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });
        getContentPane().add(x);
        x.setBounds(921, 1, 17, 18);

        x1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/13.png"))); // NOI18N
        x1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(x1);
        x1.setBounds(917, -1, 24, 22);

        _.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _MouseExited(evt);
            }
        });
        getContentPane().add(_);
        _.setBounds(903, 1, 16, 18);

        _1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/15.png"))); // NOI18N
        getContentPane().add(_1);
        _1.setBounds(896, -1, 22, 22);

        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 20);

        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });
        getContentPane().add(Home);
        Home.setBounds(52, 409, 195, 33);

        Home1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home.png"))); // NOI18N
        getContentPane().add(Home1);
        Home1.setBounds(52, 409, 195, 33);

        Show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ShowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ShowMouseExited(evt);
            }
        });
        getContentPane().add(Show);
        Show.setBounds(52, 201, 195, 33);

        Show1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Show Emp.png"))); // NOI18N
        getContentPane().add(Show1);
        Show1.setBounds(52, 201, 195, 33);

        Show2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Show Emp.png"))); // NOI18N
        getContentPane().add(Show2);
        Show2.setBounds(52, 201, 195, 33);

        NewE.setLayout(null);

        Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddMouseExited(evt);
            }
        });
        NewE.add(Add);
        Add.setBounds(52, 132, 195, 33);

        Add1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add.png"))); // NOI18N
        NewE.add(Add1);
        Add1.setBounds(52, 132, 195, 33);

        ID.setEditable(false);
        ID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ID.setBorder(null);
        ID.setOpaque(false);
        NewE.add(ID);
        ID.setBounds(580, 120, 150, 29);

        Name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Name.setForeground(new java.awt.Color(51, 51, 51));
        Name.setBorder(null);
        Name.setOpaque(false);
        NewE.add(Name);
        Name.setBounds(520, 182, 210, 30);

        Phone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Phone.setForeground(new java.awt.Color(51, 51, 51));
        Phone.setBorder(null);
        Phone.setOpaque(false);
        NewE.add(Phone);
        Phone.setBounds(520, 380, 210, 29);

        Salary.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Salary.setForeground(new java.awt.Color(51, 51, 51));
        Salary.setBorder(null);
        Salary.setOpaque(false);
        NewE.add(Salary);
        Salary.setBounds(580, 440, 150, 30);

        hiring.setDateFormatString("yyyy-MM-dd");
        NewE.add(hiring);
        hiring.setBounds(512, 313, 220, 29);

        birth.setDateFormatString("yyyy-MM-dd");
        NewE.add(birth);
        birth.setBounds(512, 247, 220, 29);

        MainE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emp.jpg"))); // NOI18N
        NewE.add(MainE);
        MainE.setBounds(0, 0, 940, 506);

        getContentPane().add(NewE);
        NewE.setBounds(0, 0, 940, 506);

        ShowE.setLayout(null);

        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
        });
        ShowE.add(Back);
        Back.setBounds(52, 132, 195, 33);

        Back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        ShowE.add(Back1);
        Back1.setBounds(52, 132, 195, 33);

        Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateMouseExited(evt);
            }
        });
        ShowE.add(Update);
        Update.setBounds(52, 270, 195, 33);

        Update1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Update.png"))); // NOI18N
        ShowE.add(Update1);
        Update1.setBounds(52, 270, 195, 33);

        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteMouseExited(evt);
            }
        });
        ShowE.add(Delete);
        Delete.setBounds(50, 340, 195, 33);

        Delete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete.png"))); // NOI18N
        ShowE.add(Delete1);
        Delete1.setBounds(50, 340, 195, 33);

        LestEmp.setBackground(new java.awt.Color(184, 197, 251));
        LestEmp.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LestEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "رقم التسلسل", "الاسم", "النسبة ", "الموبايل", "تاريخ التعيين", "تاريخ الميلاد"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        LestEmp.setGridColor(new java.awt.Color(51, 51, 51));
        LestEmp.setOpaque(false);
        LestEmp.setSelectionBackground(new java.awt.Color(102, 102, 102));
        LestEmp.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(LestEmp);

        ShowE.add(jScrollPane1);
        jScrollPane1.setBounds(310, 120, 600, 350);

        MainE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EmpName.png"))); // NOI18N
        ShowE.add(MainE1);
        MainE1.setBounds(0, 0, 940, 506);

        getContentPane().add(ShowE);
        ShowE.setBounds(0, 0, 940, 506);

        setBounds(0, 0, 940, 506);
    }// </editor-fold>//GEN-END:initComponents
     public void clearData() {
        Controls.Tools.clearText(this);
        Name.requestFocus();
        ID.setText(DB.GO.autoNumber("employees", "Number"));
        
    }
    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
        if("".equals(ID.getText()) || "".equals(Name.getText()) || "".equals(hiring.getCalendar()) || "".equals(birth.getCalendar()) || "".equals(Phone.getText()) || "".equals(Salary.getText())){
            JOptionPane.showMessageDialog(this, "رجاء ادخال جميع البيانات ", "خطأ", JOptionPane.ERROR_MESSAGE);
        }else{
            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            String hDate = f.format(hiring.getDate());
            String bDate = f.format(birth.getDate());
            String str = "INSERT INTO employees VALUES ("+ID.getText()+", '"+Name.getText()+"', '"+Salary.getText()+"', '"+Phone.getText()+"', '"+hDate+"', '"+bDate+"')";
            boolean ifadd = DB.GO.runNunQuery(str);
            if(ifadd){
                JOptionPane.showMessageDialog(this, "تم تسجيل البيانات", "نجح", JOptionPane.WARNING_MESSAGE);
                
            }else{
                JOptionPane.showMessageDialog(this, "لم يتم تسجيل البيانات", "خطأ", JOptionPane.ERROR_MESSAGE);
            }
        }
        clearData();
    }//GEN-LAST:event_AddMouseClicked

    private void AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseEntered
        Add1.setEnabled(true);
        Add1.setVisible(true);
    }//GEN-LAST:event_AddMouseEntered

    private void AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseExited
        Add1.setEnabled(false);
        Add1.setVisible(false);
    }//GEN-LAST:event_AddMouseExited

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked

        this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        Home1.setEnabled(true);
        Home1.setVisible(true);
    }//GEN-LAST:event_HomeMouseEntered

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        Home1.setEnabled(false);
        Home1.setVisible(false);
    }//GEN-LAST:event_HomeMouseExited
public void lested(){
    DefaultTableModel table = new DefaultTableModel();
    table.addColumn("رقم التسلسل");
    table.addColumn("الاسم");
    table.addColumn("النسبة");
    table.addColumn("الموبايل");
    table.addColumn("تاريخ التعيين");
    table.addColumn("تاريخ الميلاد");
    
    try{
        Connection con = DB.ConectionDB.setconn();
        String strs = "SELECT * FROM EMPLOYEES";
        Statement st = con.createStatement();
        ResultSet r = st.executeQuery(strs);
        
        while(r.next()){
            table.addRow(new Object[]{
                r.getString(1),
                r.getString(2),
                r.getString(3),
                r.getString(4),
                r.getString(5),
                r.getString(6),
            });
            LestEmp.setModel(table);
        }
    }catch(Exception ex){}
}
    
    private void ShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseClicked
        ShowE.setEnabled(true);
        ShowE.setVisible(true);
        NewE.setEnabled(false);
        NewE.setVisible(false);
        Show2.setEnabled(true);
        Show2.setVisible(true);
        lested();
    }//GEN-LAST:event_ShowMouseClicked

    private void ShowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseEntered
        Show1.setEnabled(true);
        Show1.setVisible(true);
    }//GEN-LAST:event_ShowMouseEntered

    private void ShowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseExited
        Show1.setEnabled(false);
        Show1.setVisible(false);
    }//GEN-LAST:event_ShowMouseExited

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-mousex, y-mousey);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        int a = JOptionPane.showConfirmDialog(this, "هل تريد الخروج ؟", "Exit", JOptionPane.WARNING_MESSAGE);

        if (a == JOptionPane.YES_OPTION) {
            this.dispose();
        } else {

        }
    }//GEN-LAST:event_xMouseClicked

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
        x1.setEnabled(true);
        x1.setVisible(true);
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
        x1.setEnabled(false);
        x1.setVisible(false);
    }//GEN-LAST:event_xMouseExited

    private void _MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseClicked
        this.setState(MainFormE.ICONIFIED);
    }//GEN-LAST:event__MouseClicked

    private void _MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseEntered
        _1.setEnabled(true);
        _1.setVisible(true);
    }//GEN-LAST:event__MouseEntered

    private void _MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseExited
        _1.setEnabled(false);
        _1.setVisible(false);
    }//GEN-LAST:event__MouseExited

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        ShowE.setEnabled(false);
        ShowE.setVisible(false);
        NewE.setEnabled(true);
        NewE.setVisible(true);
        Show2.setEnabled(false);
        Show2.setVisible(false);
    }//GEN-LAST:event_BackMouseClicked

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
        Back1.setEnabled(true);
        Back1.setVisible(true);
    }//GEN-LAST:event_BackMouseEntered

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
        Back1.setEnabled(false);
        Back1.setVisible(false);
    }//GEN-LAST:event_BackMouseExited

    private void UpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseEntered
        Update1.setEnabled(true);
        Update1.setVisible(true);
    }//GEN-LAST:event_UpdateMouseEntered

    private void UpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseExited
        Update1.setEnabled(false);
        Update1.setVisible(false);
    }//GEN-LAST:event_UpdateMouseExited

    private void DeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseEntered
        Delete1.setEnabled(true);
        Delete1.setVisible(true);
    }//GEN-LAST:event_DeleteMouseEntered

    private void DeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseExited
        Delete1.setEnabled(false);
        Delete1.setVisible(false);
    }//GEN-LAST:event_DeleteMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DB.GO.icon(this);
        ID.setText(DB.GO.autoNumber("employees", "Number"));
    }//GEN-LAST:event_formWindowOpened

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        int d = JOptionPane.showConfirmDialog(this, "هل تريد حذف المحدد ؟");
        if(d==JOptionPane.YES_OPTION){
            int row = LestEmp.getSelectedRow();
            String ID = LestEmp.getValueAt(row, 0).toString();
            String strD = "DELETE FROM EMPLOYEES WHERE NUMBER ="+ID;
            boolean ifD = DB.GO.runNunQuery(strD);
            if(ifD){
                JOptionPane.showMessageDialog(this, "تم حذف البيانات", "نجح", JOptionPane.WARNING_MESSAGE);
                lested();
            }
        }else{
            JOptionPane.showMessageDialog(this, "لم يتم حذف شيئ", "خطأ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_DeleteMouseClicked

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        int row = LestEmp.getSelectedRow();
        String ID = LestEmp.getValueAt(row, 0).toString();
        String Name = LestEmp.getValueAt(row, 1).toString();
        String Salary = LestEmp.getValueAt(row, 2).toString();
        String Phone = LestEmp.getValueAt(row, 3).toString();
        //SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        String Hiring = LestEmp.getValueAt(row, 4).toString();
        String Birth = LestEmp.getValueAt(row, 5).toString();
        
        String strU = "UPDATE EMPLOYEES SET NAME='"+Name+"', SALARY='"+Salary+"', PHONE='"+Phone+"', HIRING_DATE='"+Hiring+"', BIRTH_DATE='"+Birth+"' WHERE NUMBER="+ID;
        boolean ifU = DB.GO.runNunQuery(strU);
        if(ifU){
            JOptionPane.showMessageDialog(this, "تم تعديل البيانات", "نجح", JOptionPane.WARNING_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "لم يتم تعديل البيانات", "خطأ", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_UpdateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add;
    private javax.swing.JLabel Add1;
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Back1;
    private javax.swing.JLabel Delete;
    private javax.swing.JLabel Delete1;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Home1;
    private javax.swing.JTextField ID;
    private javax.swing.JTable LestEmp;
    private javax.swing.JLabel MainE;
    private javax.swing.JLabel MainE1;
    private javax.swing.JTextField Name;
    private javax.swing.JPanel NewE;
    private javax.swing.JTextField Phone;
    private javax.swing.JTextField Salary;
    private javax.swing.JLabel Show;
    private javax.swing.JLabel Show1;
    private javax.swing.JLabel Show2;
    private javax.swing.JPanel ShowE;
    private javax.swing.JLabel Update;
    private javax.swing.JLabel Update1;
    private javax.swing.JLabel _;
    private javax.swing.JLabel _1;
    private com.toedter.calendar.JDateChooser birth;
    private com.toedter.calendar.JDateChooser hiring;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel x;
    private javax.swing.JLabel x1;
    // End of variables declaration//GEN-END:variables
}
