/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahmed Kassem
 */
public class Expenses extends javax.swing.JFrame {

    int mousex;
    int mousey;

    /**
     * Creates new form Expenses
     */
    public Expenses() {
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        ExpShow.setEnabled(false);
        ExpShow.setVisible(false);
        Add1.setEnabled(false);
        Add1.setVisible(false);
        Show1.setEnabled(false);
        Show1.setVisible(false);
        Show2.setEnabled(false);
        Show2.setVisible(false);
        exit1.setEnabled(false);
        exit1.setVisible(false);
        x1.setEnabled(false);
        x1.setVisible(false);
        _1.setEnabled(false);
        _1.setVisible(false);
        Back1.setEnabled(false);
        Back1.setVisible(false);
        Delete1.setEnabled(false);
        Delete1.setVisible(false);
        lestexp.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _ = new javax.swing.JLabel();
        _1 = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        bar = new javax.swing.JLabel();
        Show = new javax.swing.JLabel();
        Show1 = new javax.swing.JLabel();
        Show2 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        ExpShow = new javax.swing.JPanel();
        Delete = new javax.swing.JLabel();
        Delete1 = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        Back1 = new javax.swing.JLabel();
        dateday = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lestexp = new javax.swing.JTable();
        main1 = new javax.swing.JLabel();
        Exp = new javax.swing.JPanel();
        Add = new javax.swing.JLabel();
        Add1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        namereg = new javax.swing.JComboBox<>();
        dateexp = new javax.swing.JLabel();
        costexp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        expens = new javax.swing.JTextArea();
        main = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        _.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _MouseExited(evt);
            }
        });
        getContentPane().add(_);
        _.setBounds(896, -1, 22, 22);

        _1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/15.png"))); // NOI18N
        getContentPane().add(_1);
        _1.setBounds(896, -1, 22, 22);

        x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });
        getContentPane().add(x);
        x.setBounds(919, 1, 22, 18);

        x1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/13.png"))); // NOI18N
        x1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(x1);
        x1.setBounds(917, -1, 24, 22);

        bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barMouseDragged(evt);
            }
        });
        bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barMousePressed(evt);
            }
        });
        getContentPane().add(bar);
        bar.setBounds(0, 0, 900, 20);

        Show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ShowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ShowMouseExited(evt);
            }
        });
        getContentPane().add(Show);
        Show.setBounds(50, 354, 195, 33);

        Show1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/عرض المصروفات.png"))); // NOI18N
        getContentPane().add(Show1);
        Show1.setBounds(50, 354, 195, 33);

        Show2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/عرض المصروفات.png"))); // NOI18N
        getContentPane().add(Show2);
        Show2.setBounds(50, 354, 195, 33);

        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(50, 422, 195, 33);

        exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/خروج.png"))); // NOI18N
        getContentPane().add(exit1);
        exit1.setBounds(50, 422, 195, 33);

        ExpShow.setLayout(null);

        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteMouseExited(evt);
            }
        });
        ExpShow.add(Delete);
        Delete.setBounds(49, 285, 195, 33);

        Delete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/حذف.png"))); // NOI18N
        ExpShow.add(Delete1);
        Delete1.setBounds(49, 285, 195, 33);

        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
        });
        ExpShow.add(Back);
        Back.setBounds(50, 147, 195, 33);

        Back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/رجوع.png"))); // NOI18N
        ExpShow.add(Back1);
        Back1.setBounds(50, 147, 195, 33);

        dateday.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ExpShow.add(dateday);
        dateday.setBounds(543, 168, 160, 30);

        jScrollPane2.setBorder(null);

        lestexp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lestexp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "رقم الصرف", "المصروفات", "صرف من", "سجل بواسطة", "تاريخ الصرف", "السعر", "تم دفع"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lestexp.setGridColor(new java.awt.Color(0, 0, 0));
        lestexp.setSelectionBackground(new java.awt.Color(0, 102, 215));
        jScrollPane2.setViewportView(lestexp);

        ExpShow.add(jScrollPane2);
        jScrollPane2.setBounds(290, 212, 630, 280);

        main1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/expenses.jpg"))); // NOI18N
        ExpShow.add(main1);
        main1.setBounds(0, 0, 940, 506);

        getContentPane().add(ExpShow);
        ExpShow.setBounds(0, 0, 940, 506);

        Exp.setLayout(null);

        Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddMouseExited(evt);
            }
        });
        Exp.add(Add);
        Add.setBounds(50, 285, 195, 33);

        Add1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/تسجيل.png"))); // NOI18N
        Exp.add(Add1);
        Add1.setBounds(50, 285, 195, 33);

        id.setEditable(false);
        id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        id.setBorder(null);
        id.setOpaque(false);
        Exp.add(id);
        id.setBounds(538, 136, 160, 28);

        nam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Exp.add(nam);
        nam.setBounds(405, 232, 158, 28);

        namereg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        namereg.setBorder(null);
        namereg.setOpaque(false);
        Exp.add(namereg);
        namereg.setBounds(677, 230, 160, 30);

        dateexp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Exp.add(dateexp);
        dateexp.setBounds(677, 327, 160, 30);

        costexp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        costexp.setBorder(null);
        costexp.setOpaque(false);
        Exp.add(costexp);
        costexp.setBounds(677, 420, 160, 29);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jScrollPane1.setOpaque(false);

        expens.setColumns(20);
        expens.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        expens.setLineWrap(true);
        expens.setRows(5);
        expens.setBorder(null);
        jScrollPane1.setViewportView(expens);

        Exp.add(jScrollPane1);
        jScrollPane1.setBounds(404, 369, 160, 80);

        main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/expenses.png"))); // NOI18N
        Exp.add(main);
        main.setBounds(0, 0, 940, 506);

        getContentPane().add(Exp);
        Exp.setBounds(0, 0, 940, 506);

        setBounds(0, 0, 940, 506);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            int q = JOptionPane.showConfirmDialog(this, "اضغط موافق لتأكيد الخروج", "خروج", JOptionPane.OK_CANCEL_OPTION);
            if (q == JOptionPane.OK_OPTION) {
                this.dispose();
            } else {

            }
        }
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit1.setEnabled(true);
        exit1.setVisible(true);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit1.setEnabled(false);
        exit1.setVisible(false);
    }//GEN-LAST:event_exitMouseExited
    public void lestexp() {
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("رقم الصرف");
        table.addColumn("المصروفات");
        table.addColumn("صرف من");
        table.addColumn("سجل بواسطة");
        table.addColumn("تاريخ الصرف");
        table.addColumn("السعر");
        table.addColumn("تم دفع");
        try {
            Connection con = DB.ConectionDB.setconn();
            Statement st = con.createStatement();
            String strs = "SELECT * FROM EXPENSES WHERE Date_of_exp ='" + dateday.getText() + "'";
            ResultSet r = st.executeQuery(strs);

            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                    r.getString(6),
                    r.getString(7),});
                lestexp.setModel(table);
            }
            lestexp.setModel(table);
        } catch (Exception ex) {
            ex.getMessage();
        }
    }
    private void ShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            ExpShow.setEnabled(true);
            ExpShow.setVisible(true);
            Exp.setEnabled(false);
            Exp.setVisible(false);
            Show2.setEnabled(true);
            Show2.setVisible(true);
            lestexp();
        }
    }//GEN-LAST:event_ShowMouseClicked

    private void ShowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseEntered
        Show1.setEnabled(true);
        Show1.setVisible(true);
    }//GEN-LAST:event_ShowMouseEntered

    private void ShowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseExited
        Show1.setEnabled(false);
        Show1.setVisible(false);
    }//GEN-LAST:event_ShowMouseExited

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            int q = JOptionPane.showConfirmDialog(this, "اضغط موافق لتأكيد الخروج", "خروج", JOptionPane.OK_CANCEL_OPTION);
            if (q == JOptionPane.OK_OPTION) {
                this.dispose();
            } else {

            }
        }
    }//GEN-LAST:event_xMouseClicked

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
        x1.setEnabled(true);
        x1.setVisible(true);
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
        x1.setEnabled(false);
        x1.setVisible(false);
    }//GEN-LAST:event_xMouseExited

    private void _MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.setState(MainFormE.ICONIFIED);
        }
    }//GEN-LAST:event__MouseClicked

    private void _MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseEntered
        _1.setEnabled(true);
        _1.setVisible(true);
    }//GEN-LAST:event__MouseEntered

    private void _MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseExited
        _1.setEnabled(false);
        _1.setVisible(false);
    }//GEN-LAST:event__MouseExited

    private void barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mousex, y - mousey);
    }//GEN-LAST:event_barMouseDragged

    private void barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMousePressed
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_barMousePressed

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            try {
                if ("".equals(id.getText()) || "".equals(dateday.getText()) || namereg.getSelectedItem() == null || "".equals(costexp.getText()) || "".equals(expens.getText()) || "".equals(nam.getText())) {
                    JOptionPane.showMessageDialog(this, "رجاء ادخال جميع البيانات ");
                } else {
                    int c = JOptionPane.showConfirmDialog(this, "لتأكيد حفظ البيانات اضغط موافق", "تنبيه", JOptionPane.OK_CANCEL_OPTION);
                    if (c == JOptionPane.OK_OPTION) {
                        String stra = "INSERT INTO EXPENSES VALUES(" + id.getText() + ", '" + expens.getText() + "', '" + namereg.getSelectedItem() + "', '"
                                + nam.getText() + "', '" + dateexp.getText() + "', '" + costexp.getText() + "', '" + "0" + "')";
                        boolean ifadd = DB.GO.runNunQuery(stra);
                        if (ifadd) {
                            JOptionPane.showMessageDialog(this, "تم حفظ البيانات", "نجح", JOptionPane.WARNING_MESSAGE);
                            costexp.setText("");
                            expens.setText("");
                            namereg.setSelectedItem(null);
                            id.setText(DB.GO.autoNumber("expenses", "anum"));
                            expens.requestFocus();
                        } else {
                            JOptionPane.showMessageDialog(this, "لم يتم حفظ البيانات", "خطأ", JOptionPane.ERROR_MESSAGE);
                            expens.requestFocus();
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "لم يتم حفظ البيانات", "خطأ", JOptionPane.ERROR_MESSAGE);
                        expens.requestFocus();
                    }
                }
            } catch (Exception ex) {
                ex.getMessage();
            }
        }
    }//GEN-LAST:event_AddMouseClicked

    private void AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseEntered
        Add1.setEnabled(true);
        Add1.setVisible(true);
    }//GEN-LAST:event_AddMouseEntered

    private void AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseExited
        Add1.setEnabled(false);
        Add1.setVisible(false);
    }//GEN-LAST:event_AddMouseExited

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            int row = lestexp.getSelectedRow();
            String nu = lestexp.getValueAt(row, 0).toString();
            int c = JOptionPane.showConfirmDialog(this, "اضغط موافق لتأكيد الحذف", "تنبيه", JOptionPane.OK_CANCEL_OPTION);
            if (c == JOptionPane.OK_OPTION) {
                String strd = "DELETE FROM EXPENSES WHERE ANUM=" + nu;
                boolean ifd = DB.GO.runNunQuery(strd);
                if (ifd) {
                    JOptionPane.showMessageDialog(this, "تم حذف البيانات", "نجح", JOptionPane.WARNING_MESSAGE);
                    lestexp();
                    id.setText(DB.GO.autoNumber("expenses", "anum"));
                } else {
                    JOptionPane.showMessageDialog(this, "لم يتم حذف البيانات", "خطأ", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "لم يتم حذف البيانات", "خطأ", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_DeleteMouseClicked

    private void DeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseEntered
        Delete1.setEnabled(true);
        Delete1.setVisible(true);
    }//GEN-LAST:event_DeleteMouseEntered

    private void DeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseExited
        Delete1.setEnabled(false);
        Delete1.setVisible(false);
    }//GEN-LAST:event_DeleteMouseExited

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            ExpShow.setEnabled(false);
            ExpShow.setVisible(false);
            Exp.setEnabled(true);
            Exp.setVisible(true);
            Show2.setEnabled(false);
            Show2.setVisible(false);
        }
    }//GEN-LAST:event_BackMouseClicked

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
        Back1.setEnabled(true);
        Back1.setVisible(true);
    }//GEN-LAST:event_BackMouseEntered

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
        Back1.setEnabled(false);
        Back1.setVisible(false);
    }//GEN-LAST:event_BackMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DB.GO.icon(this);
        Date d = new Date();
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");

        dateexp.setText(f.format(d));
        dateday.setText(f.format(d));
        DB.GO.fillCompo2(namereg);
        namereg.setSelectedItem(null);
        id.setText(DB.GO.autoNumber("expenses", "anum"));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Expenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Expenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Expenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Expenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Expenses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add;
    private javax.swing.JLabel Add1;
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Back1;
    private javax.swing.JLabel Delete;
    private javax.swing.JLabel Delete1;
    private javax.swing.JPanel Exp;
    private javax.swing.JPanel ExpShow;
    private javax.swing.JLabel Show;
    private javax.swing.JLabel Show1;
    private javax.swing.JLabel Show2;
    private javax.swing.JLabel _;
    private javax.swing.JLabel _1;
    private javax.swing.JLabel bar;
    private javax.swing.JTextField costexp;
    private javax.swing.JLabel dateday;
    private javax.swing.JLabel dateexp;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exit1;
    private javax.swing.JTextArea expens;
    private javax.swing.JTextField id;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable lestexp;
    private javax.swing.JLabel main;
    private javax.swing.JLabel main1;
    public static final javax.swing.JLabel nam = new javax.swing.JLabel();
    private javax.swing.JComboBox<String> namereg;
    private javax.swing.JLabel x;
    private javax.swing.JLabel x1;
    // End of variables declaration//GEN-END:variables
}
