/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahmed Kassem
 */
public class PPInfo extends javax.swing.JFrame {

    int mousex;
    int mousey;

    /**
     * Creates new form PPInfo
     */
    public PPInfo() {
        initComponents();
        h1.setVisible(false);
        h1.setEnabled(false);
        s1.setVisible(false);
        s1.setEnabled(false);
        s2.setVisible(false);
        s2.setEnabled(false);
        ch.setVisible(false);
        ch.setEnabled(false);
        x1.setVisible(false);
        x1.setEnabled(false);
        _1.setVisible(false);
        _1.setEnabled(false);
        rL.getTableHeader().setReorderingAllowed(false);
        chL.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ch = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        chL = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        r = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rL = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        h = new javax.swing.JLabel();
        h1 = new javax.swing.JLabel();
        h2 = new javax.swing.JLabel();
        s = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();
        Bar = new javax.swing.JLabel();
        _ = new javax.swing.JLabel();
        _1 = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        ch.setLayout(null);

        jScrollPane2.setBorder(null);

        chL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "رقم المريض", "الاسم", "رقم الكشف", "الطبيب", "الكشف", "تاريخ الكشف", "تاريخ الاستشارة", "الاستشارة"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        chL.setGridColor(new java.awt.Color(0, 0, 0));
        chL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                chLMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(chL);

        ch.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 718, 291);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PIFO.png"))); // NOI18N
        ch.add(jLabel3);
        jLabel3.setBounds(0, 0, 718, 291);

        getContentPane().add(ch);
        ch.setBounds(16, 52, 718, 291);

        r.setLayout(null);

        jScrollPane1.setBorder(null);

        rL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "رقم المريض", "الاسم", "التليفون", "النوع", "تاريخ الميلاد", "العمر", "رقم الحجز", "الطبيب", "تاريخ الحجز", "الكشف"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rL.setGridColor(new java.awt.Color(0, 0, 0));
        rL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rLMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(rL);

        r.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 718, 291);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PIFO.png"))); // NOI18N
        r.add(jLabel2);
        jLabel2.setBounds(0, 0, 718, 291);

        getContentPane().add(r);
        r.setBounds(16, 52, 718, 291);

        h.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        h.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hMouseExited(evt);
            }
        });
        getContentPane().add(h);
        h.setBounds(644, 24, 90, 31);

        h1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/الحجوزات.png"))); // NOI18N
        getContentPane().add(h1);
        h1.setBounds(644, 24, 90, 31);

        h2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/الحجوزات.png"))); // NOI18N
        getContentPane().add(h2);
        h2.setBounds(644, 24, 90, 31);

        s.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        s.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sMouseExited(evt);
            }
        });
        getContentPane().add(s);
        s.setBounds(554, 23, 89, 31);

        s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/الاستشارات.png"))); // NOI18N
        getContentPane().add(s1);
        s1.setBounds(554, 23, 89, 31);

        s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/الاستشارات.png"))); // NOI18N
        getContentPane().add(s2);
        s2.setBounds(554, 23, 89, 31);

        Bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarMouseDragged(evt);
            }
        });
        Bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarMousePressed(evt);
            }
        });
        getContentPane().add(Bar);
        Bar.setBounds(0, 0, 697, 20);

        _.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _MouseExited(evt);
            }
        });
        getContentPane().add(_);
        _.setBounds(700, 0, 19, 20);

        _1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/R_.png"))); // NOI18N
        getContentPane().add(_1);
        _1.setBounds(700, 0, 19, 20);

        x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });
        getContentPane().add(x);
        x.setBounds(719, -1, 22, 22);

        x1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RX.png"))); // NOI18N
        getContentPane().add(x1);
        x1.setBounds(719, -1, 22, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/More info.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 740, 350);

        setSize(new java.awt.Dimension(740, 350));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void LestRESp() {
        try {
            DefaultTableModel table = new DefaultTableModel();
            table.addColumn("رقم المريض");
            table.addColumn("الاسم   ");
            table.addColumn("التليفون   ");
            table.addColumn("النوع");
            table.addColumn("تاريخ الميلاد   ");
            table.addColumn("العمر");
            table.addColumn("رقم الحجز");
            table.addColumn("الطبيب    ");
            table.addColumn("تاريخ الحجز   ");
            table.addColumn("الكشف");

            int roow = MainForm.LPE.getSelectedRow();
            String nuu = MainForm.LPE.getValueAt(roow, 0).toString();

            Connection con = DB.ConectionDB.setconn();
            Statement st = con.createStatement();
            String strs = "SELECT * FROM patients_data WHERE NUMBER LIKE '%" + nuu + "%'  AND DOCNAME LIKE '%" + MainForm.Name1.getText() + "%'";
            ResultSet r = st.executeQuery(strs);

            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                    r.getString(6),
                    r.getString(7),
                    r.getString(8),
                    r.getString(9),
                    r.getString(10),});

                rL.setModel(table);
            }

        } catch (Exception ex) {
            ex.getMessage();
        }
    }

    public void LestRechp() {
        try {
            DefaultTableModel table = new DefaultTableModel();
            table.addColumn("رقم المريض");
            table.addColumn("الاسم   ");
            table.addColumn("رقم الكشف");
            table.addColumn("الطبيب   ");
            table.addColumn("الكشف");
            table.addColumn("تاريخ الكشف   ");
            table.addColumn("تاريخ الاستشارة   ");
            table.addColumn("الاستشارة");

            int roow = MainForm.LPE.getSelectedRow();
            String nuu = MainForm.LPE.getValueAt(roow, 0).toString();

            Connection con = DB.ConectionDB.setconn();
            Statement st = con.createStatement();

            String strs = "SELECT * FROM patients_data_r WHERE NUMBER LIKE '%" + nuu + "%' AND DOCNAME LIKE '%" + MainForm.Name1.getText() + "%'";

            ResultSet r = st.executeQuery(strs);

            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                    r.getString(6),
                    r.getString(7),
                    r.getString(8),});

                chL.setModel(table);
            }

        } catch (Exception ex) {
            ex.getMessage();
        }
    }
    private void BarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mousex, y - mousey);
    }//GEN-LAST:event_BarMouseDragged

    private void BarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarMousePressed
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_BarMousePressed

    private void _MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.setState(Reservations.ICONIFIED);
        }
    }//GEN-LAST:event__MouseClicked

    private void _MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseEntered
        _1.setVisible(true);
        _1.setEnabled(true);
    }//GEN-LAST:event__MouseEntered

    private void _MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseExited
        _1.setVisible(false);
        _1.setEnabled(false);
    }//GEN-LAST:event__MouseExited

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.dispose();
        }
    }//GEN-LAST:event_xMouseClicked

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
        x1.setVisible(true);
        x1.setEnabled(true);
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
        x1.setVisible(false);
        x1.setEnabled(false);
    }//GEN-LAST:event_xMouseExited

    private void hMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            h2.setVisible(true);
            h2.setEnabled(true);
            s2.setVisible(false);
            s2.setEnabled(false);
            ch.setVisible(false);
            ch.setEnabled(false);
            r.setVisible(true);
            r.setEnabled(true);
            LestRESp();
        }
    }//GEN-LAST:event_hMouseClicked

    private void hMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hMouseEntered
        h1.setVisible(true);
        h1.setEnabled(true);
    }//GEN-LAST:event_hMouseEntered

    private void hMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hMouseExited
        h1.setVisible(true);
        h1.setEnabled(true);
    }//GEN-LAST:event_hMouseExited

    private void sMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            h2.setVisible(false);
            h2.setEnabled(false);
            s2.setVisible(true);
            s2.setEnabled(true);
            ch.setVisible(true);
            ch.setEnabled(true);
            r.setVisible(false);
            r.setEnabled(false);
            LestRechp();
        }
    }//GEN-LAST:event_sMouseClicked

    private void sMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sMouseEntered
        s1.setVisible(true);
        s1.setEnabled(true);
    }//GEN-LAST:event_sMouseEntered

    private void sMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sMouseExited
        s1.setVisible(false);
        s1.setEnabled(false);
    }//GEN-LAST:event_sMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DB.GO.icon(this);
        LestRESp();
    }//GEN-LAST:event_formWindowOpened

    private void chLMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chLMouseReleased
        int row = chL.getSelectedRow();
        String pn = chL.getValueAt(row, 0).toString();
        String n = chL.getValueAt(row, 1).toString();
        String cn = chL.getValueAt(row, 2).toString();
        String rcd = chL.getValueAt(row, 6).toString();
        String rc = chL.getValueAt(row, 7).toString();

        if (evt.getButton() == MouseEvent.BUTTON1 && evt.getClickCount() == 2 && "تم".equals(rc)) {

            RCheckUpInfo.PeNumRI.setText(pn);
            RCheckUpInfo.PeNameRI.setText(n);
            RCheckUpInfo.ChNumRI.setText(cn);
            RCheckUpInfo.dateRCI.setText(rcd);

            try {
                Connection con = DB.ConectionDB.setconn();
                Statement st = con.createStatement();
                String strs = "SELECT * FROM recheck_up WHERE CNUM LIKE '%" + cn + "%'";
                ResultSet rt = st.executeQuery(strs);
                while (rt.next()) {

                    RCheckUpInfo.tybeI.setText(rt.getString(3));

                    RCheckUpInfo.widthRI.setText(rt.getString(4));
                    RCheckUpInfo.sugarRI.setText(rt.getString(5));
                    RCheckUpInfo.pressRI.setText(rt.getString(6));
                    RCheckUpInfo.tempRI.setText(rt.getString(7));
                    RCheckUpInfo.notesI.setText(rt.getString(8));
                    RCheckUpInfo.condRI.setText(rt.getString(9));
                    RCheckUpInfo.ReNumRI.setText(rt.getString(15));
                    RCheckUpInfo.eshaatI.setText(rt.getString(10));
                    RCheckUpInfo.thalelI.setText(rt.getString(11));
                    RCheckUpInfo.dwaaI.setText(rt.getString(12));
                    RCheckUpInfo.DoNumRI.setText(rt.getString(14));

                }

                Statement stt = con.createStatement();
                String strss = "SELECT * FROM patients WHERE NUMBER LIKE '%" + pn + "%'";
                ResultSet rs = stt.executeQuery(strss);
                while (rs.next()) {
                    RCheckUpInfo.PeAgeRI.setText(rs.getString(6));

                }

                Statement sst = con.createStatement();
                String strrs = "SELECT * FROM check_up WHERE NUMBER LIKE '%" + cn + "%'";
                ResultSet rrs = sst.executeQuery(strrs);
                while (rrs.next()) {

                    RCheckUpInfo.heightRI.setText(rrs.getString(4));
                }

            } catch (Exception ex) {
                ex.getMessage();
            }
            new RCheckUpInfo().setVisible(true);
        } else {

        }
    }//GEN-LAST:event_chLMouseReleased

    private void rLMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rLMouseReleased
        try {
            int row = rL.getSelectedRow();

            String nu = rL.getValueAt(row, 0).toString();
            String na = rL.getValueAt(row, 1).toString();
            String k = rL.getValueAt(row, 9).toString();
            if (evt.getButton() == MouseEvent.BUTTON1 && evt.getClickCount() == 2 && "تم".equals(k)) {
                checkInfo.PeNumI.setText(nu);
                checkInfo.PeNameI.setText(na);

                Connection con = DB.ConectionDB.setconn();
                Statement st = con.createStatement();
                String strs = "SELECT * FROM check_up WHERE PNumber LIKE '%" + nu + "%'";
                ResultSet rs = st.executeQuery(strs);

                while (rs.next()) {
                    checkInfo.ChNumI.setText(rs.getString(1));
                    checkInfo.Cdate.setText(rs.getString(2));
                    checkInfo.tybeI.setText(rs.getString(3));
                    checkInfo.heightI.setText(rs.getString(4));
                    checkInfo.widthI.setText(rs.getString(5));
                    checkInfo.sugarI.setText(rs.getString(6));
                    checkInfo.pressI.setText(rs.getString(7));
                    checkInfo.tempI.setText(rs.getString(8));
                    checkInfo.notesI.setText(rs.getString(9));
                    checkInfo.eshaatI.setText(rs.getString(10));
                    checkInfo.thalelI.setText(rs.getString(11));
                    checkInfo.dwaaI.setText(rs.getString(12));
                    checkInfo.Rdate.setText(rs.getString(13));
                    checkInfo.DoNumI.setText(rs.getString(14));
                    checkInfo.ReNumI.setText(rs.getString(16));

                }

                Statement str = con.createStatement();
                String strss = "SELECT * FROM patients WHERE NUMBER LIKE '%" + nu + "%'";
                ResultSet rt = st.executeQuery(strss);
                while (rt.next()) {
                    checkInfo.PeAgeI.setText(rt.getString(6));

                }

                new checkInfo().setVisible(true);
            } else {

            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_rLMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PPInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PPInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PPInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PPInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PPInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bar;
    private javax.swing.JLabel _;
    private javax.swing.JLabel _1;
    private javax.swing.JPanel ch;
    private javax.swing.JTable chL;
    private javax.swing.JLabel h;
    private javax.swing.JLabel h1;
    private javax.swing.JLabel h2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel r;
    private javax.swing.JTable rL;
    private javax.swing.JLabel s;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel x;
    private javax.swing.JLabel x1;
    // End of variables declaration//GEN-END:variables
}
