/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahmed Kassem
 */
public class PRInfo extends javax.swing.JFrame {

    int mousex;
    int mousey;

    /**
     * Creates new form PRInfo
     */
    public PRInfo() {
        initComponents();
        rv1.setVisible(false);
        rv1.setEnabled(false);
        rc1.setVisible(false);
        rc1.setEnabled(false);
        rc2.setVisible(false);
        rc2.setEnabled(false);
        rch.setVisible(false);
        rch.setEnabled(false);
        x1.setVisible(false);
        x1.setEnabled(false);
        _1.setVisible(false);
        _1.setEnabled(false);
        resL.getTableHeader().setReorderingAllowed(false);
        rchL.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rch = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rchL = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        res = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resL = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        rv = new javax.swing.JLabel();
        rv1 = new javax.swing.JLabel();
        rv2 = new javax.swing.JLabel();
        rc = new javax.swing.JLabel();
        rc1 = new javax.swing.JLabel();
        rc2 = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        _ = new javax.swing.JLabel();
        _1 = new javax.swing.JLabel();
        Bar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        rch.setLayout(null);

        jScrollPane2.setBorder(null);

        rchL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "رقم المريض", "الاسم", "رقم الكشف", "الطبيب", "الكشف", "تاريخ الكشف", "تاريخ الاستشارة", "الاستشارة"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rchL.setGridColor(new java.awt.Color(0, 0, 0));
        rchL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rchLMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(rchL);

        rch.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 718, 291);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PIFO.png"))); // NOI18N
        rch.add(jLabel2);
        jLabel2.setBounds(0, 0, 718, 291);

        getContentPane().add(rch);
        rch.setBounds(16, 52, 718, 291);

        res.setLayout(null);

        jScrollPane1.setBorder(null);

        resL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "رقم المريض", "الاسم", "التليفون", "النوع", "تاريخ الميلاد", "العمر", "رقم الحجز", "الطبيب", "تاريخ الحجز", "الكشف"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        resL.setGridColor(new java.awt.Color(0, 0, 0));
        resL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                resLMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(resL);

        res.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 718, 291);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PIFO.png"))); // NOI18N
        res.add(jLabel3);
        jLabel3.setBounds(0, 0, 718, 291);

        getContentPane().add(res);
        res.setBounds(16, 52, 718, 291);

        rv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rvMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rvMouseExited(evt);
            }
        });
        getContentPane().add(rv);
        rv.setBounds(644, 24, 90, 31);

        rv1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/الحجوزات.png"))); // NOI18N
        getContentPane().add(rv1);
        rv1.setBounds(644, 24, 90, 31);

        rv2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/الحجوزات.png"))); // NOI18N
        getContentPane().add(rv2);
        rv2.setBounds(644, 24, 90, 31);

        rc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rcMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rcMouseExited(evt);
            }
        });
        getContentPane().add(rc);
        rc.setBounds(554, 23, 89, 31);

        rc1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/الاستشارات.png"))); // NOI18N
        getContentPane().add(rc1);
        rc1.setBounds(554, 23, 89, 31);

        rc2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/الاستشارات.png"))); // NOI18N
        getContentPane().add(rc2);
        rc2.setBounds(554, 23, 89, 31);

        x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });
        getContentPane().add(x);
        x.setBounds(719, -1, 22, 22);

        x1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RX.png"))); // NOI18N
        getContentPane().add(x1);
        x1.setBounds(719, -1, 22, 22);

        _.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _MouseExited(evt);
            }
        });
        getContentPane().add(_);
        _.setBounds(700, 0, 19, 20);

        _1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/R_.png"))); // NOI18N
        getContentPane().add(_1);
        _1.setBounds(700, 0, 19, 20);

        Bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarMouseDragged(evt);
            }
        });
        Bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarMousePressed(evt);
            }
        });
        getContentPane().add(Bar);
        Bar.setBounds(0, 0, 697, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/More info.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 740, 350);

        setSize(new java.awt.Dimension(740, 350));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void LestRESr() {
        try {
            DefaultTableModel table = new DefaultTableModel();
            table.addColumn("رقم المريض");
            table.addColumn("الاسم   ");
            table.addColumn("التليفون   ");
            table.addColumn("النوع");
            table.addColumn("تاريخ الميلاد   ");
            table.addColumn("العمر");
            table.addColumn("رقم الحجز");
            table.addColumn("الطبيب    ");
            table.addColumn("تاريخ الحجز   ");
            table.addColumn("الكشف");

            Connection con = DB.ConectionDB.setconn();
            Statement st = con.createStatement();
            String strs = "SELECT * FROM patients_data WHERE NUMBER LIKE '%" + RCheckUp.PeNumR.getText() + "%'  AND DOCNAME LIKE '%" + MainForm.Name1.getText() + "%'";
            ResultSet r = st.executeQuery(strs);

            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                    r.getString(6),
                    r.getString(7),
                    r.getString(8),
                    r.getString(9),
                    r.getString(10),});

                resL.setModel(table);
            }

        } catch (Exception ex) {
            ex.getMessage();
        }
    }

    public void LestRechr() {
        try {
            DefaultTableModel table = new DefaultTableModel();
            table.addColumn("رقم المريض");
            table.addColumn("الاسم   ");
            table.addColumn("رقم الكشف");
            table.addColumn("الطبيب   ");
            table.addColumn("الكشف");
            table.addColumn("تاريخ الكشف   ");
            table.addColumn("تاريخ الاستشارة   ");
            table.addColumn("الاستشارة");

            Connection con = DB.ConectionDB.setconn();
            Statement st = con.createStatement();

            String strs = "SELECT * FROM patients_data_r WHERE NUMBER LIKE '%" + RCheckUp.PeNumR.getText() + "%' AND DOCNAME LIKE '%" + MainForm.DName.getText() + "%'";

            ResultSet r = st.executeQuery(strs);

            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                    r.getString(6),
                    r.getString(7),
                    r.getString(8),});

                rchL.setModel(table);
            }

        } catch (Exception ex) {
            ex.getMessage();
        }
    }
    private void resLMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resLMouseReleased
        try {
            int row = resL.getSelectedRow();

            String nu = resL.getValueAt(row, 0).toString();
            String na = resL.getValueAt(row, 1).toString();
            String k = resL.getValueAt(row, 9).toString();
            if (evt.getButton() == MouseEvent.BUTTON1 && evt.getClickCount() == 2 && "تم".equals(k)) {
                checkInfo.PeNumI.setText(nu);
                checkInfo.PeNameI.setText(na);

                Connection con = DB.ConectionDB.setconn();
                Statement st = con.createStatement();
                String strs = "SELECT * FROM check_up WHERE PNumber LIKE '%" + nu + "%'";
                ResultSet rs = st.executeQuery(strs);

                while (rs.next()) {
                    checkInfo.ChNumI.setText(rs.getString(1));
                    checkInfo.Cdate.setText(rs.getString(2));
                    checkInfo.tybeI.setText(rs.getString(3));
                    checkInfo.heightI.setText(rs.getString(4));
                    checkInfo.widthI.setText(rs.getString(5));
                    checkInfo.sugarI.setText(rs.getString(6));
                    checkInfo.pressI.setText(rs.getString(7));
                    checkInfo.tempI.setText(rs.getString(8));
                    checkInfo.notesI.setText(rs.getString(9));
                    checkInfo.eshaatI.setText(rs.getString(10));
                    checkInfo.thalelI.setText(rs.getString(11));
                    checkInfo.dwaaI.setText(rs.getString(12));
                    checkInfo.Rdate.setText(rs.getString(13));
                    checkInfo.DoNumI.setText(rs.getString(14));
                    checkInfo.ReNumI.setText(rs.getString(16));

                }

                Statement str = con.createStatement();
                String strss = "SELECT * FROM patients WHERE NUMBER LIKE '%" + nu + "%'";
                ResultSet rt = st.executeQuery(strss);
                while (rt.next()) {
                    checkInfo.PeAgeI.setText(rt.getString(6));

                }

                new checkInfo().setVisible(true);
            } else {

            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_resLMouseReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DB.GO.icon(this);
        LestRESr();
    }//GEN-LAST:event_formWindowOpened

    private void rvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rvMouseEntered
        rv1.setVisible(true);
        rv1.setEnabled(true);
    }//GEN-LAST:event_rvMouseEntered

    private void rvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rvMouseExited
        rv1.setVisible(false);
        rv1.setEnabled(false);
    }//GEN-LAST:event_rvMouseExited

    private void rcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rcMouseEntered
        rc1.setVisible(true);
        rc1.setEnabled(true);
    }//GEN-LAST:event_rcMouseEntered

    private void rcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rcMouseExited
        rc1.setVisible(false);
        rc1.setEnabled(false);
    }//GEN-LAST:event_rcMouseExited

    private void rvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rvMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            rv2.setVisible(true);
            rv2.setEnabled(true);
            rc2.setVisible(false);
            rc2.setEnabled(false);
            rch.setVisible(false);
            rch.setEnabled(false);
            res.setVisible(true);
            res.setEnabled(true);
            LestRESr();
        }
    }//GEN-LAST:event_rvMouseClicked

    private void rcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rcMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            rv2.setVisible(false);
            rv2.setEnabled(false);
            rc2.setVisible(true);
            rc2.setEnabled(true);
            rch.setVisible(true);
            rch.setEnabled(true);
            res.setVisible(false);
            res.setEnabled(false);
            LestRechr();
        }
    }//GEN-LAST:event_rcMouseClicked

    private void rchLMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rchLMouseReleased
        int row = rchL.getSelectedRow();
        String pn = rchL.getValueAt(row, 0).toString();
        String n = rchL.getValueAt(row, 1).toString();
        String cn = rchL.getValueAt(row, 2).toString();
        String rcd = rchL.getValueAt(row, 6).toString();
        String rc = rchL.getValueAt(row, 7).toString();

        if (evt.getButton() == MouseEvent.BUTTON1 && evt.getClickCount() == 2 && "تم".equals(rc)) {

            RCheckUpInfo.PeNumRI.setText(pn);
            RCheckUpInfo.PeNameRI.setText(n);
            RCheckUpInfo.ChNumRI.setText(cn);
            RCheckUpInfo.dateRCI.setText(rcd);

            try {
                Connection con = DB.ConectionDB.setconn();
                Statement st = con.createStatement();
                String strs = "SELECT * FROM recheck_up WHERE CNUM LIKE '%" + cn + "%'";
                ResultSet rt = st.executeQuery(strs);
                while (rt.next()) {

                    RCheckUpInfo.tybeI.setText(rt.getString(3));

                    RCheckUpInfo.widthRI.setText(rt.getString(4));
                    RCheckUpInfo.sugarRI.setText(rt.getString(5));
                    RCheckUpInfo.pressRI.setText(rt.getString(6));
                    RCheckUpInfo.tempRI.setText(rt.getString(7));
                    RCheckUpInfo.notesI.setText(rt.getString(8));
                    RCheckUpInfo.condRI.setText(rt.getString(9));
                    RCheckUpInfo.ReNumRI.setText(rt.getString(15));
                    RCheckUpInfo.eshaatI.setText(rt.getString(10));
                    RCheckUpInfo.thalelI.setText(rt.getString(11));
                    RCheckUpInfo.dwaaI.setText(rt.getString(12));
                    RCheckUpInfo.DoNumRI.setText(rt.getString(14));

                }

                Statement stt = con.createStatement();
                String strss = "SELECT * FROM patients WHERE NUMBER LIKE '%" + pn + "%'";
                ResultSet rs = stt.executeQuery(strss);
                while (rs.next()) {
                    RCheckUpInfo.PeAgeRI.setText(rs.getString(6));

                }

                Statement sst = con.createStatement();
                String strrs = "SELECT * FROM check_up WHERE NUMBER LIKE '%" + cn + "%'";
                ResultSet rrs = sst.executeQuery(strrs);
                while (rrs.next()) {

                    RCheckUpInfo.heightRI.setText(rrs.getString(4));
                }

            } catch (Exception ex) {
                ex.getMessage();
            }
            new RCheckUpInfo().setVisible(true);
        } else {

        }

    }//GEN-LAST:event_rchLMouseReleased

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.dispose();
        }
    }//GEN-LAST:event_xMouseClicked

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
        x1.setVisible(true);
        x1.setEnabled(true);
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
        x1.setVisible(false);
        x1.setEnabled(false);
    }//GEN-LAST:event_xMouseExited

    private void _MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.setState(Reservations.ICONIFIED);
        }
    }//GEN-LAST:event__MouseClicked

    private void _MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseEntered
        _1.setVisible(true);
        _1.setEnabled(true);
    }//GEN-LAST:event__MouseEntered

    private void _MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseExited
        _1.setVisible(false);
        _1.setEnabled(false);
    }//GEN-LAST:event__MouseExited

    private void BarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mousex, y - mousey);
    }//GEN-LAST:event_BarMouseDragged

    private void BarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarMousePressed
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_BarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bar;
    private javax.swing.JLabel _;
    private javax.swing.JLabel _1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel rc;
    private javax.swing.JLabel rc1;
    private javax.swing.JLabel rc2;
    private javax.swing.JPanel rch;
    private javax.swing.JTable rchL;
    private javax.swing.JPanel res;
    private javax.swing.JTable resL;
    private javax.swing.JLabel rv;
    private javax.swing.JLabel rv1;
    private javax.swing.JLabel rv2;
    private javax.swing.JLabel x;
    private javax.swing.JLabel x1;
    // End of variables declaration//GEN-END:variables
}
