/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahmed Kassem
 */
public class ReportCheckup extends javax.swing.JFrame {

    int mousex;
    int mousey;

    /**
     * Creates new form ReportCheckup
     */
    public ReportCheckup() {
        initComponents();
        x1.setEnabled(false);
        x1.setVisible(false);
        _1.setEnabled(false);
        _1.setVisible(false);
        print1.setEnabled(false);
        print1.setVisible(false);
        exit1.setEnabled(false);
        exit1.setVisible(false);
        SePE1.setVisible(false);
        SePE1.setEnabled(false);
        Searchds1.setVisible(false);
        Searchds1.setEnabled(false);
        Searchd1.setVisible(false);
        Searchd1.setEnabled(false);

        searchDate.setEnabled(false);
        searchDate.setVisible(false);
        day.setEnabled(false);
        day.setVisible(false);
        days.setEnabled(false);
        days.setVisible(false);
        search.setEnabled(false);
        search.setVisible(false);
        Controls.Tools.setReport(Chek);
        Chek.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchGroup = new javax.swing.ButtonGroup();
        SearchGroups = new javax.swing.ButtonGroup();
        bar = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        _ = new javax.swing.JLabel();
        _1 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        print = new javax.swing.JLabel();
        print1 = new javax.swing.JLabel();
        btnall = new javax.swing.JRadioButton();
        btnnum = new javax.swing.JRadioButton();
        btnname = new javax.swing.JRadioButton();
        btndate = new javax.swing.JRadioButton();
        search = new javax.swing.JPanel();
        PESearch = new javax.swing.JTextField();
        PESearch1 = new javax.swing.JLabel();
        SePE = new javax.swing.JLabel();
        SePE1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchDate = new javax.swing.JPanel();
        btnday = new javax.swing.JRadioButton();
        btndays = new javax.swing.JRadioButton();
        days = new javax.swing.JPanel();
        Datefrom = new com.toedter.calendar.JDateChooser();
        Dateto = new com.toedter.calendar.JDateChooser();
        Searchds = new javax.swing.JLabel();
        Searchds1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        day = new javax.swing.JPanel();
        DateDay = new com.toedter.calendar.JDateChooser();
        Searchd = new javax.swing.JLabel();
        Searchd1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barMouseDragged(evt);
            }
        });
        bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barMousePressed(evt);
            }
        });
        getContentPane().add(bar);
        bar.setBounds(0, 0, 900, 20);

        x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });
        getContentPane().add(x);
        x.setBounds(919, 1, 22, 18);

        x1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/13.png"))); // NOI18N
        x1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(x1);
        x1.setBounds(917, -1, 24, 21);

        _.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _MouseExited(evt);
            }
        });
        getContentPane().add(_);
        _.setBounds(896, 0, 22, 20);

        _1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/15.png"))); // NOI18N
        getContentPane().add(_1);
        _1.setBounds(896, 0, 22, 20);

        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(26, 430, 195, 33);

        exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/خروج.png"))); // NOI18N
        getContentPane().add(exit1);
        exit1.setBounds(26, 430, 195, 33);

        print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printMouseExited(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(27, 366, 195, 33);

        print1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/طباعة.png"))); // NOI18N
        getContentPane().add(print1);
        print1.setBounds(27, 366, 195, 33);

        btnall.setOpaque(false);
        btnall.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnallItemStateChanged(evt);
            }
        });
        getContentPane().add(btnall);
        btnall.setBounds(837, 111, 20, 20);

        btnnum.setOpaque(false);
        btnnum.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnnumItemStateChanged(evt);
            }
        });
        getContentPane().add(btnnum);
        btnnum.setBounds(765, 111, 20, 20);

        btnname.setOpaque(false);
        btnname.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnnameItemStateChanged(evt);
            }
        });
        getContentPane().add(btnname);
        btnname.setBounds(684, 111, 20, 20);

        btndate.setOpaque(false);
        btndate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btndateItemStateChanged(evt);
            }
        });
        getContentPane().add(btndate);
        btndate.setBounds(594, 111, 20, 20);

        Dname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Dname.setForeground(new java.awt.Color(56, 148, 233));
        getContentPane().add(Dname);
        Dname.setBounds(250, 110, 180, 20);

        Doname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Doname.setForeground(new java.awt.Color(56, 148, 233));
        getContentPane().add(Doname);
        Doname.setBounds(250, 109, 180, 24);

        search.setLayout(null);

        PESearch.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PESearch.setForeground(new java.awt.Color(16, 24, 32));
        PESearch.setToolTipText("");
        PESearch.setBorder(null);
        PESearch.setOpaque(false);
        PESearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PESearchKeyTyped(evt);
            }
        });
        search.add(PESearch);
        PESearch.setBounds(42, 13, 562, 25);

        PESearch1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PESearch1.setForeground(new java.awt.Color(102, 102, 102));
        PESearch1.setText("Search");
        search.add(PESearch1);
        PESearch1.setBounds(44, 16, 90, 20);

        SePE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SePE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SePEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SePEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SePEMouseExited(evt);
            }
        });
        search.add(SePE);
        SePE.setBounds(609, 10, 34, 32);

        SePE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainResSe.png"))); // NOI18N
        search.add(SePE1);
        SePE1.setBounds(609, 10, 34, 32);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ReportCh_Search.png"))); // NOI18N
        search.add(jLabel2);
        jLabel2.setBounds(0, 0, 685, 54);

        getContentPane().add(search);
        search.setBounds(243, 150, 685, 54);

        searchDate.setLayout(null);

        btnday.setOpaque(false);
        btnday.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btndayItemStateChanged(evt);
            }
        });
        searchDate.add(btnday);
        btnday.setBounds(593, 13, 20, 30);

        btndays.setOpaque(false);
        btndays.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btndaysItemStateChanged(evt);
            }
        });
        searchDate.add(btndays);
        btndays.setBounds(522, 13, 20, 30);

        days.setLayout(null);

        Datefrom.setDateFormatString("yyyy-MM-dd");
        days.add(Datefrom);
        Datefrom.setBounds(256, 11, 133, 28);

        Dateto.setDateFormatString("yyyy-MM-dd");
        days.add(Dateto);
        Dateto.setBounds(60, 11, 133, 28);

        Searchds.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Searchds.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchdsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchdsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchdsMouseExited(evt);
            }
        });
        days.add(Searchds);
        Searchds.setBounds(18, 11, 34, 28);

        Searchds1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainResSe.png"))); // NOI18N
        days.add(Searchds1);
        Searchds1.setBounds(18, 11, 34, 28);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ReportCh_Search4.png"))); // NOI18N
        days.add(jLabel5);
        jLabel5.setBounds(0, 0, 458, 51);

        searchDate.add(days);
        days.setBounds(2, 0, 458, 51);

        day.setLayout(null);

        DateDay.setDateFormatString("yyyy-MM-dd");
        day.add(DateDay);
        DateDay.setBounds(66, 11, 240, 28);

        Searchd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Searchd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchdMouseExited(evt);
            }
        });
        day.add(Searchd);
        Searchd.setBounds(18, 11, 34, 28);

        Searchd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainResSe.png"))); // NOI18N
        day.add(Searchd1);
        Searchd1.setBounds(18, 11, 34, 28);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ReportCh_Search3.png"))); // NOI18N
        day.add(jLabel4);
        jLabel4.setBounds(0, 0, 420, 51);

        searchDate.add(day);
        day.setBounds(2, 0, 420, 51);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ReportCh_Search2.png"))); // NOI18N
        searchDate.add(jLabel3);
        jLabel3.setBounds(0, 0, 685, 54);

        getContentPane().add(searchDate);
        searchDate.setBounds(243, 150, 685, 54);

        jScrollPane6.setBorder(null);

        Chek.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Chek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "رقم الكشف", "التاريخ", "المريض", "المرض", "الطبيب", "الكشف", "تاريخ الاستشارة", " الاستشارة"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Chek.setGridColor(new java.awt.Color(0, 0, 0));
        Chek.setSelectionBackground(new java.awt.Color(0, 102, 204));
        jScrollPane6.setViewportView(Chek);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(250, 220, 670, 270);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ReportCheckup.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 940, 506);

        setBounds(0, 0, 940, 506);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DB.GO.icon(this);
        SearchGroup.add(btnall);
        SearchGroup.add(btnnum);
        SearchGroup.add(btnname);
        SearchGroup.add(btndate);

        SearchGroups.add(btnday);
        SearchGroups.add(btndays);
    }//GEN-LAST:event_formWindowOpened
    public void lest() {
        try {
            DefaultTableModel table = new DefaultTableModel();
            table.addColumn("رقم الكشف");
            table.addColumn("التاريخ");
            table.addColumn("المريض");
            table.addColumn("المرض");
            table.addColumn("الطبيب");
            table.addColumn("الكشف");
            table.addColumn("تاريخ الاستشارة");
            table.addColumn("الاستشارة");

            String strs = "SELECT * FROM patients_data_2 WHERE ";

            if (btnnum.isSelected()) {
                strs += " CHNUMBER";
            } else if (btnname.isSelected()) {
                strs += " NAME";
            }
            strs += " LIKE '%" + PESearch.getText() + "%' AND ";
            if (Doname.isVisible()) {
                strs += " DOCNAME like '%" + Doname.getSelectedItem() + "%'";
            } else {
                strs += " DOCNAME like '%" + Dname.getText() + "%'";
            }

            Connection con = DB.ConectionDB.setconn();
            Statement st = con.createStatement();
            ResultSet r = st.executeQuery(strs);

            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(4),
                    r.getString(6),
                    r.getString(7),
                    r.getString(8),
                    r.getString(10),
                    r.getString(11),});
                Chek.setModel(table);
            }
            Chek.setModel(table);
        } catch (Exception ex) {
            ex.getMessage();
        }
    }

    public void lestday() {
        try {
            DefaultTableModel table = new DefaultTableModel();
            table.addColumn("رقم الكشف");
            table.addColumn("التاريخ");
            table.addColumn("المريض");
            table.addColumn("المرض");
            table.addColumn("الطبيب");
            table.addColumn("الكشف");
            table.addColumn("تاريخ الاستشارة");
            table.addColumn("الاستشارة");

            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            String dat = f.format(DateDay.getDate());
            String strs = "SELECT * FROM patients_data_2 WHERE DATE_CHECK  like '%" + dat + "%' AND ";
            if (Doname.isVisible()) {
                strs += " DOCNAME like '%" + Doname.getSelectedItem() + "%'";
            } else {
                strs += " DOCNAME like '%" + Dname.getText() + "%'";
            }       

            Connection con = DB.ConectionDB.setconn();
            Statement st = con.createStatement();
            ResultSet r = st.executeQuery(strs);

            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(4),
                    r.getString(6),
                    r.getString(7),
                    r.getString(8),
                    r.getString(10),
                    r.getString(11),});
                Chek.setModel(table);
            }
            Chek.setModel(table);
        } catch (Exception ex) {
            ex.getMessage();
        }
    }

    public void lestdays() {
        try {
            DefaultTableModel table = new DefaultTableModel();
            table.addColumn("رقم الكشف");
            table.addColumn("التاريخ");
            table.addColumn("المريض");
            table.addColumn("المرض");
            table.addColumn("الطبيب");
            table.addColumn("الكشف");
            table.addColumn("تاريخ الاستشارة");
            table.addColumn("الاستشارة");

            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            String datf = f.format(Datefrom.getDate());
            String datt = f.format(Dateto.getDate());
            String strs = "SELECT * FROM patients_data_2 WHERE DATE_CHECK  BETWEEN '" + datf + "' AND '" + datt + "' AND ";
                    if (Doname.isVisible()) {
                strs += " DOCNAME like '%" + Doname.getSelectedItem() + "%'";
            } else {
                strs += " DOCNAME like '%" + Dname.getText() + "%'";
            }

            Connection con = DB.ConectionDB.setconn();
            Statement st = con.createStatement();
            ResultSet r = st.executeQuery(strs);

            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(4),
                    r.getString(6),
                    r.getString(7),
                    r.getString(8),
                    r.getString(10),
                    r.getString(11),});
                Chek.setModel(table);
            }
            Chek.setModel(table);
        } catch (Exception ex) {
            ex.getMessage();
        }
    }
    private void barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mousex, y - mousey);
    }//GEN-LAST:event_barMouseDragged

    private void barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMousePressed
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_barMousePressed

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.dispose();
        }
    }//GEN-LAST:event_xMouseClicked

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
        x1.setEnabled(true);
        x1.setVisible(true);
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
        x1.setEnabled(false);
        x1.setVisible(false);
    }//GEN-LAST:event_xMouseExited

    private void _MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.setState(MainFormE.ICONIFIED);
        }
    }//GEN-LAST:event__MouseClicked

    private void _MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseEntered
        _1.setEnabled(true);
        _1.setVisible(true);
    }//GEN-LAST:event__MouseEntered

    private void _MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseExited
        _1.setEnabled(false);
        _1.setVisible(false);
    }//GEN-LAST:event__MouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.dispose();
        }
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit1.setEnabled(true);
        exit1.setVisible(true);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit1.setEnabled(false);
        exit1.setVisible(false);
    }//GEN-LAST:event_exitMouseExited

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
        Controls.Tools.printReport(Chek, "Check Up");
    }//GEN-LAST:event_printMouseClicked

    private void printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseEntered
        print1.setEnabled(true);
        print1.setVisible(true);
    }//GEN-LAST:event_printMouseEntered

    private void printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseExited
        print1.setEnabled(false);
        print1.setVisible(false);
    }//GEN-LAST:event_printMouseExited

    private void btndateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btndateItemStateChanged
        searchDate.setVisible(true);
        searchDate.setEnabled(true);
        search.setVisible(false);
        search.setEnabled(false);
        DefaultTableModel mo = (DefaultTableModel) Chek.getModel();
        mo.setNumRows(0);
    }//GEN-LAST:event_btndateItemStateChanged

    private void btnnameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnnameItemStateChanged
        searchDate.setVisible(false);
        searchDate.setEnabled(false);
        search.setVisible(true);
        search.setEnabled(true);
        DefaultTableModel mo = (DefaultTableModel) Chek.getModel();
        mo.setNumRows(0);
        lest();
    }//GEN-LAST:event_btnnameItemStateChanged

    private void btnnumItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnnumItemStateChanged
        searchDate.setVisible(false);
        searchDate.setEnabled(false);
        search.setVisible(true);
        search.setEnabled(true);
        DefaultTableModel mo = (DefaultTableModel) Chek.getModel();
        mo.setNumRows(0);
        lest();
    }//GEN-LAST:event_btnnumItemStateChanged

    private void btnallItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnallItemStateChanged
        searchDate.setVisible(false);
        searchDate.setEnabled(false);
        search.setVisible(false);
        search.setEnabled(false);
        try {
            DefaultTableModel table = new DefaultTableModel();
            table.addColumn("رقم الكشف");
            table.addColumn("التاريخ");
            table.addColumn("المريض");
            table.addColumn("المرض");
            table.addColumn("الطبيب      ");
            table.addColumn("الكشف");
            table.addColumn("تاريخ الاستشارة");
            table.addColumn("الاستشارة");

            String strs = "SELECT * FROM patients_data_2 WHERE ";
            if (Doname.isVisible()) {
                strs += " DOCNAME like '%" + Doname.getSelectedItem() + "%'";
            } else {
                strs += " DOCNAME like '%" + Dname.getText() + "%'";
            }
            Connection con = DB.ConectionDB.setconn();
            Statement st = con.createStatement();
            ResultSet r = st.executeQuery(strs);

            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(4),
                    r.getString(6),
                    r.getString(7),
                    r.getString(8),
                    r.getString(10),
                    r.getString(11),});
                Chek.setModel(table);
            }
            Chek.setModel(table);
        } catch (Exception ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_btnallItemStateChanged

    private void btndayItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btndayItemStateChanged
        days.setVisible(false);
        days.setEnabled(false);
        day.setVisible(true);
        day.setEnabled(true);
        DefaultTableModel mo = (DefaultTableModel) Chek.getModel();
        mo.setNumRows(0);
        Datefrom.setDate(null);
        Dateto.setDate(null);
    }//GEN-LAST:event_btndayItemStateChanged

    private void btndaysItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btndaysItemStateChanged
        days.setVisible(true);
        days.setEnabled(true);
        day.setVisible(false);
        day.setEnabled(false);
        DefaultTableModel mo = (DefaultTableModel) Chek.getModel();
        mo.setNumRows(0);
        DateDay.setDate(null);
    }//GEN-LAST:event_btndaysItemStateChanged

    private void SePEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SePEMouseEntered
        SePE1.setVisible(true);
        SePE1.setEnabled(true);
    }//GEN-LAST:event_SePEMouseEntered

    private void SePEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SePEMouseExited
        SePE1.setVisible(false);
        SePE1.setEnabled(false);
    }//GEN-LAST:event_SePEMouseExited

    private void PESearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PESearchKeyTyped
        if ("".equals(PESearch.getText())) {
            PESearch1.setVisible(true);
            PESearch1.setEnabled(true);
        } else {
            PESearch1.setVisible(false);
            PESearch1.setEnabled(false);
        }
    }//GEN-LAST:event_PESearchKeyTyped

    private void SearchdsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchdsMouseEntered
        Searchds1.setVisible(true);
        Searchds1.setEnabled(true);
    }//GEN-LAST:event_SearchdsMouseEntered

    private void SearchdsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchdsMouseExited
        Searchds1.setVisible(false);
        Searchds1.setEnabled(false);
    }//GEN-LAST:event_SearchdsMouseExited

    private void SearchdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchdMouseEntered
        Searchd1.setVisible(true);
        Searchd1.setEnabled(true);
    }//GEN-LAST:event_SearchdMouseEntered

    private void SearchdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchdMouseExited
        Searchd1.setVisible(false);
        Searchd1.setEnabled(false);
    }//GEN-LAST:event_SearchdMouseExited

    private void SearchdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchdMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            lestday();
        }
    }//GEN-LAST:event_SearchdMouseClicked

    private void SearchdsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchdsMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            lestdays();
        }
    }//GEN-LAST:event_SearchdsMouseClicked

    private void SePEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SePEMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            lest();
        }
    }//GEN-LAST:event_SePEMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportCheckup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportCheckup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportCheckup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportCheckup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportCheckup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JTable Chek = new javax.swing.JTable();
    private com.toedter.calendar.JDateChooser DateDay;
    private com.toedter.calendar.JDateChooser Datefrom;
    private com.toedter.calendar.JDateChooser Dateto;
    public static final javax.swing.JLabel Dname = new javax.swing.JLabel();
    public static final javax.swing.JComboBox<String> Doname = new javax.swing.JComboBox<>();
    private javax.swing.JTextField PESearch;
    private javax.swing.JLabel PESearch1;
    private javax.swing.JLabel SePE;
    private javax.swing.JLabel SePE1;
    private javax.swing.ButtonGroup SearchGroup;
    private javax.swing.ButtonGroup SearchGroups;
    private javax.swing.JLabel Searchd;
    private javax.swing.JLabel Searchd1;
    private javax.swing.JLabel Searchds;
    private javax.swing.JLabel Searchds1;
    private javax.swing.JLabel _;
    private javax.swing.JLabel _1;
    private javax.swing.JLabel bar;
    private javax.swing.JRadioButton btnall;
    private javax.swing.JRadioButton btndate;
    private javax.swing.JRadioButton btnday;
    private javax.swing.JRadioButton btndays;
    private javax.swing.JRadioButton btnname;
    private javax.swing.JRadioButton btnnum;
    private javax.swing.JPanel day;
    private javax.swing.JPanel days;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static final javax.swing.JScrollPane jScrollPane6 = new javax.swing.JScrollPane();
    private javax.swing.JLabel print;
    private javax.swing.JLabel print1;
    private javax.swing.JPanel search;
    private javax.swing.JPanel searchDate;
    private javax.swing.JLabel x;
    private javax.swing.JLabel x1;
    // End of variables declaration//GEN-END:variables
}
