/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahmed Kassem
 */
public class Reportexpenses extends javax.swing.JFrame {

    int mousex;
    int mousey;

    /**
     * Creates new form Reportexpenses
     */
    public Reportexpenses() {
        initComponents();
        x1.setEnabled(false);
        x1.setVisible(false);
        _1.setEnabled(false);
        _1.setVisible(false);
        print1.setEnabled(false);
        print1.setVisible(false);
        exit1.setEnabled(false);
        exit1.setVisible(false);
        Search2.setVisible(false);
        Search2.setEnabled(false);
        Search1.setVisible(false);
        Search1.setEnabled(false);
        day.setEnabled(false);
        day.setVisible(false);
        days.setEnabled(false);
        days.setVisible(false);
        SePE1.setVisible(false);
        SePE1.setEnabled(false);
        Searchds1.setVisible(false);
        Searchds1.setEnabled(false);
        Searchd1.setVisible(false);
        Searchd1.setEnabled(false);
        Controls.Tools.setReport(ExLest);
        ExLest.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchGroup = new javax.swing.ButtonGroup();
        SearchGroups = new javax.swing.ButtonGroup();
        x = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        _ = new javax.swing.JLabel();
        _1 = new javax.swing.JLabel();
        Bar = new javax.swing.JLabel();
        print = new javax.swing.JLabel();
        print1 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ExLest = new javax.swing.JTable();
        Search1 = new javax.swing.JPanel();
        PESearch = new javax.swing.JTextField();
        PESearch1 = new javax.swing.JLabel();
        SePE = new javax.swing.JLabel();
        SePE1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Search2 = new javax.swing.JPanel();
        day = new javax.swing.JPanel();
        DateDay = new com.toedter.calendar.JDateChooser();
        Searchd = new javax.swing.JLabel();
        Searchd1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        days = new javax.swing.JPanel();
        DateFrom = new com.toedter.calendar.JDateChooser();
        DateTo = new com.toedter.calendar.JDateChooser();
        Searchds = new javax.swing.JLabel();
        Searchds1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnday = new javax.swing.JRadioButton();
        btndays = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        btnall = new javax.swing.JRadioButton();
        btnnum = new javax.swing.JRadioButton();
        btnname = new javax.swing.JRadioButton();
        btndate = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });
        getContentPane().add(x);
        x.setBounds(921, 1, 17, 18);

        x1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/13.png"))); // NOI18N
        x1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(x1);
        x1.setBounds(917, -1, 24, 22);

        _.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _MouseExited(evt);
            }
        });
        getContentPane().add(_);
        _.setBounds(903, 1, 16, 18);

        _1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/15.png"))); // NOI18N
        getContentPane().add(_1);
        _1.setBounds(896, -1, 22, 22);

        Bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarMouseDragged(evt);
            }
        });
        Bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarMousePressed(evt);
            }
        });
        getContentPane().add(Bar);
        Bar.setBounds(0, 0, 900, 20);

        print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printMouseExited(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(20, 340, 195, 33);

        print1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/طباعة.png"))); // NOI18N
        getContentPane().add(print1);
        print1.setBounds(20, 340, 195, 33);

        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(20, 398, 195, 33);

        exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/خروج.png"))); // NOI18N
        getContentPane().add(exit1);
        exit1.setBounds(20, 398, 195, 33);

        jScrollPane2.setBorder(null);
        jScrollPane2.setOpaque(false);

        ExLest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ExLest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "رقم الصرف", "تم صرف", "صرف باسم", "سجل من", "تاريخ الصرف", "المبلغ المصروف", "تم خصم"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ExLest.setSelectionBackground(new java.awt.Color(0, 102, 215));
        jScrollPane2.setViewportView(ExLest);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(230, 200, 690, 280);

        Search1.setLayout(null);

        PESearch.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PESearch.setForeground(new java.awt.Color(16, 24, 32));
        PESearch.setToolTipText("");
        PESearch.setBorder(null);
        PESearch.setOpaque(false);
        PESearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PESearchKeyTyped(evt);
            }
        });
        Search1.add(PESearch);
        PESearch.setBounds(42, 13, 562, 25);

        PESearch1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PESearch1.setForeground(new java.awt.Color(102, 102, 102));
        PESearch1.setText("Search");
        Search1.add(PESearch1);
        PESearch1.setBounds(44, 16, 90, 20);

        SePE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SePE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SePEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SePEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SePEMouseExited(evt);
            }
        });
        Search1.add(SePE);
        SePE.setBounds(609, 10, 34, 32);

        SePE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainResSe.png"))); // NOI18N
        Search1.add(SePE1);
        SePE1.setBounds(609, 10, 34, 32);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ReportexpS2.png"))); // NOI18N
        Search1.add(jLabel2);
        jLabel2.setBounds(0, 0, 683, 50);

        getContentPane().add(Search1);
        Search1.setBounds(236, 144, 683, 50);

        Search2.setLayout(null);

        day.setLayout(null);

        DateDay.setDateFormatString("yyyy-MM-dd");
        day.add(DateDay);
        DateDay.setBounds(75, 10, 230, 30);

        Searchd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Searchd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchdMouseExited(evt);
            }
        });
        day.add(Searchd);
        Searchd.setBounds(18, 11, 34, 28);

        Searchd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainResSe.png"))); // NOI18N
        day.add(Searchd1);
        Searchd1.setBounds(18, 11, 34, 28);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ReportexpS3.png"))); // NOI18N
        day.add(jLabel4);
        jLabel4.setBounds(0, 0, 420, 50);

        Search2.add(day);
        day.setBounds(0, 0, 420, 50);

        days.setLayout(null);

        DateFrom.setDateFormatString("yyyy-MM-dd");
        days.add(DateFrom);
        DateFrom.setBounds(258, 10, 130, 30);

        DateTo.setDateFormatString("yyyy-MM-dd");
        days.add(DateTo);
        DateTo.setBounds(60, 10, 130, 30);

        Searchds.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Searchds.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchdsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchdsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchdsMouseExited(evt);
            }
        });
        days.add(Searchds);
        Searchds.setBounds(18, 11, 34, 28);

        Searchds1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainResSe.png"))); // NOI18N
        days.add(Searchds1);
        Searchds1.setBounds(18, 11, 34, 28);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ReportexpS4.png"))); // NOI18N
        days.add(jLabel5);
        jLabel5.setBounds(0, 0, 458, 50);

        Search2.add(days);
        days.setBounds(0, 0, 458, 50);

        btnday.setOpaque(false);
        btnday.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btndayItemStateChanged(evt);
            }
        });
        Search2.add(btnday);
        btnday.setBounds(593, 13, 20, 30);

        btndays.setOpaque(false);
        btndays.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btndaysItemStateChanged(evt);
            }
        });
        Search2.add(btndays);
        btndays.setBounds(522, 13, 20, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ReportexpS1.png"))); // NOI18N
        Search2.add(jLabel3);
        jLabel3.setBounds(0, 0, 683, 50);

        getContentPane().add(Search2);
        Search2.setBounds(236, 144, 683, 50);

        btnall.setOpaque(false);
        btnall.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnallItemStateChanged(evt);
            }
        });
        getContentPane().add(btnall);
        btnall.setBounds(823, 115, 20, 20);

        btnnum.setOpaque(false);
        btnnum.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnnumItemStateChanged(evt);
            }
        });
        getContentPane().add(btnnum);
        btnnum.setBounds(755, 115, 20, 20);

        btnname.setOpaque(false);
        btnname.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnnameItemStateChanged(evt);
            }
        });
        getContentPane().add(btnname);
        btnname.setBounds(671, 115, 20, 20);

        btndate.setOpaque(false);
        btndate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btndateItemStateChanged(evt);
            }
        });
        getContentPane().add(btndate);
        btndate.setBounds(583, 115, 20, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Reportexpenses.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 940, 506);

        setBounds(0, 0, 940, 506);
    }// </editor-fold>//GEN-END:initComponents
public void Liste() {
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("رقم الصرف");
        table.addColumn("تم صرف");
        table.addColumn("صرف باسم");
        table.addColumn("سجل من");
        table.addColumn("تاريخ الصرف");
        table.addColumn("مبلغ المصروف");
        table.addColumn("تم خصم");

        try {
            Connection con = DB.ConectionDB.setconn();
            String strs = "SELECT * FROM expenses";
            Statement st = con.createStatement();
            ResultSet r = st.executeQuery(strs);
            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                    r.getString(6),
                    r.getString(7),});
                ExLest.setModel(table);
            }

        } catch (Exception ex) {

        }
    }

    public void List() {
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("رقم الصرف");
        table.addColumn("تم صرف");
        table.addColumn("صرف باسم");
        table.addColumn("سجل من");
        table.addColumn("تاريخ الصرف");
        table.addColumn("مبلغ المصروف");
        table.addColumn("تم خصم");

        try {
            Connection con = DB.ConectionDB.setconn();
            String strs = "SELECT * FROM expenses where ";
            if (btnnum.isSelected()) {
                strs += "ANum";
            } else if (btnname.isSelected()) {
                strs += "Name_exp";
            }
            strs += " LIKE '%" + PESearch.getText() + "%'";

            Statement st = con.createStatement();
            ResultSet r = st.executeQuery(strs);
            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                    r.getString(6),
                    r.getString(7),});
                ExLest.setModel(table);
            }

        } catch (Exception ex) {

        }
    }

    public void Listday() {
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("رقم الصرف");
        table.addColumn("تم صرف");
        table.addColumn("صرف باسم");
        table.addColumn("سجل من");
        table.addColumn("تاريخ الصرف");
        table.addColumn("مبلغ المصروف");
        table.addColumn("تم خصم");

        try {
            Connection con = DB.ConectionDB.setconn();
            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            String dat = f.format(DateDay.getDate());

            String strs = "SELECT * FROM expenses where Date_of_exp like '%" + dat + "%'";
            Statement st = con.createStatement();
            ResultSet r = st.executeQuery(strs);
            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                    r.getString(6),
                    r.getString(7),});
                ExLest.setModel(table);
            }

        } catch (Exception ex) {

        }
    }

    public void Listdays() {
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("رقم الصرف");
        table.addColumn("تم صرف");
        table.addColumn("صرف باسم");
        table.addColumn("سجل من");
        table.addColumn("تاريخ الصرف");
        table.addColumn("مبلغ المصروف");
        table.addColumn("تم خصم");

        try {
            Connection con = DB.ConectionDB.setconn();
            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            String datf = f.format(DateFrom.getDate());
            String datt = f.format(DateTo.getDate());
            String strs = "SELECT * FROM expenses where Date_of_exp BETWEEN '" + datf + "' AND '" + datt + "'";

            Statement st = con.createStatement();
            ResultSet r = st.executeQuery(strs);
            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                    r.getString(6),
                    r.getString(7),});
                ExLest.setModel(table);
            }

        } catch (Exception ex) {

        }
    }
    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            Controls.Tools.printReport(ExLest, "Expenses");
        }
    }//GEN-LAST:event_printMouseClicked

    private void printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseEntered
        print1.setVisible(true);
        print1.setEnabled(true);
    }//GEN-LAST:event_printMouseEntered

    private void printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseExited
        print1.setVisible(false);
        print1.setEnabled(false);
    }//GEN-LAST:event_printMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.dispose();
        }
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit1.setEnabled(true);
        exit1.setVisible(true);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit1.setEnabled(false);
        exit1.setVisible(false);
    }//GEN-LAST:event_exitMouseExited

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.dispose();
        }
    }//GEN-LAST:event_xMouseClicked

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
        x1.setEnabled(true);
        x1.setVisible(true);
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
        x1.setEnabled(false);
        x1.setVisible(false);
    }//GEN-LAST:event_xMouseExited

    private void _MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseClicked
        this.setState(MainFormE.ICONIFIED);
    }//GEN-LAST:event__MouseClicked

    private void _MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseEntered
        _1.setEnabled(true);
        _1.setVisible(true);
    }//GEN-LAST:event__MouseEntered

    private void _MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseExited
        _1.setEnabled(false);
        _1.setVisible(false);
    }//GEN-LAST:event__MouseExited

    private void BarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mousex, y - mousey);
    }//GEN-LAST:event_BarMouseDragged

    private void BarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarMousePressed
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_BarMousePressed

    private void btndayItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btndayItemStateChanged
        days.setVisible(false);
        days.setEnabled(false);
        day.setVisible(true);
        day.setEnabled(true);
        DefaultTableModel mo = (DefaultTableModel) ExLest.getModel();
        mo.setNumRows(0);
        DateFrom.setDate(null);
        DateTo.setDate(null);
    }//GEN-LAST:event_btndayItemStateChanged

    private void btndaysItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btndaysItemStateChanged
        days.setVisible(true);
        days.setEnabled(true);
        day.setVisible(false);
        day.setEnabled(false);
        DefaultTableModel mo = (DefaultTableModel) ExLest.getModel();
        mo.setNumRows(0);
        DateDay.setDate(null);
    }//GEN-LAST:event_btndaysItemStateChanged

    private void btnallItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnallItemStateChanged
        Search2.setVisible(false);
        Search2.setEnabled(false);
        Search1.setVisible(false);
        Search1.setEnabled(false);
        Liste();
    }//GEN-LAST:event_btnallItemStateChanged

    private void btnnumItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnnumItemStateChanged
        Search2.setVisible(false);
        Search2.setEnabled(false);
        Search1.setVisible(true);
        Search1.setEnabled(true);
        DefaultTableModel mo = (DefaultTableModel) ExLest.getModel();
        mo.setNumRows(0);

    }//GEN-LAST:event_btnnumItemStateChanged

    private void btnnameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnnameItemStateChanged
        Search2.setVisible(false);
        Search2.setEnabled(false);
        Search1.setVisible(true);
        Search1.setEnabled(true);
        DefaultTableModel mo = (DefaultTableModel) ExLest.getModel();
        mo.setNumRows(0);

    }//GEN-LAST:event_btnnameItemStateChanged

    private void btndateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btndateItemStateChanged
        Search2.setVisible(true);
        Search2.setEnabled(true);
        Search1.setVisible(false);
        Search1.setEnabled(false);
        DefaultTableModel mo = (DefaultTableModel) ExLest.getModel();
        mo.setNumRows(0);
    }//GEN-LAST:event_btndateItemStateChanged

    private void SearchdsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchdsMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            Listdays();
        }
    }//GEN-LAST:event_SearchdsMouseClicked

    private void SearchdsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchdsMouseEntered
        Searchds1.setVisible(true);
        Searchds1.setEnabled(true);
    }//GEN-LAST:event_SearchdsMouseEntered

    private void SearchdsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchdsMouseExited
        Searchds1.setVisible(false);
        Searchds1.setEnabled(false);
    }//GEN-LAST:event_SearchdsMouseExited

    private void SearchdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchdMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            Listday();
        }
    }//GEN-LAST:event_SearchdMouseClicked

    private void SearchdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchdMouseEntered
        Searchd1.setVisible(true);
        Searchd1.setEnabled(true);
    }//GEN-LAST:event_SearchdMouseEntered

    private void SearchdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchdMouseExited
        Searchd1.setVisible(false);
        Searchd1.setEnabled(false);
    }//GEN-LAST:event_SearchdMouseExited

    private void PESearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PESearchKeyTyped
        if ("".equals(PESearch.getText())) {
            PESearch1.setVisible(true);
            PESearch1.setEnabled(true);
        } else {
            PESearch1.setVisible(false);
            PESearch1.setEnabled(false);
        }
    }//GEN-LAST:event_PESearchKeyTyped

    private void SePEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SePEMouseEntered
        SePE1.setVisible(true);
        SePE1.setEnabled(true);
    }//GEN-LAST:event_SePEMouseEntered

    private void SePEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SePEMouseExited
        SePE1.setVisible(false);
        SePE1.setEnabled(false);
    }//GEN-LAST:event_SePEMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DB.GO.icon(this);
        SearchGroup.add(btnall);
        SearchGroup.add(btnnum);
        SearchGroup.add(btnname);
        SearchGroup.add(btndate);

        SearchGroups.add(btnday);
        SearchGroups.add(btndays);
    }//GEN-LAST:event_formWindowOpened

    private void SePEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SePEMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            List();
        }
    }//GEN-LAST:event_SePEMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportexpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportexpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportexpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportexpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportexpenses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bar;
    private com.toedter.calendar.JDateChooser DateDay;
    private com.toedter.calendar.JDateChooser DateFrom;
    private com.toedter.calendar.JDateChooser DateTo;
    private javax.swing.JTable ExLest;
    private javax.swing.JTextField PESearch;
    private javax.swing.JLabel PESearch1;
    private javax.swing.JLabel SePE;
    private javax.swing.JLabel SePE1;
    private javax.swing.JPanel Search1;
    private javax.swing.JPanel Search2;
    private javax.swing.ButtonGroup SearchGroup;
    private javax.swing.ButtonGroup SearchGroups;
    private javax.swing.JLabel Searchd;
    private javax.swing.JLabel Searchd1;
    private javax.swing.JLabel Searchds;
    private javax.swing.JLabel Searchds1;
    private javax.swing.JLabel _;
    private javax.swing.JLabel _1;
    private javax.swing.JRadioButton btnall;
    private javax.swing.JRadioButton btndate;
    private javax.swing.JRadioButton btnday;
    private javax.swing.JRadioButton btndays;
    private javax.swing.JRadioButton btnname;
    private javax.swing.JRadioButton btnnum;
    private javax.swing.JPanel day;
    private javax.swing.JPanel days;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel print;
    private javax.swing.JLabel print1;
    private javax.swing.JLabel x;
    private javax.swing.JLabel x1;
    // End of variables declaration//GEN-END:variables
}
