/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahmed Kassem
 */
public class Times extends javax.swing.JFrame {

    int mousex;
    int mousey;

    /**
     * Creates new form Times
     */
    public Times() {
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        TimesShow.setEnabled(false);
        TimesShow.setVisible(false);
        Add1.setEnabled(false);
        Add1.setVisible(false);
        Show3.setEnabled(false);
        Show3.setVisible(false);
        Show2.setEnabled(false);
        Show2.setVisible(false);
        Exit1.setEnabled(false);
        Exit1.setVisible(false);
        x1.setEnabled(false);
        x1.setVisible(false);
        _1.setEnabled(false);
        _1.setVisible(false);
        Back1.setEnabled(false);
        Back1.setVisible(false);
        Update1.setEnabled(false);
        Update1.setVisible(false);
        Delete1.setEnabled(false);
        Delete1.setVisible(false);
        Search1.setVisible(false);
        Search1.setEnabled(false);
        Lest.getTableHeader().setReorderingAllowed(false);
        Lest.getTableHeader().setBackground(new Color(102, 102, 102));
        Lest.getTableHeader().setForeground(Color.BLACK);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        x = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        _ = new javax.swing.JLabel();
        _1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        Exit1 = new javax.swing.JLabel();
        Show1 = new javax.swing.JLabel();
        Show2 = new javax.swing.JLabel();
        Show3 = new javax.swing.JLabel();
        TimesShow = new javax.swing.JPanel();
        Update1 = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        Back1 = new javax.swing.JLabel();
        Update = new javax.swing.JLabel();
        Delete = new javax.swing.JLabel();
        Delete1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lest = new javax.swing.JTable();
        Dnam = new javax.swing.JComboBox<>();
        Search = new javax.swing.JLabel();
        Search1 = new javax.swing.JLabel();
        Main2 = new javax.swing.JLabel();
        DID = new javax.swing.JLabel();
        Times = new javax.swing.JPanel();
        Add = new javax.swing.JLabel();
        Add1 = new javax.swing.JLabel();
        Days = new javax.swing.JComboBox<>();
        DName = new javax.swing.JComboBox<>();
        Shift = new javax.swing.JComboBox<>();
        Date d = new Date();
        SpinnerDateModel so =
        new SpinnerDateModel(d,null,null,Calendar.HOUR_OF_DAY);
        from = new javax.swing.JSpinner(so);
        Date da = new Date();
        SpinnerDateModel soo =
        new SpinnerDateModel(da,null,null,Calendar.HOUR_OF_DAY);
        to = new javax.swing.JSpinner(soo);
        JSpinner.DateEditor ded = new JSpinner.DateEditor(to,"HH:mm");
        to.setEditor(ded);
        Main1 = new javax.swing.JLabel();
        docid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });
        getContentPane().add(x);
        x.setBounds(921, 1, 17, 18);

        x1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/13.png"))); // NOI18N
        x1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(x1);
        x1.setBounds(917, -1, 24, 22);

        _.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _MouseExited(evt);
            }
        });
        getContentPane().add(_);
        _.setBounds(903, 1, 16, 18);

        _1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/15.png"))); // NOI18N
        getContentPane().add(_1);
        _1.setBounds(896, -1, 22, 22);

        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 20);

        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(52, 409, 195, 33);

        Exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit Times.png"))); // NOI18N
        getContentPane().add(Exit1);
        Exit1.setBounds(52, 409, 195, 33);

        Show1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Show1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Show1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Show1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Show1MouseExited(evt);
            }
        });
        getContentPane().add(Show1);
        Show1.setBounds(52, 201, 195, 33);

        Show2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Show Times.png"))); // NOI18N
        getContentPane().add(Show2);
        Show2.setBounds(52, 201, 195, 33);

        Show3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Show Times.png"))); // NOI18N
        getContentPane().add(Show3);
        Show3.setBounds(52, 201, 195, 33);

        TimesShow.setLayout(null);

        Update1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Update.png"))); // NOI18N
        Update1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TimesShow.add(Update1);
        Update1.setBounds(52, 270, 195, 33);

        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
        });
        TimesShow.add(Back);
        Back.setBounds(52, 132, 195, 33);

        Back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        TimesShow.add(Back1);
        Back1.setBounds(52, 132, 195, 33);

        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateMouseExited(evt);
            }
        });
        TimesShow.add(Update);
        Update.setBounds(52, 270, 195, 33);

        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteMouseExited(evt);
            }
        });
        TimesShow.add(Delete);
        Delete.setBounds(50, 340, 195, 33);

        Delete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete.png"))); // NOI18N
        TimesShow.add(Delete1);
        Delete1.setBounds(50, 340, 195, 33);

        Lest.setBackground(new java.awt.Color(184, 197, 251));
        Lest.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Lest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "رقم التسلسل", "اليوم", "من", "إلى", "رقم الشيفت"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Lest.setGridColor(new java.awt.Color(51, 51, 51));
        Lest.setOpaque(false);
        Lest.setSelectionBackground(new java.awt.Color(102, 102, 102));
        Lest.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(Lest);

        TimesShow.add(jScrollPane1);
        jScrollPane1.setBounds(310, 190, 600, 280);

        Dnam.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Dnam.setForeground(new java.awt.Color(0, 0, 130));
        Dnam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        Dnam.setBorder(null);
        Dnam.setOpaque(false);
        Dnam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DnamItemStateChanged(evt);
            }
        });
        TimesShow.add(Dnam);
        Dnam.setBounds(610, 129, 160, 29);

        Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchMouseExited(evt);
            }
        });
        TimesShow.add(Search);
        Search.setBounds(541, 120, 43, 46);

        Search1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        TimesShow.add(Search1);
        Search1.setBounds(541, 120, 43, 46);

        Main2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ShowTime.png"))); // NOI18N
        TimesShow.add(Main2);
        Main2.setBounds(0, 0, 940, 506);

        DID.setForeground(new java.awt.Color(255, 255, 255));
        TimesShow.add(DID);
        DID.setBounds(640, 50, 60, 30);

        getContentPane().add(TimesShow);
        TimesShow.setBounds(0, 0, 940, 506);

        Times.setLayout(null);

        Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddMouseExited(evt);
            }
        });
        Times.add(Add);
        Add.setBounds(52, 132, 195, 33);

        Add1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add.png"))); // NOI18N
        Times.add(Add1);
        Add1.setBounds(52, 132, 195, 33);

        Days.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Days.setForeground(new java.awt.Color(0, 0, 130));
        Days.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "السبت", "الاحد", "الاثنين", "الثلاثاء", "الاربعاء", "الخميس", "الجمعه" }));
        Days.setBorder(null);
        Days.setOpaque(false);
        Times.add(Days);
        Days.setBounds(576, 293, 160, 29);

        DName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DName.setForeground(new java.awt.Color(0, 0, 130));
        DName.setBorder(null);
        DName.setOpaque(false);
        DName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DNameItemStateChanged(evt);
            }
        });
        Times.add(DName);
        DName.setBounds(706, 160, 160, 29);

        Shift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1", "2" }));
        Shift.setBorder(null);
        Shift.setOpaque(false);
        Times.add(Shift);
        Shift.setBounds(454, 160, 120, 29);

        JSpinner.DateEditor de = new JSpinner.DateEditor(from,"HH:mm");
        from.setEditor(de);
        from.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        from.setBorder(null);
        from.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Times.add(from);
        from.setBounds(750, 399, 111, 30);

        to.setBackground(new Color(0, 0, 0));
        to.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        to.setBorder(null);
        to.setOpaque(false);
        Times.add(to);
        to.setBounds(458, 399, 111, 30);

        Main1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Time.png"))); // NOI18N
        Times.add(Main1);
        Main1.setBounds(0, 0, 940, 506);

        docid.setForeground(new java.awt.Color(255, 255, 255));
        Times.add(docid);
        docid.setBounds(710, 70, 80, 30);

        getContentPane().add(Times);
        Times.setBounds(0, 0, 940, 506);

        setBounds(0, 0, 940, 506);
    }// </editor-fold>//GEN-END:initComponents
public void Listed() {
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("رقم التسلسل");
        table.addColumn("اليوم");
        table.addColumn("من");
        table.addColumn("إلى");
        table.addColumn("رقم الشيفت");

        try {
            Connection con = DB.ConectionDB.setconn();
            String strs = "SELECT * FROM doc_times WHERE dnum like '%" + DID.getText() + "%'";
            Statement st = con.createStatement();
            ResultSet r = st.executeQuery(strs);

            while (r.next()) {
                table.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                });
                Lest.setModel(table);
                if (r.getString(1) == null) {
                    table.setNumRows(0);
                }
            }
        } catch (Exception ex) {

        }
    }
    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        this.dispose();
    }//GEN-LAST:event_xMouseClicked

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
        x1.setEnabled(true);
        x1.setVisible(true);
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
        x1.setEnabled(false);
        x1.setVisible(false);
    }//GEN-LAST:event_xMouseExited

    private void _MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseClicked
        this.setState(MainFormE.ICONIFIED);
    }//GEN-LAST:event__MouseClicked

    private void _MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseEntered
        _1.setEnabled(true);
        _1.setVisible(true);
    }//GEN-LAST:event__MouseEntered

    private void _MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseExited
        _1.setEnabled(false);
        _1.setVisible(false);
    }//GEN-LAST:event__MouseExited

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mousex, y - mousey);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked

        this.dispose();
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        Exit1.setEnabled(true);
        Exit1.setVisible(true);
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        Exit1.setEnabled(false);
        Exit1.setVisible(false);
    }//GEN-LAST:event_ExitMouseExited

    private void Show1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Show1MouseClicked
        TimesShow.setEnabled(true);
        TimesShow.setVisible(true);
        Times.setEnabled(false);
        Times.setVisible(false);
        Show3.setEnabled(true);
        Show3.setVisible(true);
        //Listed();
    }//GEN-LAST:event_Show1MouseClicked

    private void Show1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Show1MouseEntered
        Show2.setEnabled(true);
        Show2.setVisible(true);
    }//GEN-LAST:event_Show1MouseEntered

    private void Show1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Show1MouseExited
        Show2.setEnabled(false);
        Show2.setVisible(false);
    }//GEN-LAST:event_Show1MouseExited
    public void clearData() {
        Controls.Tools.clearText(this);
    }
    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
        if (DName.getSelectedItem()== null || "".equals(Days.getSelectedItem()) || "".equals(from.getValue()) || "".equals(to.getValue()) || "".equals(Shift.getSelectedItem())) {
            JOptionPane.showMessageDialog(this, "رجاء ادخال جميع البيانات ", "خطأ", JOptionPane.ERROR_MESSAGE);
        } else {
            SimpleDateFormat fr = new SimpleDateFormat("HH:mm");
            String Sfrom = fr.format(from.getValue());
            String Sto = fr.format(to.getValue());
            String stri = "INSERT INTO doc_times VALUES (" + docid.getText() + ", '" + Days.getSelectedItem() + "', '" + Sfrom + "', '" + Sto + "', "+Shift.getSelectedItem()+")";
            boolean ifadd = DB.GO.runNunQuery(stri);
            if (ifadd) {
                JOptionPane.showMessageDialog(this, "تم تسجيل البيانات", "نجح", JOptionPane.WARNING_MESSAGE);
                //clearData();
                Days.setSelectedItem("");
                Shift.setSelectedItem("");
                
                DName.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "لم يتم تسجيل البيانات", "خطأ", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_AddMouseClicked

    private void AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseEntered
        Add1.setEnabled(true);
        Add1.setVisible(true);
    }//GEN-LAST:event_AddMouseEntered

    private void AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseExited
        Add1.setEnabled(false);
        Add1.setVisible(false);
    }//GEN-LAST:event_AddMouseExited

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        TimesShow.setEnabled(false);
        TimesShow.setVisible(false);
        Times.setEnabled(true);
        Times.setVisible(true);
        Show3.setEnabled(false);
        Show3.setVisible(false);
    }//GEN-LAST:event_BackMouseClicked

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
        Back1.setEnabled(true);
        Back1.setVisible(true);
    }//GEN-LAST:event_BackMouseEntered

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
        Back1.setEnabled(false);
        Back1.setVisible(false);
    }//GEN-LAST:event_BackMouseExited

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        int row = Lest.getSelectedRow();
        String id = Lest.getValueAt(row, 0).toString();
        String days = Lest.getValueAt(row, 1).toString();
        String f = Lest.getValueAt(row, 2).toString();
        String t = Lest.getValueAt(row, 3).toString();
        String sh = Lest.getValueAt(row, 4).toString();
        
        String stru = "UPDATE DOC_TIMES SET Days='"+days+"', t_from='"+f+"', t_to='"+t+"', shift="+sh+" where dNum="+id+" and days='"+days+"' and shift='"+sh+"'";
        boolean ifu = DB.GO.runNunQuery(stru);
        if (ifu) {
            JOptionPane.showMessageDialog(this, "تم تعديل البيانات", "نجح", JOptionPane.WARNING_MESSAGE);
            //Show3.setVisible(true);
            //Show3.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "لم يتم تعديل البيانات", "خطأ", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_UpdateMouseClicked

    private void UpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseEntered
        Update1.setEnabled(true);
        Update1.setVisible(true);
    }//GEN-LAST:event_UpdateMouseEntered

    private void UpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseExited
        Update1.setEnabled(false);
        Update1.setVisible(false);
    }//GEN-LAST:event_UpdateMouseExited

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        int row = Lest.getSelectedRow();
        String id = Lest.getValueAt(row, 0).toString();
        String days = Lest.getValueAt(row, 1).toString();
        String f = Lest.getValueAt(row, 2).toString();
        String t = Lest.getValueAt(row, 3).toString();
        String sh = Lest.getValueAt(row, 4).toString();
        int d = JOptionPane.showConfirmDialog(this, "هل تريد حذف المحدد ؟");
        if (d == JOptionPane.YES_OPTION) {
            String strd = "DELETE FROM DOC_TIMES WHERE DNUM=" + id + " and days='" + days + "' and t_from='" + f + "' and t_to='" + t + "' and shift="+ sh ;
            boolean ifd = DB.GO.runNunQuery(strd);
            if (ifd) {
                Listed();
                JOptionPane.showMessageDialog(this, "تم حذف البيانات", "نجح", JOptionPane.WARNING_MESSAGE);
                //Show3.setVisible(true);
                //Show3.setEnabled(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "لم يتم حذف شيئ", "خطأ", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_DeleteMouseClicked

    private void DeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseEntered
        Delete1.setEnabled(true);
        Delete1.setVisible(true);
    }//GEN-LAST:event_DeleteMouseEntered

    private void DeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseExited
        Delete1.setEnabled(false);
        Delete1.setVisible(false);
    }//GEN-LAST:event_DeleteMouseExited
public void lestD() {
        try {
            Connection con = DB.ConectionDB.setconn();
            String strs = "SELECT * FROM Doctors WHERE name like '%" + DName.getSelectedItem() + "%'";
            Statement st = con.createStatement();
            ResultSet r = st.executeQuery(strs);
            
            while (r.next()) {
                r.getString(1);
                r.getString(2);
                if (DName.getSelectedItem().equals(r.getString(2))) {
                    docid.setText(r.getString(1));
                }
                
            }
        } catch (Exception ex) {
            
        }
    }
public void lestDi() {
        try {
            Connection con = DB.ConectionDB.setconn();
            String strs = "SELECT * FROM Doctors WHERE name like '%" + Dnam.getSelectedItem() + "%'";
            Statement st = con.createStatement();
            ResultSet r = st.executeQuery(strs);
            
            while (r.next()) {
                r.getString(1);
                r.getString(2);
                if (Dnam.getSelectedItem().equals(r.getString(2))) {
                    DID.setText(r.getString(1));
                }
                
            }
        } catch (Exception ex) {
            
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DB.GO.icon(this);
        DB.GO.fillCompo("doctors","Name", DName);
        
        DB.GO.fillCompo("Doctors", "Name", Dnam);
        DName.setSelectedItem(null);
        Dnam.setSelectedItem(null);
        
    }//GEN-LAST:event_formWindowOpened

    private void SearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseEntered
        Search1.setVisible(true);
        Search1.setEnabled(true);
    }//GEN-LAST:event_SearchMouseEntered

    private void SearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseExited
        Search1.setVisible(false);
        Search1.setEnabled(false);
    }//GEN-LAST:event_SearchMouseExited

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
        Listed();
    }//GEN-LAST:event_SearchMouseClicked

    private void DNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DNameItemStateChanged
        lestD();
    }//GEN-LAST:event_DNameItemStateChanged

    private void DnamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DnamItemStateChanged
        lestDi();
    }//GEN-LAST:event_DnamItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Times.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Times.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Times.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Times.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Times().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add;
    private javax.swing.JLabel Add1;
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Back1;
    private javax.swing.JLabel DID;
    private javax.swing.JComboBox<String> DName;
    private javax.swing.JComboBox<String> Days;
    private javax.swing.JLabel Delete;
    private javax.swing.JLabel Delete1;
    private javax.swing.JComboBox<String> Dnam;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Exit1;
    private javax.swing.JTable Lest;
    private javax.swing.JLabel Main1;
    private javax.swing.JLabel Main2;
    private javax.swing.JLabel Search;
    private javax.swing.JLabel Search1;
    private javax.swing.JComboBox<String> Shift;
    private javax.swing.JLabel Show1;
    private javax.swing.JLabel Show2;
    private javax.swing.JLabel Show3;
    private javax.swing.JPanel Times;
    private javax.swing.JPanel TimesShow;
    private javax.swing.JLabel Update;
    private javax.swing.JLabel Update1;
    private javax.swing.JLabel _;
    private javax.swing.JLabel _1;
    private javax.swing.JLabel docid;
    private javax.swing.JSpinner from;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner to;
    private javax.swing.JLabel x;
    private javax.swing.JLabel x1;
    // End of variables declaration//GEN-END:variables

    private void fromKeyTyped(MouseEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void toKeyTyped(MouseEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
