/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahmed Kassem
 */
public class UserRegister extends javax.swing.JFrame {

    int mousex;
    int mousey;

    /**
     * Creates new form UserRegister
     */
    public UserRegister() {
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        ShowUser.setEnabled(false);
        ShowUser.setVisible(false);
        Add1.setEnabled(false);
        Add1.setVisible(false);
        Show1.setEnabled(false);
        Show1.setVisible(false);
        Show2.setEnabled(false);
        Show2.setVisible(false);
        Home1.setEnabled(false);
        Home1.setVisible(false);
        x1.setEnabled(false);
        x1.setVisible(false);
        _1.setEnabled(false);
        _1.setVisible(false);
        Back1.setEnabled(false);
        Back1.setVisible(false);
        Update1.setEnabled(false);
        Update1.setVisible(false);
        Delete1.setEnabled(false);
        Delete1.setVisible(false);
        Lest.getTableHeader().setReorderingAllowed(false);
        Lest.getTableHeader().setBackground(new Color(102, 102, 102));
        Lest.getTableHeader().setForeground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        x = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        _ = new javax.swing.JLabel();
        _1 = new javax.swing.JLabel();
        Show = new javax.swing.JLabel();
        Show1 = new javax.swing.JLabel();
        Show2 = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Home1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ShowUser = new javax.swing.JPanel();
        Back = new javax.swing.JLabel();
        Back1 = new javax.swing.JLabel();
        Update = new javax.swing.JLabel();
        Update1 = new javax.swing.JLabel();
        Delete = new javax.swing.JLabel();
        Delete1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lest = new javax.swing.JTable();
        MainU1 = new javax.swing.JLabel();
        ShowUser1 = new javax.swing.JPanel();
        Add = new javax.swing.JLabel();
        Add1 = new javax.swing.JLabel();
        UName = new javax.swing.JTextField();
        Pass = new javax.swing.JTextField();
        NameU = new javax.swing.JComboBox<>();
        Position = new javax.swing.JComboBox<>();
        ID = new javax.swing.JTextField();
        MainU = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });
        getContentPane().add(x);
        x.setBounds(921, 1, 17, 18);

        x1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/13.png"))); // NOI18N
        x1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(x1);
        x1.setBounds(917, -1, 24, 22);

        _.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _MouseExited(evt);
            }
        });
        getContentPane().add(_);
        _.setBounds(903, 1, 16, 18);

        _1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/15.png"))); // NOI18N
        getContentPane().add(_1);
        _1.setBounds(896, -1, 22, 22);

        Show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ShowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ShowMouseExited(evt);
            }
        });
        getContentPane().add(Show);
        Show.setBounds(52, 201, 195, 33);

        Show1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Show User.png"))); // NOI18N
        getContentPane().add(Show1);
        Show1.setBounds(52, 201, 195, 33);

        Show2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Show User.png"))); // NOI18N
        getContentPane().add(Show2);
        Show2.setBounds(52, 201, 195, 33);

        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });
        getContentPane().add(Home);
        Home.setBounds(52, 409, 195, 33);

        Home1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home.png"))); // NOI18N
        getContentPane().add(Home1);
        Home1.setBounds(52, 409, 195, 33);

        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 20);

        ShowUser.setLayout(null);

        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
        });
        ShowUser.add(Back);
        Back.setBounds(52, 132, 195, 33);

        Back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        ShowUser.add(Back1);
        Back1.setBounds(52, 132, 195, 33);

        Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateMouseExited(evt);
            }
        });
        ShowUser.add(Update);
        Update.setBounds(52, 270, 195, 33);

        Update1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Update.png"))); // NOI18N
        ShowUser.add(Update1);
        Update1.setBounds(52, 270, 195, 33);

        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteMouseExited(evt);
            }
        });
        ShowUser.add(Delete);
        Delete.setBounds(50, 340, 195, 33);

        Delete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete.png"))); // NOI18N
        ShowUser.add(Delete1);
        Delete1.setBounds(50, 340, 195, 33);

        Lest.setBackground(new java.awt.Color(184, 197, 251));
        Lest.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Lest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "رقم التسلسل", "الوظيفة", "الاسم", "اسم المستخدم", "كلمة المرور"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Lest.setGridColor(new java.awt.Color(51, 51, 51));
        Lest.setOpaque(false);
        Lest.setSelectionBackground(new java.awt.Color(102, 102, 102));
        Lest.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(Lest);

        ShowUser.add(jScrollPane1);
        jScrollPane1.setBounds(300, 130, 600, 310);

        MainU1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UserName2.png"))); // NOI18N
        ShowUser.add(MainU1);
        MainU1.setBounds(0, 0, 940, 506);

        getContentPane().add(ShowUser);
        ShowUser.setBounds(0, 0, 940, 506);

        ShowUser1.setLayout(null);

        Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddMouseExited(evt);
            }
        });
        ShowUser1.add(Add);
        Add.setBounds(52, 132, 195, 33);

        Add1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add.png"))); // NOI18N
        ShowUser1.add(Add1);
        Add1.setBounds(52, 132, 195, 33);

        UName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UName.setForeground(new java.awt.Color(51, 51, 51));
        UName.setBorder(null);
        UName.setOpaque(false);
        ShowUser1.add(UName);
        UName.setBounds(522, 336, 210, 30);

        Pass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Pass.setForeground(new java.awt.Color(51, 51, 51));
        Pass.setBorder(null);
        Pass.setOpaque(false);
        ShowUser1.add(Pass);
        Pass.setBounds(522, 403, 210, 29);

        NameU.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NameU.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        NameU.setOpaque(false);
        ShowUser1.add(NameU);
        NameU.setBounds(521, 271, 220, 29);

        Position.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "DR", "EMP" }));
        Position.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Position.setOpaque(false);
        Position.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                PositionItemStateChanged(evt);
            }
        });
        Position.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                PositionPropertyChange(evt);
            }
        });
        ShowUser1.add(Position);
        Position.setBounds(578, 205, 160, 29);

        ID.setEditable(false);
        ID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ID.setBorder(null);
        ID.setOpaque(false);
        ShowUser1.add(ID);
        ID.setBounds(581, 138, 150, 29);

        MainU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NewUser.png"))); // NOI18N
        ShowUser1.add(MainU);
        MainU.setBounds(0, 0, 940, 506);

        getContentPane().add(ShowUser1);
        ShowUser1.setBounds(0, 0, 940, 506);

        setBounds(0, 0, 940, 506);
    }// </editor-fold>//GEN-END:initComponents

    private void AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseEntered
        Add1.setEnabled(true);
        Add1.setVisible(true);
    }//GEN-LAST:event_AddMouseEntered

    private void AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseExited
        Add1.setEnabled(false);
        Add1.setVisible(false);
    }//GEN-LAST:event_AddMouseExited

    private void ShowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseEntered
        Show1.setEnabled(true);
        Show1.setVisible(true);
    }//GEN-LAST:event_ShowMouseEntered

    private void ShowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseExited
        Show1.setEnabled(false);
        Show1.setVisible(false);
    }//GEN-LAST:event_ShowMouseExited

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        Home1.setEnabled(true);
        Home1.setVisible(true);
    }//GEN-LAST:event_HomeMouseEntered

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        Home1.setEnabled(false);
        Home1.setVisible(false);
    }//GEN-LAST:event_HomeMouseExited

    public void clearData() {
        Controls.Tools.clearText(this);
        Position.setSelectedItem("");
        ID.setText(DB.GO.autoNumber("users", "IDNumber"));
        NameU.setSelectedItem(null);
    }
    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
        if ("".equals(ID.getText()) || "".equals(Position.getSelectedItem()) || "".equals(NameU.getSelectedItem()) || "".equals(UName.getText()) || "".equals(Pass.getText())) {
            JOptionPane.showMessageDialog(this, "رجاء ادخال جميع البيانات ", "خطأ", JOptionPane.ERROR_MESSAGE);
        } else {
            String str = "insert into users values (" + ID.getText() + " , '" + Position.getSelectedItem() + "' , '" + NameU.getSelectedItem() + "' , '" + UName.getText() + "' , '" + Pass.getText() + "')";
            boolean ifAdd = DB.GO.runNunQuery(str);
            if (ifAdd) {
                JOptionPane.showMessageDialog(this, "تم تسجيل البيانات", "نجح", JOptionPane.WARNING_MESSAGE);
                clearData();
            } else {
                JOptionPane.showMessageDialog(this, "لم يتم تسجيل البيانات", "خطأ", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_AddMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DB.GO.icon(this);
        ID.setText(DB.GO.autoNumber("users", "IDNumber"));

    }//GEN-LAST:event_formWindowOpened

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        int a = JOptionPane.showConfirmDialog(this, "هل تريد الخروج ؟", "Exit", JOptionPane.WARNING_MESSAGE);

        if (a == JOptionPane.YES_OPTION) {
            this.dispose();
        } else {

        }
    }//GEN-LAST:event_xMouseClicked

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
        x1.setEnabled(true);
        x1.setVisible(true);
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
        x1.setEnabled(false);
        x1.setVisible(false);
    }//GEN-LAST:event_xMouseExited

    private void _MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseClicked
        this.setState(MainFormE.ICONIFIED);
    }//GEN-LAST:event__MouseClicked

    private void _MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseEntered
        _1.setEnabled(true);
        _1.setVisible(true);
    }//GEN-LAST:event__MouseEntered

    private void _MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__MouseExited
        _1.setEnabled(false);
        _1.setVisible(false);
    }//GEN-LAST:event__MouseExited
    public void listed() {
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("رقم التسلسل");
        table.addColumn("الوظيفة");
        table.addColumn("الاسم");
        table.addColumn("اسم المستخدم");
        table.addColumn("كلمة المرور");
        try {
            Connection con = DB.ConectionDB.setconn();
            String strS = "SELECT * FROM USERS";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(strS);

            while (rs.next()) {
                table.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),});
            }
            Lest.setModel(table);
        } catch (Exception e) {

        }

    }
    private void ShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseClicked
        ShowUser.setEnabled(true);
        ShowUser.setVisible(true);
        ShowUser1.setEnabled(false);
        ShowUser1.setVisible(false);
        Show2.setEnabled(true);
        Show2.setVisible(true);
        listed();
    }//GEN-LAST:event_ShowMouseClicked

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
        Back1.setEnabled(true);
        Back1.setVisible(true);
    }//GEN-LAST:event_BackMouseEntered

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
        Back1.setEnabled(false);
        Back1.setVisible(false);
    }//GEN-LAST:event_BackMouseExited

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        ShowUser.setEnabled(false);
        ShowUser.setVisible(false);
        ShowUser1.setEnabled(true);
        ShowUser1.setVisible(true);
        Show2.setEnabled(false);
        Show2.setVisible(false);
    }//GEN-LAST:event_BackMouseClicked

    private void UpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseEntered
        Update1.setEnabled(true);
        Update1.setVisible(true);
    }//GEN-LAST:event_UpdateMouseEntered

    private void UpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseExited
        Update1.setEnabled(false);
        Update1.setVisible(false);
    }//GEN-LAST:event_UpdateMouseExited

    private void DeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseEntered
        Delete1.setEnabled(true);
        Delete1.setVisible(true);
    }//GEN-LAST:event_DeleteMouseEntered

    private void DeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseExited
        Delete1.setEnabled(false);
        Delete1.setVisible(false);
    }//GEN-LAST:event_DeleteMouseExited

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mousex, y - mousey);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        int row = Lest.getSelectedRow();
        String ID = Lest.getValueAt(row, 0).toString();

        int d = JOptionPane.showConfirmDialog(this, "هل تريد حذف المحدد ؟", "Delete", JOptionPane.WARNING_MESSAGE);
        if (d == JOptionPane.YES_OPTION) {

            String strd = "delete from users where IDnumber=" + ID;
            boolean ifD = DB.GO.runNunQuery(strd);
            if (ifD) {
                JOptionPane.showMessageDialog(this, "تم حذف البيانات", "نجح", JOptionPane.WARNING_MESSAGE);
                listed();
                //Show2.setEnabled(true);
                //Show2.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "لم يتم حذف شيئ", "خطأ", JOptionPane.WARNING_MESSAGE);
            //Show2.setEnabled(true);
            //Show2.setVisible(true);
        }


    }//GEN-LAST:event_DeleteMouseClicked

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        int row = Lest.getSelectedRow();
        String ID = Lest.getValueAt(row, 0).toString();
        String Name = Lest.getValueAt(row, 2).toString();
        String UName = Lest.getValueAt(row, 3).toString();
        String Pass = Lest.getValueAt(row, 4).toString();
        if ("".equals(row)) {
            JOptionPane.showMessageDialog(this, "حدد الصف الذي تريد حذفة", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String strU = "UPDATE USERS SET NAME='" + Name + "', USERNAME='" + UName + "', PASS='" + Pass + "' WHERE NUMBER=" + ID;
            boolean ifU = DB.GO.runNunQuery(strU);
            if (ifU) {
                JOptionPane.showMessageDialog(this, "تم تعديل البيانات", "نجح", JOptionPane.WARNING_MESSAGE);
                listed();
                //Show2.setEnabled(true);
                //Show2.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "لم يتم تعديل البيانات", "خطأ", JOptionPane.ERROR_MESSAGE);
                //Show2.setEnabled(true);
                //Show2.setVisible(true);
            }
            //Show2.setEnabled(true);
            //Show2.setVisible(true);
        }
    }//GEN-LAST:event_UpdateMouseClicked
    public void compoPosition() {
        if (Position.getSelectedItem().equals("DR")) {
            NameU.removeAllItems();
            DB.GO.fillCompo("doctors", "Name", NameU);
        } else if (Position.getSelectedItem().equals("EMP")) {
            NameU.removeAllItems();
            DB.GO.fillCompo("Employees", "Name", NameU);
        } else {
            NameU.removeAllItems();
        }
    }
    private void PositionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_PositionItemStateChanged
        //DB.GO.fillCompo("Doctors", "Name", Name);
        compoPosition();
    }//GEN-LAST:event_PositionItemStateChanged

    private void PositionPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_PositionPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_PositionPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add;
    private javax.swing.JLabel Add1;
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Back1;
    private javax.swing.JLabel Delete;
    private javax.swing.JLabel Delete1;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Home1;
    private javax.swing.JTextField ID;
    private javax.swing.JTable Lest;
    private javax.swing.JLabel MainU;
    private javax.swing.JLabel MainU1;
    private javax.swing.JComboBox<String> NameU;
    private javax.swing.JTextField Pass;
    private javax.swing.JComboBox<String> Position;
    private javax.swing.JLabel Show;
    private javax.swing.JLabel Show1;
    private javax.swing.JLabel Show2;
    private javax.swing.JPanel ShowUser;
    private javax.swing.JPanel ShowUser1;
    private javax.swing.JTextField UName;
    private javax.swing.JLabel Update;
    private javax.swing.JLabel Update1;
    private javax.swing.JLabel _;
    private javax.swing.JLabel _1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel x;
    private javax.swing.JLabel x1;
    // End of variables declaration//GEN-END:variables
}
